;; a.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The A extension: the atomic memory operations — Zalrsc's load-reserved/store-conditional pairs and Zaamo's nine AMOs, each .W and .D (22 forms; the pinned RVWMO chapter's Tables 6/7 enumerate exactly this set). It OWNS the aq and rl operand fields (the ordering bits — the pinned arg_lut.csv carries them at 26..26 and 25..25 and the combined aqrl at 26..25; the tables list aq and rl as separate operand tokens, and the .aq/.rl/.aqrl mnemonic suffix supplies their VALUES at assembly time, so they are never positional operand spellings). lr's rs2-must-be-zero rule is the row's own 24..20=0 fixed field, not a special case. REQUIRES a base: it reuses rd/rs1/rs2 from it (P4-SYSTEM.4 slice a).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/a")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_a") (sha256 "d9eaa988c4779ca352d9da9eabacf6c71771d0b81e04b234302627f69e0863d9"))
    (file (name "rv64_a") (sha256 "819e0487131bc97cfc0b6f3de62390f2f9936b43e80aef7c6cec14fbe7c7a1b6"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- operand field positions, inclusive bit ranges ------------------
  (field (name aq) (hi 26) (lo 26))
  (field (name rl) (hi 25) (lo 25))

  ;; ---- 22 instruction(s) ----
  (insn (name amoadd.d) (fixed (31 29 0x0) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amoadd.w) (fixed (31 29 0x0) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amoand.d) (fixed (31 29 0x3) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amoand.w) (fixed (31 29 0x3) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amomax.d) (fixed (31 29 0x5) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amomax.w) (fixed (31 29 0x5) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amomaxu.d) (fixed (31 29 0x7) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amomaxu.w) (fixed (31 29 0x7) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amomin.d) (fixed (31 29 0x4) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amomin.w) (fixed (31 29 0x4) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amominu.d) (fixed (31 29 0x6) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amominu.w) (fixed (31 29 0x6) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amoor.d) (fixed (31 29 0x2) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amoor.w) (fixed (31 29 0x2) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amoswap.d) (fixed (31 29 0x0) (28 27 0x1) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amoswap.w) (fixed (31 29 0x0) (28 27 0x1) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name amoxor.d) (fixed (31 29 0x1) (28 27 0x0) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name amoxor.w) (fixed (31 29 0x1) (28 27 0x0) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
  (insn (name lr.d) (fixed (24 20 0x0) (31 29 0x0) (28 27 0x2) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 aq rl) (from "rv64_a"))
  (insn (name lr.w) (fixed (24 20 0x0) (31 29 0x0) (28 27 0x2) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 aq rl) (from "rv_a"))
  (insn (name sc.d) (fixed (31 29 0x0) (28 27 0x3) (14 12 0x3) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv64_a"))
  (insn (name sc.w) (fixed (31 29 0x0) (28 27 0x3) (14 12 0x2) (6 2 0xb) (1 0 0x3)) (operands rd rs1 rs2 aq rl) (from "rv_a"))
)
