;; c.sem.sexp — what each compressed instruction DOES: the 37 forms at RV64 with D (Zca + Zcd),
;; each DECLARED BY ITS EXPANSION (P4-SYSTEM.12 slice b).
;;
;; ⛔ HAND-WRITTEN FROM THE PINNED SPECIFICATION (RVI-C, the v20260120 snapshot's §27.1). The chapter's
;; own constraint is the representation: "each RVC instruction expands into a single 32-bit
;; instruction" (§27.1.1). So a row names the base instruction it expands into (`to`) and binds
;; the operands that base rule reads to expressions over this instruction's fields — the engine
;; runs the BASE rule. Every source quotes the chapter's own "expands" sentence (single-quoted, so
;; CITATION-QUOTES judges it in its section), and that sentence names the base.
;;
;; THE OPERAND MAPPINGS. A 3-bit register field names x8..x15: (add (field rd_p) (lit 8)). An
;; immediate is the OR of its scattered pieces, each placed at its bit position (the piece tables
;; in c.sexp); a piece carries the width of the immediate it composes, so a signed immediate is
;; sign-extended from its own top bit by the base rule's (sext 64 …), and an unsigned one is
;; (zext 12 …)'d first so that sign extension finds a zero. C.LUI's imm is nzimm[17:12] as
;; LUI's 20-bit field: (sext 20 (bits 17 12 …)).
;;
;; RESERVED code points are the chapter's "are reserved" sentences, quoted; HINTs are not listed —
;; the chapter says an implementation may execute a HINT "as a regular computational instruction
;; that happens not to mutate the architectural state", which is exactly the expansion (§27.1.7).
;; C.JALR alone carries its own rule: the chapter says it "does not expand exactly" (the link is
;; pc+2).

(semantics (fragment "riscv/c") (xlen 64)
  (expand (insn c.addi4spn) (to addi)
          (operand (name rd) (value (add (field rd_p) (lit 8)))) (operand (name rs1) (value (lit 2))) (operand (name imm12) (value (zext 12 (imm c_nzuimm10))))
          (reserved (eq (imm c_nzuimm10) (lit 0)))
          (source "RVI-C §27.1.5.2 — 'expands to addi rd′, x2, nzuimm[9:2]'; 'C.ADDI4SPN is valid only when nzuimm≠0; the code points with nzuimm=0 are reserved' (the all-zero parcel among them)"))
  (expand (insn c.fld) (to fld)
          (operand (name rd) (value (add (field rd_p) (lit 8)))) (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm8hi) (imm c_uimm8lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to fld rd′, offset(rs1′)' — the offset zero-extended, scaled by 8"))
  (expand (insn c.lw) (to lw)
          (operand (name rd) (value (add (field rd_p) (lit 8)))) (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm7hi) (imm c_uimm7lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to lw rd′, offset(rs1′)' — the offset zero-extended, scaled by 4"))
  (expand (insn c.ld) (to ld)
          (operand (name rd) (value (add (field rd_p) (lit 8)))) (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm8hi) (imm c_uimm8lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to ld rd′, offset(rs1′)' — the offset zero-extended, scaled by 8"))
  (expand (insn c.fsd) (to fsd)
          (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm8hi) (imm c_uimm8lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to fsd rs2′, offset(rs1′)'"))
  (expand (insn c.sw) (to sw)
          (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm7hi) (imm c_uimm7lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to sw rs2′, offset(rs1′)'"))
  (expand (insn c.sd) (to sd)
          (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8)))) (operand (name imm12) (value (zext 12 (or (imm c_uimm8hi) (imm c_uimm8lo)))))
          (source "RVI-C §27.1.3.2 — 'It expands to sd rs2′, offset(rs1′)'"))
  (expand (insn c.nop) (to addi)
          (operand (name rd) (value (lit 0))) (operand (name rs1) (value (lit 0))) (operand (name imm12) (value (or (imm c_nzimm6hi) (imm c_nzimm6lo))))
          (source "RVI-C §27.1.5.2 — 'The code points with rd=x0 encode the C.NOP instruction'; 'C.ADDI expands into addi rd, rd, imm' — with rd = x0 (its nonzero-immediate code points HINTs: no state changes)"))
  (expand (insn c.addi) (to addi)
          (operand (name rd) (value (field rd_rs1_n0))) (operand (name rs1) (value (field rd_rs1_n0))) (operand (name imm12) (value (or (imm c_nzimm6hi) (imm c_nzimm6lo))))
          (source "RVI-C §27.1.5.2 — 'C.ADDI expands into addi rd, rd, imm' (the rd≠0, imm=0 code points HINTs)"))
  (expand (insn c.addiw) (to addiw)
          (operand (name rd) (value (field rd_rs1_n0))) (operand (name rs1) (value (field rd_rs1_n0))) (operand (name imm12) (value (or (imm c_imm6hi) (imm c_imm6lo))))
          (reserved (eq (field rd_rs1_n0) (lit 0)))
          (source "RVI-C §27.1.5.2 — 'C.ADDIW expands into addiw rd, rd, imm'; 'C.ADDIW is valid only when rd≠x0; the code points with rd=x0 are reserved'"))
  (expand (insn c.li) (to addi)
          (operand (name rd) (value (field rd_n0))) (operand (name rs1) (value (lit 0))) (operand (name imm12) (value (or (imm c_imm6hi) (imm c_imm6lo))))
          (source "RVI-C §27.1.5.1 — 'C.LI expands into addi rd, x0, imm' (the rd=x0 code points HINTs)"))
  (expand (insn c.addi16sp) (to addi)
          (operand (name rd) (value (lit 2))) (operand (name rs1) (value (lit 2))) (operand (name imm12) (value (or (imm c_nzimm10hi) (imm c_nzimm10lo))))
          (reserved (eq (or (imm c_nzimm10hi) (imm c_nzimm10lo)) (lit 0)))
          (source "RVI-C §27.1.5.2 — 'It expands into addi x2, x2, nzimm[9:4]'; 'C.ADDI16SP is valid only when nzimm≠0; the code point with nzimm=0 is reserved'"))
  (expand (insn c.lui) (to lui)
          (operand (name rd) (value (field rd_n2))) (operand (name imm20) (value (sext 20 (bits 17 12 (or (imm c_nzimm18hi) (imm c_nzimm18lo))))))
          (reserved (eq (or (imm c_nzimm18hi) (imm c_nzimm18lo)) (lit 0)))
          (source "RVI-C §27.1.5.1 — 'C.LUI expands into lui rd, imm'; 'The code points with imm=0 are reserved' — imm the 6-bit nzimm[17:12], sign-extended"))
  (expand (insn c.srli) (to srli)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name shamt) (value (or (imm c_nzuimm6hi) (imm c_nzuimm6lo))))
          (source "RVI-C §27.1.5.2 — 'C.SRLI expands into srli rd′, rd′, shamt' (the shamt=0 code points HINTs)"))
  (expand (insn c.srai) (to srai)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name shamt) (value (or (imm c_nzuimm6hi) (imm c_nzuimm6lo))))
          (source "RVI-C §27.1.5.2 — 'C.SRAI expands to srai rd′, rd′, shamt'"))
  (expand (insn c.andi) (to andi)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name imm12) (value (or (imm c_imm6hi) (imm c_imm6lo))))
          (source "RVI-C §27.1.5.2 — 'C.ANDI expands to andi rd′, rd′, imm'"))
  (expand (insn c.sub) (to sub)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.SUB expands into sub rd′, rd′, rs2′'"))
  (expand (insn c.xor) (to xor)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.XOR expands into xor rd′, rd′, rs2′'"))
  (expand (insn c.or) (to or)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.OR expands into or rd′, rd′, rs2′'"))
  (expand (insn c.and) (to and)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.AND expands into and rd′, rd′, rs2′'"))
  (expand (insn c.subw) (to subw)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.SUBW expands into subw rd′, rd′, rs2′'"))
  (expand (insn c.addw) (to addw)
          (operand (name rd) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs1) (value (add (field rd_rs1_p) (lit 8)))) (operand (name rs2) (value (add (field rs2_p) (lit 8))))
          (source "RVI-C §27.1.5.3 — 'C.ADDW expands into addw rd′, rd′, rs2′'"))
  (expand (insn c.j) (to jal)
          (operand (name rd) (value (lit 0))) (operand (name jimm20) (value (imm c_imm12)))
          (source "RVI-C §27.1.4 — 'C.J expands to jal x0, offset'"))
  (expand (insn c.beqz) (to beq)
          (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name rs2) (value (lit 0))) (operand (name bimm12) (value (or (imm c_bimm9hi) (imm c_bimm9lo))))
          (source "RVI-C §27.1.4 — 'It expands to beq rs1′, x0, offset'"))
  (expand (insn c.bnez) (to bne)
          (operand (name rs1) (value (add (field rs1_p) (lit 8)))) (operand (name rs2) (value (lit 0))) (operand (name bimm12) (value (or (imm c_bimm9hi) (imm c_bimm9lo))))
          (source "RVI-C §27.1.4 — 'It expands to bne rs1′, x0, offset'"))
  (expand (insn c.slli) (to slli)
          (operand (name rd) (value (field rd_rs1_n0))) (operand (name rs1) (value (field rd_rs1_n0))) (operand (name shamt) (value (or (imm c_nzuimm6hi) (imm c_nzuimm6lo))))
          (source "RVI-C §27.1.5.2 — 'C.SLLI expands into slli rd, rd, shamt[5:0]' (the shamt=0 or rd=x0 code points HINTs)"))
  (expand (insn c.fldsp) (to fld)
          (operand (name rd) (value (field rd))) (operand (name rs1) (value (lit 2))) (operand (name imm12) (value (zext 12 (or (imm c_uimm9sphi) (imm c_uimm9splo)))))
          (source "RVI-C §27.1.3.1 — 'It expands to fld rd, offset(x2)'"))
  (expand (insn c.lwsp) (to lw)
          (operand (name rd) (value (field rd_n0))) (operand (name rs1) (value (lit 2))) (operand (name imm12) (value (zext 12 (or (imm c_uimm8sphi) (imm c_uimm8splo)))))
          (reserved (eq (field rd_n0) (lit 0)))
          (source "RVI-C §27.1.3.1 — 'It expands to lw rd, offset(x2)'; 'C.LWSP is valid only when rd≠x0; the code points with rd=x0 are reserved'"))
  (expand (insn c.ldsp) (to ld)
          (operand (name rd) (value (field rd_n0))) (operand (name rs1) (value (lit 2))) (operand (name imm12) (value (zext 12 (or (imm c_uimm9sphi) (imm c_uimm9splo)))))
          (reserved (eq (field rd_n0) (lit 0)))
          (source "RVI-C §27.1.3.1 — 'It expands to ld rd, offset(x2)'; 'C.LDSP is valid only when rd≠x0; the code points with rd=x0 are reserved'"))
  (expand (insn c.jr) (to jalr)
          (operand (name rd) (value (lit 0))) (operand (name rs1) (value (field rs1_n0))) (operand (name imm12) (value (lit 0)))
          (reserved (eq (field rs1_n0) (lit 0)))
          (source "RVI-C §27.1.4 — 'C.JR expands to jalr x0, 0(rs1)'; 'C.JR is valid only when rs1≠x0; the code point with rs1=x0 is reserved'"))
  (expand (insn c.mv) (to add)
          (operand (name rd) (value (field rd_n0))) (operand (name rs1) (value (lit 0))) (operand (name rs2) (value (field c_rs2_n0)))
          (source "RVI-C §27.1.5.3 — 'C.MV expands into add rd, x0, rs2' (the rd=x0 code points HINTs)"))
  (expand (insn c.ebreak) (to ebreak)
          (source "RVI-C §27.1.5.6 — 'Debuggers can use the C.EBREAK instruction, which expands to ebreak'"))
  (expand (insn c.add) (to add)
          (operand (name rd) (value (field rd_rs1_n0))) (operand (name rs1) (value (field rd_rs1_n0))) (operand (name rs2) (value (field c_rs2_n0)))
          (source "RVI-C §27.1.5.3 — 'C.ADD expands into add rd, rd, rs2' (the rd=x0 code points HINTs)"))
  (expand (insn c.fsdsp) (to fsd)
          (operand (name rs1) (value (lit 2))) (operand (name rs2) (value (field c_rs2))) (operand (name imm12) (value (zext 12 (imm c_uimm9sp_s))))
          (source "RVI-C §27.1.3.1 — 'It expands to fsd rs2, offset(x2)'"))
  (expand (insn c.swsp) (to sw)
          (operand (name rs1) (value (lit 2))) (operand (name rs2) (value (field c_rs2))) (operand (name imm12) (value (zext 12 (imm c_uimm8sp_s))))
          (source "RVI-C §27.1.3.1 — 'It expands to sw rs2, offset(x2)'"))
  (expand (insn c.sdsp) (to sd)
          (operand (name rs1) (value (lit 2))) (operand (name rs2) (value (field c_rs2))) (operand (name imm12) (value (zext 12 (imm c_uimm9sp_s))))
          (source "RVI-C §27.1.3.1 — 'It expands to sd rs2, offset(x2)'"))
  (expand (insn c.jalr)
          (operand (name rd) (value (lit 1))) (operand (name rs1) (value (field c_rs1_n0)))
          (effect (seq (set-pc (and (reg rs1) (lit -2)))
                       (set (reg rd) (add (pc) (lit 2)))))
          (source "RVI-C §27.1.4 — 'C.JALR expands to jalr x1, 0(rs1)'; 'Strictly speaking, C.JALR does not expand exactly to a base RVI instruction as the value added to the PC to form the link address is 2 rather than 4' — its own rule: jalr's, the link pc+2")))
