;; d.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The D extension: double-precision floating point — 32 forms (26 in rv_d: the FLD/FSD transfers, the four fused multiply-adds, add/sub/mul/div/sqrt, sign injection, min/max, the two format conversions FCVT.S.D/FCVT.D.S, the three compares, fclass and the 32-bit integer conversions; 6 in rv64_d: the 64-bit integer conversions and the FMV.X.D/FMV.D.X bit moves). It owns NO operand field: rs3 and rm are F's, and it REQUIRES riscv/f by name for them — and because the chapter states it (D depends on F, RVI-D 21.1). The tables' 3 $pseudo_op rows (fmv.d/fabs.d/fneg.d) are NOT carried: they spell the sign-injection forms (the rv64i write-it-out policy, as F's) (P4-SYSTEM.7 slice d1).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/d")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (requires "riscv/f")
  (source
    (file (name "rv_d") (sha256 "24bc7c6384f9a009dbafb3f177ec68b0d4f8fb1c2c2b7b07767320fdd7d4acbc"))
    (file (name "rv64_d") (sha256 "883e668be4c536d0dfdb8c02bd1f3eb959801eb953f1fb7a4b4e5e623cbf19a9"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- 32 instruction(s) ----
  (insn (name fadd.d) (fixed (31 27 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_d"))
  (insn (name fclass.d) (fixed (24 20 0x0) (31 27 0x1c) (14 12 0x1) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv_d"))
  (insn (name fcvt.d.l) (fixed (24 20 0x2) (31 27 0x1a) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_d"))
  (insn (name fcvt.d.lu) (fixed (24 20 0x3) (31 27 0x1a) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_d"))
  (insn (name fcvt.d.s) (fixed (24 20 0x0) (31 27 0x8) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fcvt.d.w) (fixed (24 20 0x0) (31 27 0x1a) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fcvt.d.wu) (fixed (24 20 0x1) (31 27 0x1a) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fcvt.l.d) (fixed (24 20 0x2) (31 27 0x18) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_d"))
  (insn (name fcvt.lu.d) (fixed (24 20 0x3) (31 27 0x18) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_d"))
  (insn (name fcvt.s.d) (fixed (24 20 0x1) (31 27 0x8) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fcvt.w.d) (fixed (24 20 0x0) (31 27 0x18) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fcvt.wu.d) (fixed (24 20 0x1) (31 27 0x18) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fdiv.d) (fixed (31 27 0x3) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_d"))
  (insn (name feq.d) (fixed (31 27 0x14) (14 12 0x2) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fld) (fixed (14 12 0x3) (6 2 0x1) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_d"))
  (insn (name fle.d) (fixed (31 27 0x14) (14 12 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name flt.d) (fixed (31 27 0x14) (14 12 0x1) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fmadd.d) (fixed (26 25 0x1) (6 2 0x10) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_d"))
  (insn (name fmax.d) (fixed (31 27 0x5) (14 12 0x1) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fmin.d) (fixed (31 27 0x5) (14 12 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fmsub.d) (fixed (26 25 0x1) (6 2 0x11) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_d"))
  (insn (name fmul.d) (fixed (31 27 0x2) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_d"))
  (insn (name fmv.d.x) (fixed (24 20 0x0) (31 27 0x1e) (14 12 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv64_d"))
  (insn (name fmv.x.d) (fixed (24 20 0x0) (31 27 0x1c) (14 12 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv64_d"))
  (insn (name fnmadd.d) (fixed (26 25 0x1) (6 2 0x13) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_d"))
  (insn (name fnmsub.d) (fixed (26 25 0x1) (6 2 0x12) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_d"))
  (insn (name fsd) (fixed (14 12 0x3) (6 2 0x9) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv_d"))
  (insn (name fsgnj.d) (fixed (31 27 0x4) (14 12 0x0) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fsgnjn.d) (fixed (31 27 0x4) (14 12 0x1) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fsgnjx.d) (fixed (31 27 0x4) (14 12 0x2) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_d"))
  (insn (name fsqrt.d) (fixed (24 20 0x0) (31 27 0xb) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_d"))
  (insn (name fsub.d) (fixed (31 27 0x1) (26 25 0x1) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_d"))
)
