;; f.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The F extension: single-precision floating point — 30 forms (26 in rv_f: the FLW/FSW transfers, the four fused multiply-adds, add/sub/mul/div/sqrt, sign injection, min/max, the three compares, fclass, the 32-bit integer conversions and the FMV bit moves; 4 in rv64_f: the 64-bit integer conversions). It OWNS rs3 (the fused forms' third source) and rm (the rounding-mode field, which sits where the non-rounding rows carry a fixed funct3 — the rows decide which). rd/rs1/rs2 and the load/store immediates are the base's fields: which REGISTER FILE an operand addresses is the instruction's semantics (f.sem.sexp), not its encoding — the pinned rows name only the field. The tables' 13 $pseudo_op rows are NOT carried: they spell real forms (the rv64i write-it-out policy), and the pseudo flag is for forms that exist upstream ONLY as pseudo-ops (P4-SYSTEM.7 slice c2).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/f")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_f") (sha256 "227e09504c0d758add114d5a77ac06d7e2ffab9c6a9509633c4f531db58b3e3e"))
    (file (name "rv64_f") (sha256 "5c01c243ccd8a1c0e24a48a1ffcf62eecb10aa36fd6bdcedf7392e670cd46cf9"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- operand field positions, inclusive bit ranges ------------------
  (field (name rs3) (hi 31) (lo 27))
  (field (name rm) (hi 14) (lo 12))

  ;; ---- 30 instruction(s) ----
  (insn (name fadd.s) (fixed (31 27 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_f"))
  (insn (name fclass.s) (fixed (24 20 0x0) (31 27 0x1c) (14 12 0x1) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv_f"))
  (insn (name fcvt.l.s) (fixed (24 20 0x2) (31 27 0x18) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_f"))
  (insn (name fcvt.lu.s) (fixed (24 20 0x3) (31 27 0x18) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_f"))
  (insn (name fcvt.s.l) (fixed (24 20 0x2) (31 27 0x1a) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_f"))
  (insn (name fcvt.s.lu) (fixed (24 20 0x3) (31 27 0x1a) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv64_f"))
  (insn (name fcvt.s.w) (fixed (24 20 0x0) (31 27 0x1a) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_f"))
  (insn (name fcvt.s.wu) (fixed (24 20 0x1) (31 27 0x1a) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_f"))
  (insn (name fcvt.w.s) (fixed (24 20 0x0) (31 27 0x18) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_f"))
  (insn (name fcvt.wu.s) (fixed (24 20 0x1) (31 27 0x18) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_f"))
  (insn (name fdiv.s) (fixed (31 27 0x3) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_f"))
  (insn (name feq.s) (fixed (31 27 0x14) (14 12 0x2) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fle.s) (fixed (31 27 0x14) (14 12 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name flt.s) (fixed (31 27 0x14) (14 12 0x1) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name flw) (fixed (14 12 0x2) (6 2 0x1) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_f"))
  (insn (name fmadd.s) (fixed (26 25 0x0) (6 2 0x10) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_f"))
  (insn (name fmax.s) (fixed (31 27 0x5) (14 12 0x1) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fmin.s) (fixed (31 27 0x5) (14 12 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fmsub.s) (fixed (26 25 0x0) (6 2 0x11) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_f"))
  (insn (name fmul.s) (fixed (31 27 0x2) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_f"))
  (insn (name fmv.w.x) (fixed (24 20 0x0) (31 27 0x1e) (14 12 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv_f"))
  (insn (name fmv.x.w) (fixed (24 20 0x0) (31 27 0x1c) (14 12 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1) (from "rv_f"))
  (insn (name fnmadd.s) (fixed (26 25 0x0) (6 2 0x13) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_f"))
  (insn (name fnmsub.s) (fixed (26 25 0x0) (6 2 0x12) (1 0 0x3)) (operands rd rs1 rs2 rs3 rm) (from "rv_f"))
  (insn (name fsgnj.s) (fixed (31 27 0x4) (14 12 0x0) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fsgnjn.s) (fixed (31 27 0x4) (14 12 0x1) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fsgnjx.s) (fixed (31 27 0x4) (14 12 0x2) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_f"))
  (insn (name fsqrt.s) (fixed (24 20 0x0) (31 27 0xb) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rm) (from "rv_f"))
  (insn (name fsub.s) (fixed (31 27 0x1) (26 25 0x0) (6 2 0x14) (1 0 0x3)) (operands rd rs1 rs2 rm) (from "rv_f"))
  (insn (name fsw) (fixed (14 12 0x2) (6 2 0x9) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv_f"))
)
