;; m.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The M extension: integer multiply and divide. REQUIRES a base, because it reuses the base's R-type operand fields and defines none of its own — a fragment with a hidden dependency is a fragment that composes by luck.
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/m")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_m") (sha256 "1a53ea03820b7044de4f0f04d207c1e4fc0ced46deb2c6ed4a3ca268fa37ddbe"))
    (file (name "rv64_m") (sha256 "112bf223a31b7cc51761ce1572a8a35c2502ab2c5a6e318db80c0601b587480e"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- 13 instruction(s) ----
  (insn (name div) (fixed (31 25 0x1) (14 12 0x4) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name divu) (fixed (31 25 0x1) (14 12 0x5) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name divuw) (fixed (31 25 0x1) (14 12 0x5) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_m"))
  (insn (name divw) (fixed (31 25 0x1) (14 12 0x4) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_m"))
  (insn (name mul) (fixed (31 25 0x1) (14 12 0x0) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name mulh) (fixed (31 25 0x1) (14 12 0x1) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name mulhsu) (fixed (31 25 0x1) (14 12 0x2) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name mulhu) (fixed (31 25 0x1) (14 12 0x3) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name mulw) (fixed (31 25 0x1) (14 12 0x0) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_m"))
  (insn (name rem) (fixed (31 25 0x1) (14 12 0x6) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name remu) (fixed (31 25 0x1) (14 12 0x7) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_m"))
  (insn (name remuw) (fixed (31 25 0x1) (14 12 0x7) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_m"))
  (insn (name remw) (fixed (31 25 0x1) (14 12 0x6) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_m"))
)
