;; rv64i.sexp — a reusable definition FRAGMENT (isa-base).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The RV64I base: the 52 instructions every RV64 profile starts from. Carries the operand field table and the scattered-immediate layouts, because a base defines the formats its extensions reuse.
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/rv64i")
  (kind isa-base)
  (requires)
  (source
    (file (name "rv_i") (sha256 "146e297ddbe346f325d993aaf56d7006f1bfde39df584b888b221543def17b97"))
    (file (name "rv64_i") (sha256 "262cbd0884fe1383fcb7c42070cbc73e309d0452ff8d00b38452a4dee7cfa7f5"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- operand field positions, inclusive bit ranges ------------------
  (field (name rd) (hi 11) (lo 7))
  (field (name rs1) (hi 19) (lo 15))
  (field (name rs2) (hi 24) (lo 20))
  (field (name imm12) (hi 31) (lo 20))
  (field (name imm20) (hi 31) (lo 12))
  (field (name shamtd) (hi 25) (lo 20))
  (field (name shamtw) (hi 24) (lo 20))
  (field (name imm12hi) (hi 31) (lo 25))
  (field (name imm12lo) (hi 11) (lo 7))
  (field (name jimm20) (hi 31) (lo 12))
  (field (name bimm12hi) (hi 31) (lo 25))
  (field (name bimm12lo) (hi 11) (lo 7))

  ;; ---- immediates SCATTERED across their field, MSB piece first -------
  (scatter (name bimm12hi) (hi 31) (lo 25) (pieces (12 12) (10 5)))
  (scatter (name bimm12lo) (hi 11) (lo 7) (pieces (4 1) (11 11)))
  (scatter (name jimm20) (hi 31) (lo 12) (pieces (20 20) (10 1) (11 11) (19 12)))

  ;; ---- 52 instruction(s) ----
  (insn (name add) (fixed (31 25 0x0) (14 12 0x0) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name addi) (fixed (14 12 0x0) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name addiw) (fixed (14 12 0x0) (6 2 0x6) (1 0 0x3)) (operands rd rs1 imm12) (from "rv64_i"))
  (insn (name addw) (fixed (31 25 0x0) (14 12 0x0) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_i"))
  (insn (name and) (fixed (31 25 0x0) (14 12 0x7) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name andi) (fixed (14 12 0x7) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name auipc) (fixed (6 2 0x5) (1 0 0x3)) (operands rd imm20) (from "rv_i"))
  (insn (name beq) (fixed (14 12 0x0) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name bge) (fixed (14 12 0x5) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name bgeu) (fixed (14 12 0x7) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name blt) (fixed (14 12 0x4) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name bltu) (fixed (14 12 0x6) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name bne) (fixed (14 12 0x1) (6 2 0x18) (1 0 0x3)) (operands bimm12hi rs1 rs2 bimm12lo) (from "rv_i"))
  (insn (name ebreak) (fixed (31 20 0x1) (19 7 0x0) (6 2 0x1c) (1 0 0x3)) (operands ) (from "rv_i"))
  (insn (name ecall) (fixed (31 20 0x0) (19 7 0x0) (6 2 0x1c) (1 0 0x3)) (operands ) (from "rv_i"))
  (insn (name fence) (fixed (14 12 0x0) (6 2 0x3) (1 0 0x3)) (operands fm pred succ rs1 rd) (from "rv_i"))
  (insn (name jal) (fixed (6 2 0x1b) (1 0 0x3)) (operands rd jimm20) (from "rv_i"))
  (insn (name jalr) (fixed (14 12 0x0) (6 2 0x19) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name lb) (fixed (14 12 0x0) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name lbu) (fixed (14 12 0x4) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name ld) (fixed (14 12 0x3) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv64_i"))
  (insn (name lh) (fixed (14 12 0x1) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name lhu) (fixed (14 12 0x5) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name lui) (fixed (6 2 0xd) (1 0 0x3)) (operands rd imm20) (from "rv_i"))
  (insn (name lw) (fixed (14 12 0x2) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name lwu) (fixed (14 12 0x6) (6 2 0x0) (1 0 0x3)) (operands rd rs1 imm12) (from "rv64_i"))
  (insn (name or) (fixed (31 25 0x0) (14 12 0x6) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name ori) (fixed (14 12 0x6) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name sb) (fixed (14 12 0x0) (6 2 0x8) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv_i"))
  (insn (name sd) (fixed (14 12 0x3) (6 2 0x8) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv64_i"))
  (insn (name sh) (fixed (14 12 0x1) (6 2 0x8) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv_i"))
  (insn (name sll) (fixed (31 25 0x0) (14 12 0x1) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name slli) (fixed (31 26 0x0) (14 12 0x1) (6 2 0x4) (1 0 0x3)) (operands rd rs1 shamtd) (from "rv64_i"))
  (insn (name slliw) (fixed (31 25 0x0) (14 12 0x1) (6 2 0x6) (1 0 0x3)) (operands rd rs1 shamtw) (from "rv64_i"))
  (insn (name sllw) (fixed (31 25 0x0) (14 12 0x1) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_i"))
  (insn (name slt) (fixed (31 25 0x0) (14 12 0x2) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name slti) (fixed (14 12 0x2) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name sltiu) (fixed (14 12 0x3) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
  (insn (name sltu) (fixed (31 25 0x0) (14 12 0x3) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name sra) (fixed (31 25 0x20) (14 12 0x5) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name srai) (fixed (31 26 0x10) (14 12 0x5) (6 2 0x4) (1 0 0x3)) (operands rd rs1 shamtd) (from "rv64_i"))
  (insn (name sraiw) (fixed (31 25 0x20) (14 12 0x5) (6 2 0x6) (1 0 0x3)) (operands rd rs1 shamtw) (from "rv64_i"))
  (insn (name sraw) (fixed (31 25 0x20) (14 12 0x5) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_i"))
  (insn (name srl) (fixed (31 25 0x0) (14 12 0x5) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name srli) (fixed (31 26 0x0) (14 12 0x5) (6 2 0x4) (1 0 0x3)) (operands rd rs1 shamtd) (from "rv64_i"))
  (insn (name srliw) (fixed (31 25 0x0) (14 12 0x5) (6 2 0x6) (1 0 0x3)) (operands rd rs1 shamtw) (from "rv64_i"))
  (insn (name srlw) (fixed (31 25 0x0) (14 12 0x5) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_i"))
  (insn (name sub) (fixed (31 25 0x20) (14 12 0x0) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name subw) (fixed (31 25 0x20) (14 12 0x0) (6 2 0xe) (1 0 0x3)) (operands rd rs1 rs2) (from "rv64_i"))
  (insn (name sw) (fixed (14 12 0x2) (6 2 0x8) (1 0 0x3)) (operands imm12hi rs1 rs2 imm12lo) (from "rv_i"))
  (insn (name xor) (fixed (31 25 0x0) (14 12 0x4) (6 2 0xc) (1 0 0x3)) (operands rd rs1 rs2) (from "rv_i"))
  (insn (name xori) (fixed (14 12 0x4) (6 2 0x4) (1 0 0x3)) (operands rd rs1 imm12) (from "rv_i"))
)
