;; system.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The privileged system instructions: mret and wfi (rv_system), sret and sfence.vma (rv_s) — the profile's selection from RVP-INSNS 18.1 (D-PRIV-INSNS). REQUIRES a base, because ecall/ebreak own the neighbouring fixed points of the SYSTEM opcode (P4-SYSTEM.2 slice a).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/system")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_system") (sha256 "4a58b5f0c908d7b748abbeb9df8335dbc53650ea284b738e4351afd49755e646"))
    (file (name "rv_s") (sha256 "e9d509a3a46de9024547fa75f76bf3c2839910ebc9af81d106cc46bc0ac6eb78"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- 4 instruction(s) ----
  (insn (name mret) (fixed (11 7 0x0) (19 15 0x0) (31 20 0x302) (14 12 0x0) (6 2 0x1c) (1 0 0x3)) (operands ) (from "rv_system"))
  (insn (name sfence.vma) (fixed (11 7 0x0) (31 25 0x9) (14 12 0x0) (6 2 0x1c) (1 0 0x3)) (operands rs1 rs2) (from "rv_s"))
  (insn (name sret) (fixed (11 7 0x0) (19 15 0x0) (31 20 0x102) (14 12 0x0) (6 2 0x1c) (1 0 0x3)) (operands ) (from "rv_s"))
  (insn (name wfi) (fixed (11 7 0x0) (19 15 0x0) (31 20 0x105) (14 12 0x0) (6 2 0x1c) (1 0 0x3)) (operands ) (from "rv_system"))
)
