;; zicntr.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The Zicntr extension: the base counter reads rdcycle/rdtime/rdinstret. It adds NO new encodings — upstream carries the three only as $pseudo_op rows of Zicsr's csrrs, each fully fixed by its row — so the fragment carries them as (pseudo …) assembler spellings and the encoding space is untouched. It REQUIRES Zicsr by name (the pinned rows say rv_zicsr::csrrs — the realizing instruction lives there), not only the base (P4-SYSTEM.2 slice a).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/zicntr")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (requires "riscv/zicsr")
  (source
    (file (name "rv_zicntr") (sha256 "34ed6bb1cf98448c7c40abbd6f67cbccee0788bd42429a2b1a9538952f6cca8c"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- 0 instruction(s) ----

  ;; ---- pseudo-instruction(s): assembler spellings, NOT new encodings ------
  ;; Each row's fixed bits specialize a real instruction's (the `of` base), so
  ;; the word it assembles is already in the encoding space.
  (pseudo (name rdcycle) (of "rv_zicsr::csrrs") (fixed (19 15 0x0) (31 20 0xc00) (14 12 0x2) (6 2 0x1c) (1 0 0x3)) (operands rd) (from "rv_zicntr"))
  (pseudo (name rdinstret) (of "rv_zicsr::csrrs") (fixed (19 15 0x0) (31 20 0xc02) (14 12 0x2) (6 2 0x1c) (1 0 0x3)) (operands rd) (from "rv_zicntr"))
  (pseudo (name rdtime) (of "rv_zicsr::csrrs") (fixed (19 15 0x0) (31 20 0xc01) (14 12 0x2) (6 2 0x1c) (1 0 0x3)) (operands rd) (from "rv_zicntr"))
)
