;; zicsr.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The Zicsr extension: the CSR access instructions csrrw/csrrs/csrrc and their immediate forms. It OWNS the csr and zimm5 operand fields (the base's field table predates them, and a field nothing owns is a field nobody can check); csr shares bits 31..20 with imm12 and the pinned arg_lut.csv distinguishes them by field name. REQUIRES a base: it reuses rd/rs1 from it (P4-SYSTEM.2 slice a).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/zicsr")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_zicsr") (sha256 "dd8cc0e2c32fb5658d4aa719cef6ab1b714e2145ba071c9aeb382d9963e4901f"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- operand field positions, inclusive bit ranges ------------------
  (field (name csr) (hi 31) (lo 20))
  (field (name zimm5) (hi 19) (lo 15))

  ;; ---- 6 instruction(s) ----
  (insn (name csrrc) (fixed (14 12 0x3) (6 2 0x1c) (1 0 0x3)) (operands rd rs1 csr) (from "rv_zicsr"))
  (insn (name csrrci) (fixed (14 12 0x7) (6 2 0x1c) (1 0 0x3)) (operands rd csr zimm5) (from "rv_zicsr"))
  (insn (name csrrs) (fixed (14 12 0x2) (6 2 0x1c) (1 0 0x3)) (operands rd rs1 csr) (from "rv_zicsr"))
  (insn (name csrrsi) (fixed (14 12 0x6) (6 2 0x1c) (1 0 0x3)) (operands rd csr zimm5) (from "rv_zicsr"))
  (insn (name csrrw) (fixed (14 12 0x1) (6 2 0x1c) (1 0 0x3)) (operands rd rs1 csr) (from "rv_zicsr"))
  (insn (name csrrwi) (fixed (14 12 0x5) (6 2 0x1c) (1 0 0x3)) (operands rd csr zimm5) (from "rv_zicsr"))
)
