;; zifencei.sexp — a reusable definition FRAGMENT (isa-extension).
;;
;; A fragment is a complete, independently checkable description of ONE thing. It
;; lives here rather than inside a profile because a base ISA is shared by every
;; profile that composes it — copying it per profile would be the duplication the
;; composition model exists to avoid. A unit COMPOSES fragments;
;; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.
;;
;; The Zifencei extension: fence.i, the instruction-fetch synchronization instruction — ONE form (the pinned table's single row). It owns NO operand fields: imm12/rs1/rd are the base's, and the chapter's own rule is that base implementations shall IGNORE them (standard software shall zero them) — they are decoded, never legalization-rejected. funct3=1 sits beside fence's 0 inside the MISC-MEM opcode (P4-SYSTEM.6 slice a).
;;
;; Generated by `scripts/gen_fragments.py`. Do not edit by hand.

(fragment
  (id "riscv/zifencei")
  (kind isa-extension)
  (requires "riscv/rv64i")
  (source
    (file (name "rv_zifencei") (sha256 "be2d8f7286e06fadafffbde14656e6adb3f923ce704ea0829229d3a3b5f35758"))
    (origin "https://github.com/riscv/riscv-opcodes")
    (license "BSD-3-Clause"))

  ;; ---- 1 instruction(s) ----
  (insn (name fence.i) (fixed (14 12 0x1) (6 2 0x3) (1 0 0x3)) (operands imm12 rs1 rd) (from "rv_zifencei"))
)
