;; GENERATED — do not edit (OWN-03). Regenerate with `python3 scripts/gen_board.py`; drift between this document and the
;; canonical board definition is refused by the BOARD-GEN doctrine (scripts/check_board_gen.sh).
;; Canonical input: profiles/netboard-lab-v0/board.sexp (sha256 584bcc4201aafcd3c1c582718e96c2341beb3eb70aec84f8bb1951c923921854)
;; Generator: scripts/gen_board.py (sha256 4908656d81f5e31392b90ecf963ea2cdd1a4a3f2f1e0bf9966f9d1ba179f14f9)

(hardware
  (board "netboard-lab-v0")
  (version "0")
  (processor (unit "rv64i-lab-v0") (version "0") (contract "rv64i-lab-env-v0") (contract-version "0"))
  (region (name "ram0") (base "0x8000_0000") (size "0x8000_0000") (end "0x1_0000_0000") (kind ram) (executable true))
  (region (name "uart0") (base "0x1001_0000") (size "0x1000") (end "0x1001_1000") (kind mmio) (executable false) (device "uart0"))
  (region (name "eth0") (base "0x1002_0000") (size "0x100") (end "0x1002_0100") (kind mmio) (executable false) (device "eth0"))
  (wiring (device "uart0") (unit "sifive-uart-lab-v0") (kind sifive-uart) (region "uart0") (access-widths 32) (interrupt unconnected) (backend-rx recorded-input) (backend-tx host-console))
  (wiring (device "eth0") (unit "lan9118-lab-v0") (kind lan9118) (region "eth0") (access-widths 32) (interrupt unconnected) (backend-rx recorded-trace-replay) (backend-tx recording-sink))
  (serial-console (device "uart0"))
  (reset (kinds cold))
  (absence (element timers) (satisfies "OB-ENV-VIRTUAL-TIME"))
  (absence (element interrupt-controller) (satisfies "OB-ENV-EVENT-DELIVERY"))
  (disposition (decision "D-BOARD-NIC-STRAPS") (answers "OB-NIC-STRAP-RESETS") (statement "The LAN9118's configuration straps: D32/nD16 is tied HIGH — 32-bit host bus mode, the datasheet's native mode with no special requirements (DS00002266B §3.6) and the 64-bit host's natural width; EEDIO has no internal pull (Table 2-4), so the tie is an explicit board choice — and SPEED_SEL is left unwired, so its internal pull-up (Table 2-3: I (PU)) latches 1 (Table 2-2: 100 Mbps with auto-negotiation enabled). Consequences: HW_CFG reads 0x00050004 at reset; PHY register 0 bits 13/12 (Speed Select, Auto-Negotiation Enable) read 1/1; PHY register 4 (the technology advertisement) reads 0x01E1; PHY register 31's HCDSPEED default is 100BASE-TX half-duplex (010b) before negotiation completes."))
  (disposition (decision "D-BOARD-NIC-TIME-FROZEN") (answers "OB-NIC-TIME-SOURCES") (statement "The LAN9118's guest-readable time sources are frozen: FREE_RUN reads its reset value 0 forever, GPT_CNT never advances (a TIMER_EN write still loads GPT_LOAD into GPT_CNT — a guest-visible, datasheet-defined, deterministic state change — but the count never decrements, so GPT_INT never sets and the wrap never occurs), and IRQ_CFG's INT_DEAS never runs (the interrupt line is unconnected and INT_EN resets 0, so no deassertion interval ever starts; its status bits stay at reset). Constant or guest-written-static values carry no time information, so OB-ENV-VIRTUAL-TIME holds with the NIC present, and the harness's retired-instruction count never becomes target-visible through them. The deviation from wall-clock-faithful behaviour is deliberate: a polled driver never needs these counters, and a guest busy-waiting on one would hang — which is why the disposition is data, not prose."))
  (disposition (decision "D-BOARD-NIC-LINK-SCENE") (answers "OB-NIC-PHY-LINK") (statement "The recorded-trace replay's declared link scene is static and complete: the wire is up at 100BASE-TX full-duplex with auto-negotiation complete, from before the guest's first access — the board's cold reset completes before any guest access exists (D-BOARD-RESET), the same discipline that already pins READY and EPC_BSY post-transient, so every guest-observable read sees the completed scene. Concretely: PHY register 1 (Basic Status) reads 0x782D — the 0x7809 reset composition with Link Status and Auto-Negotiate Complete set; the latch-low Link bit never trips because the scene never fails; PHY register 17's ENERGYON reads 1 (already its reset); PHY register 31 reads Autodone 1 with HCDSPEED 110b (100BASE-TX full-duplex, §5.5.13); PHY register 5 (link-partner ability) reads 0x01E1, the declared partner scene. Note 3-11's wait-for-link succeeds at the first read — never a live host link."))
  (disposition (decision "D-BOARD-NIC-PIN-TIEOFFS") (answers "OB-NIC-GPIO-PINS") (statement "No GPIO, LED or EEPROM pins are wired on this board, so every pin-readable value is the declared tie-off 0: GPIO_CFG's GPIODn reads 0 regardless of direction (an input sees a tied-low pin; an output drives an unwired pin and reads back the tie-off), and the EEPR_EN-muxed internal MII monitor signals (TX_EN, RX_DV, TX_CLK, RX_CLK) read 0 — never a live host signal."))
)
