;; GENERATED — do not edit (OWN-03). Regenerate with `python3 scripts/gen_platform.py`; drift between this document and its
;; canonical inputs is refused by the PLATFORM-GEN doctrine (scripts/check_platform_gen.sh).
;; Canonical inputs:
;;   profiles/netboard-lab-v0/board.sexp (sha256 d595f2b44056913c189bb1cffd477ba3e5ccfce97e70d8f4216085130d61382a)
;;   profiles/rv64i-lab-v0/profile.sexp (sha256 63f0aa1e36fe731ef6dcabc7b63a3fe7250c84063944e47e9f4066d5d2648e3d)
;;   profiles/netboard-lab-v0/contract-obligations.sexp (sha256 a4fbbc23a7b53cbc8ed0f802e136bebc1c569e45dd73aabd1e202612d35ca514)
;; Generator: scripts/gen_platform.py (sha256 1d801a12b6715e5481235225bbeea0dc15a0f9db5928b8696654f7b1ef6ee867)

(platform
  (id "netboard-lab-v0") (version "0") (export-version "0") (status experimental)
  (processor (unit "rv64i-lab-v0") (version "0")
    (dossier-sha256 "f24ca76d93ad9dd958c7350462aeb13289e5c51d8ef72e71972ffe67b938a74e") (contract "rv64i-lab-env-v0") (contract-version "0")
    (architecture "RISC-V") (isa "rv64i") (xlen 64) (ilen 32) (ialign 32) (harts 1)
    (privilege-modes "M") (extensions) (endianness little)
    (spec (chapter-version "2.1") (revision "v20260120")))
  (memory
    (region (name "ram0") (base "0x8000_0000") (size "0x8000_0000") (end "0x1_0000_0000") (kind ram) (executable true) (presence offered))
    (region (name "uart0") (base "0x1001_0000") (size "0x1000") (end "0x1001_1000") (kind mmio) (executable false) (device "uart0") (presence offered))
    (region (name "eth0") (base "0x1002_0000") (size "0x100") (end "0x1002_0100") (kind mmio) (executable false) (device "eth0") (presence offered)))
  (device (id "uart0") (unit "sifive-uart-lab-v0") (kind sifive-uart) (material "SIFIVE-FU540-C000") (revision "v1p5") (sha256 "5fa68a677ca4bc9fc81456840834eb4fa72874a2bd72a76c33f6709f3ecab79c")
    (region "uart0") (access-widths 32) (interrupt unconnected) (backend-rx recorded-input) (backend-tx host-console) (presence offered))
  (device (id "eth0") (unit "lan9118-lab-v0") (kind lan9118) (material "MICROCHIP-LAN9118") (revision "DS00002266B 2018-11-30") (sha256 "72fe68f241b5bc91a861cff98a877ae907339d396e64394b0f5daa2c391bf6ee")
    (region "eth0") (access-widths 32) (interrupt unconnected) (backend-rx recorded-trace-replay) (backend-tx recording-sink) (presence offered))
  (absence (element timers) (presence absent-by-contract) (satisfies "OB-ENV-VIRTUAL-TIME"))
  (absence (element interrupt-controller) (presence absent-by-contract) (satisfies "OB-ENV-EVENT-DELIVERY"))
  (disposition (decision "D-BOARD-NIC-STRAPS") (answers "OB-NIC-STRAP-RESETS") (statement "The LAN9118's configuration straps: D32/nD16 is tied HIGH — 32-bit host bus mode, the datasheet's native mode with no special requirements (DS00002266B §3.6) and the 64-bit host's natural width; EEDIO has no internal pull (Table 2-4), so the tie is an explicit board choice — and SPEED_SEL is left unwired, so its internal pull-up (Table 2-3: I (PU)) latches 1 (Table 2-2: 100 Mbps with auto-negotiation enabled). Consequences: HW_CFG reads 0x00050004 at reset; PHY register 0 bits 13/12 (Speed Select, Auto-Negotiation Enable) read 1/1; PHY register 4 (the technology advertisement) reads 0x01E1; PHY register 31's HCDSPEED default is 100BASE-TX half-duplex (010b) before negotiation completes."))
  (disposition (decision "D-BOARD-NIC-TIME-FROZEN") (answers "OB-NIC-TIME-SOURCES") (statement "The LAN9118's guest-readable time sources are frozen: FREE_RUN reads its reset value 0 forever, GPT_CNT never advances (a TIMER_EN write still loads GPT_LOAD into GPT_CNT — a guest-visible, datasheet-defined, deterministic state change — but the count never decrements, so GPT_INT never sets and the wrap never occurs), and IRQ_CFG's INT_DEAS never runs (the interrupt line is unconnected and INT_EN resets 0, so no deassertion interval ever starts; its status bits stay at reset). Constant or guest-written-static values carry no time information, so OB-ENV-VIRTUAL-TIME holds with the NIC present, and the harness's retired-instruction count never becomes target-visible through them. The deviation from wall-clock-faithful behaviour is deliberate: a polled driver never needs these counters, and a guest busy-waiting on one would hang — which is why the disposition is data, not prose."))
  (disposition (decision "D-BOARD-NIC-LINK-SCENE") (answers "OB-NIC-PHY-LINK") (statement "The recorded-trace replay's declared link scene is static and complete: the wire is up at 100BASE-TX full-duplex with auto-negotiation complete, from before the guest's first access — the board's cold reset completes before any guest access exists (D-BOARD-RESET), the same discipline that already pins READY and EPC_BSY post-transient, so every guest-observable read sees the completed scene. Concretely: PHY register 1 (Basic Status) reads 0x782D — the 0x7809 reset composition with Link Status and Auto-Negotiate Complete set; the latch-low Link bit never trips because the scene never fails; PHY register 17's ENERGYON reads 1 (already its reset); PHY register 31 reads Autodone 1 with HCDSPEED 110b (100BASE-TX full-duplex, §5.5.13); PHY register 5 (link-partner ability) reads 0x01E1, the declared partner scene. Note 3-11's wait-for-link succeeds at the first read — never a live host link."))
  (disposition (decision "D-BOARD-NIC-PIN-TIEOFFS") (answers "OB-NIC-GPIO-PINS") (statement "No GPIO, LED or EEPROM pins are wired on this board, so every pin-readable value is the declared tie-off 0: GPIO_CFG's GPIODn reads 0 regardless of direction (an input sees a tied-low pin; an output drives an unwired pin and reads back the tie-off), and the EEPR_EN-muxed internal MII monitor signals (TX_EN, RX_DV, TX_CLK, RX_CLK) read 0 — never a live host signal."))
  (boot (image-format elf64) (load-region "ram0") (entry image-entry) (register-state zeroed-x1-x31)
    (argument-convention none) (firmware-services none) (abi freestanding) (hardware-description hardware-sexp-internal) (presence offered))
  (time (time-source none) (frozen-counter-disposition "D-BOARD-NIC-TIME-FROZEN") (timing-fidelity functional-only) (presence absent-by-contract))
  (events (synchronous-exceptions yes) (requested-traps yes) (asynchronous-interrupts no) (interrupt-controller none) (presence limited))
  (ordering (harts 1) (execution sequential-in-order) (memory-model-claim none) (scheduling-policies none))
  (test-control (console-capture host-console) (completion typed-outcome-stop) (reset cold-reload) (input-injection recorded-backends)
    (execution-budget step-budget) (trace-selection step-and-store) (snapshots snapshot-resume) (presence offered))
  (limitations
    (limitation "EXPERIMENTAL: the platform inherits its processor's status (rv64i-lab-v0 v0); every claim is conditional on the CPU's acceptance trajectory — the composition can never outrank its processor")
    (limitation "timers absent by contract (OB-ENV-VIRTUAL-TIME); no such facility exists for a guest")
    (limitation "interrupt controller absent by contract (OB-ENV-EVENT-DELIVERY); no such facility exists for a guest")
    (limitation "drivers poll: no asynchronous event is deliverable, so nothing wakes a waiting guest")
    (limitation "MMIO accesses honour exactly the declared widths (32-bit on this board); any other width is a board-reported contract violation, never silently serviced")
    (limitation "no firmware services and no environment ABI: ECALL/EBREAK are typed requested-trap outcomes reported to the harness")
    (limitation "guest-readable device counters are frozen (D-BOARD-NIC-TIME-FROZEN): constant values carry no time information — a guest busy-waiting on one hangs; poll for data, never for time"))
  (non-claims
    (non-claim "a compatible manifest proves neither that an OS is correct nor that this manifest matches the implementation (docs/ARCHOGEN_INTEGRATION.md §3)")
    (non-claim "no archogen eADL interface exists today — archogen is actively developed; this export is validated by derivation freshness, schema conformance and ARCHOGEN_INTEGRATION §3 coverage, never by archogen acceptance")
    (non-claim "test-control capabilities are the platform package's declaration, evidenced by the runner's own suites — not by this document"))
)
