;; contract-obligations.sexp — the device contract for `lan9118-lab-v0` (P5-BOARD.10,
;; 2026-10-02). One (obligation …) per record. Validate:
;;   python3 scripts/check_sexp_schema.py profiles/lan9118-lab-v0/contract-obligations.sexp schema/contract-obligations.sexp
;; The contract id is `lan9118-v0` v0. Every obligation is a DEVICE GUARANTEE
;; (direction device-guarantee — P5-BOARD.2's third direction): what the datasheet lets a
;; composing board rely on, or — for the records whose source_semantics is not `defined` —
;; what it forbids the board from relying on. Each mirrors its requirement's statement
;; EXACTLY (RECORD-SCHEMA rule 9); the board definition's `satisfies` fields and
;; P5-BOARD.4's discharge verdict name these ids. Authorities: `architecture` for the
;; datasheet's own statements (RECORD-SCHEMA's authority-downgrade rule forces it for
;; `defined`), `laboratory` for the three composition dispositions (TIME-SOURCES,
;; PHY-LINK, GPIO-PINS) whose content is this board's deterministic discipline.
;; `P5-BOARD.4`: the four records the dossier defers to the composing board —
;; STRAP-RESETS (the strap values, `architecture`: the datasheet defines THAT straps
;; determine them), TIME-SOURCES, PHY-LINK, GPIO-PINS — carry the marker param
;; (composition_disposition "required"); the BOARD-VERDICT doctrine refuses a board
;; whose definition does not answer each of them with exactly one decision `answers` edge.

(obligation (id "OB-NIC-MAP") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The LAN9118 direct host-bus register map spans offsets 00h–FCh: the RX data FIFO port aliased at 00h–1Ch, the TX data FIFO port aliased at 20h–3Ch, the RX status FIFO port at 40h with its PEEK at 44h, the TX status FIFO port at 48h with its PEEK at 4Ch, twenty-four named control and status registers at 50h–B4h, and RESERVED slots at 60h, 94h and B8h–FCh; the board's 256-byte eth0 window spans exactly this map.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5, Figure 5-1, Table 5-1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-MAP"))) (param (name decision_id) (value (str "D-NIC-MAP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-MAP") (required_checks "CHK-NIC-MAP-POS") (required_checks "CHK-NIC-MAP-NEG"))

(obligation (id "OB-NIC-HBI") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The host bus interface is an SRAM-like asynchronous slave supporting programmed I/O transactions only — 32-bit and 16-bit bus transfers over internally 32-bit data paths, with no bus-master DMA. In 16-bit mode each DWORD transfer is two contiguous 16-bit accesses that begin and end on a DWORD address boundary, in either word order; a repeated access to the same word is disregarded on writes and reads back invalid (to be re-read) on reads.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§1.10, §3.6, §3.6.1, §3.6.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-HBI"))) (param (name decision_id) (value (str "D-NIC-HBI"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-HBI") (required_checks "CHK-NIC-HBI-POS") (required_checks "CHK-NIC-HBI-NEG"))

(obligation (id "OB-NIC-RXDATA-PORT") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The RX data FIFO allows destructive reads only: every read pops the head DWORD. Its port is aliased in 8 DWORD locations (16 WORD locations in 16-bit mode) from offset 00h to 1Ch; the host may access any of the aliased locations since they all contain the same data and perform the same function.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.2.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RXDATA-PORT"))) (param (name decision_id) (value (str "D-NIC-RXDATA-PORT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RXDATA-PORT") (required_checks "CHK-NIC-RXDATA-PORT-POS") (required_checks "CHK-NIC-RXDATA-PORT-NEG"))

(obligation (id "OB-NIC-TXDATA-PORT") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The TX data FIFO port is write-only, aliased in 8 DWORD locations (16 WORD locations in 16-bit mode) from offset 20h to 3Ch; the host may write to any of the aliased locations since they all access the same TX data FIFO location and perform the same function. Per the WO access attribute, reads of the port always return 0.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.2.2, §5.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TXDATA-PORT"))) (param (name decision_id) (value (str "D-NIC-TXDATA-PORT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TXDATA-PORT") (required_checks "CHK-NIC-TXDATA-PORT-POS") (required_checks "CHK-NIC-TXDATA-PORT-NEG"))

(obligation (id "OB-NIC-STATUS-PORTS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The RX and TX status FIFOs are each readable from two locations: the status FIFO port (RX at 40h, TX at 48h) performs a destructive read, popping the FIFO; the PEEK location (RX at 44h, TX at 4Ch) performs a non-destructive read of the top (oldest) location of the FIFO.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.2.1, §5.2.2, Figure 5-1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-STATUS-PORTS"))) (param (name decision_id) (value (str "D-NIC-STATUS-PORTS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-STATUS-PORTS") (required_checks "CHK-NIC-STATUS-PORTS-POS") (required_checks "CHK-NIC-STATUS-PORTS-NEG"))

(obligation (id "OB-NIC-FIFO-SIZES") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The RX and TX data FIFOs and the RX status FIFO are configurable through HW_CFG's TX_FIF_SZ field out of a 16 KB SRAM: the TX status FIFO is fixed at 512 bytes (128 DWORDs) inside the TX allocation, the RX FIFO is the remainder (16384 minus the TX allocation), and the RX status FIFO is always 1/16 of the RX FIFO size, the rest being RX data. The valid TX_FIF_SZ settings are 2 through 14 (Table 5-3 — others are reserved), the default is 5 (TX data 4608 B, TX status 512 B, RX data 10560 B, RX status 704 B), TX data FIFO space includes both commands and payload, and the RX data FIFO is considered full 4 DWORDs before its configured length. The MIL adds a fixed 2 KB TX and 128 B RX FIFO, not visible to the host processor.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.2, §5.3.9, §5.3.9.1, Table 5-3")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FIFO-SIZES"))) (param (name decision_id) (value (str "D-NIC-FIFO-SIZES"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FIFO-SIZES") (required_checks "CHK-NIC-FIFO-SIZES-POS") (required_checks "CHK-NIC-FIFO-SIZES-NEG"))

(obligation (id "OB-NIC-ID-REV") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "ID_REV (offset 50h) is read-only: Chip ID 0118h in bits [31:16] and Chip Revision 0001h in bits [15:0] — the register reads 01180001h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-ID-REV"))) (param (name decision_id) (value (str "D-NIC-ID-REV"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-ID-REV") (required_checks "CHK-NIC-ID-REV-POS") (required_checks "CHK-NIC-ID-REV-NEG"))

(obligation (id "OB-NIC-BYTE-TEST") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "BYTE_TEST (offset 64h) is a read-only byte-order test register reading 87654321h. A write of any data to BYTE_TEST while the LAN9118 is in a power-saving state (D1 or D2) returns it to the D0 state and resets PM_MODE to D0; as a read-only register, writes have no effect on its read value.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.5, §3.10.2 (Notes 3-4/3-5), §5.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-BYTE-TEST"))) (param (name decision_id) (value (str "D-NIC-BYTE-TEST"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-BYTE-TEST") (required_checks "CHK-NIC-BYTE-TEST-POS") (required_checks "CHK-NIC-BYTE-TEST-NEG"))

(obligation (id "OB-NIC-IRQ-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "IRQ_CFG (offset 54h) configures and indicates the state of the IRQ signal: INT_DEAS (bits 31:24) sets an interrupt deassertion interval in multiples of 10 µs — writing zeros disables the interval, resets the interval counter and issues any pending interrupts; INT_DEAS_CLR (bit 14, SC) restarts the deassertion interval; INT_DEAS_STS (bit 13, RO) reports an active interval during which interrupts are not delivered to the IRQ pin; IRQ_INT (bit 12, RO) reports the internal IRQ line state, responding to the associated interrupts regardless of IRQ_EN and unaffected by INT_DEAS; IRQ_EN (bit 8) gates only the external IRQ signal and has no effect on any internal interrupt status bits; IRQ_POL (bit 4) selects the polarity and IRQ_TYPE (bit 0) the buffer type, both NASR. The deassertion interval does not apply to the PME interrupt. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-IRQ-CFG"))) (param (name decision_id) (value (str "D-NIC-IRQ-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-IRQ-CFG") (required_checks "CHK-NIC-IRQ-CFG-POS") (required_checks "CHK-NIC-IRQ-CFG-NEG"))

(obligation (id "OB-NIC-INT-STS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "INT_STS (offset 58h) contains the current status of the generated interrupts — SW_INT (31), TXSTOP_INT (25), RXSTOP_INT (24), RXDFH_INT (23), TX_IOC (21), RXD_INT (20), GPT_INT (19), PHY_INT (18, read-only), PME_INT (17), TXSO (16), RWT (15), RXE (14), TXE (13), TDFO (10), TDFA (9), TSFF (8), TSFL (7), RXDF_INT (6), RSFF (4), RSFL (3) and GPIO2–GPIO0 (2:0) — as R/WC bits: writing a 1 acknowledges and clears the bit and writing a 0 has no effect. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.3")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-INT-STS"))) (param (name decision_id) (value (str "D-NIC-INT-STS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-INT-STS") (required_checks "CHK-NIC-INT-STS-POS") (required_checks "CHK-NIC-INT-STS-NEG"))

(obligation (id "OB-NIC-INT-EN") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "INT_EN (offset 5Ch) contains the interrupt masks for IRQ, one per INT_STS source at the same bit position: writing 1 enables the corresponding interrupt as a source for IRQ, and INT_STS bits still reflect the status of the interrupt source regardless of whether the source is enabled. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.4")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-INT-EN"))) (param (name decision_id) (value (str "D-NIC-INT-EN"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-INT-EN") (required_checks "CHK-NIC-INT-EN-POS") (required_checks "CHK-NIC-INT-EN-NEG"))

(obligation (id "OB-NIC-FIFO-INT") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "FIFO_INT (offset 68h) configures the limits where the FIFO controllers generate system interrupts: TX Data Available Level (bits 31:24, in 64-byte blocks — TDFA is generated when TX data FIFO free space is greater than this value), TX Status Level (bits 23:16, in DWORDs — TSFL when TX status FIFO used space is greater), and RX Status Level (bits 7:0, in DWORDs — RSFL when RX status FIFO used space is greater). Reset value 48000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.6")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FIFO-INT"))) (param (name decision_id) (value (str "D-NIC-FIFO-INT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FIFO-INT") (required_checks "CHK-NIC-FIFO-INT-POS") (required_checks "CHK-NIC-FIFO-INT-NEG"))

(obligation (id "OB-NIC-RX-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "RX_CFG (offset 6Ch) controls the receive engine: RX End Alignment (bits 31:30) selects a 4-, 16- or 32-byte end alignment the LAN9118 pads the last transfer up to, the host removing the extra DWORDs (11b is reserved); RX_DMA_CNT (bits 27:16) counts down the DWORDs to transfer out of the RX data FIFO before RXD_INT asserts, overwritable before it reaches zero; RX_DUMP (bit 15, SC) clears the RX data and status FIFOs of all pending data — the receiver must be halted and the stop confirmed before a dump; RXDOFF (bits 12:8) shifts the start of valid RX data by 0–31 bytes, its two LSBs changeable only with the receiver halted and all data purged. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.7, Table 5-2, §3.13.1.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RX-CFG"))) (param (name decision_id) (value (str "D-NIC-RX-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RX-CFG") (required_checks "CHK-NIC-RX-CFG-POS") (required_checks "CHK-NIC-RX-CFG-NEG"))

(obligation (id "OB-NIC-TX-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "TX_CFG (offset 70h) controls the transmit functions: TXS_DUMP (bit 15, SC) clears the TX status FIFO of all pending status DWORDs and TXD_DUMP (bit 14, SC) clears the TX data FIFO of all pending data; TXSAO (bit 2) allows the transmitter to continue operation with a full TX status FIFO when set, and suspends transmission on a full TX status FIFO when clear; TX_ON (bit 1) enables the transmitter — any data in the TX FIFO will be sent — and is cleared automatically when STOP_TX is set and the transmitter has halted; STOP_TX (bit 0, SC) finishes the current frame and then stops the transmitter, clearing itself when stopped, with all writes to it ignored while high. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.8, §3.12.8")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TX-CFG"))) (param (name decision_id) (value (str "D-NIC-TX-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TX-CFG") (required_checks "CHK-NIC-TX-CFG-POS") (required_checks "CHK-NIC-TX-CFG-NEG"))

(obligation (id "OB-NIC-HW-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "HW_CFG (offset 74h) controls the hardware configuration and must be written only with the transmitter and receiver stopped: MBO (bit 20) must be set to 1 for normal device operation; TX_FIF_SZ (bits 19:16) selects the TX FIFO allocation in 1 KB units (valid settings 2–14); bit 2 (RO) reports the D32/nD16 strap — set for 32-bit operation, clear for 16-bit; SRST_TO (bit 1, RO) reports that a soft reset timed out because the internal PHY was not operational; SRST (bit 0, SC) generates a software-initiated reset — a full reset of the MAC CSRs, the SCSRs except NASR bits, and the TXE/RXE errors — which will time out if the internal PHY is not in the operational state. Reset value 00050000h, with bit 2 carrying the strap value.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.9, §5.3.9.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-HW-CFG"))) (param (name decision_id) (value (str "D-NIC-HW-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-HW-CFG") (required_checks "CHK-NIC-HW-CFG-POS") (required_checks "CHK-NIC-HW-CFG-NEG"))

(obligation (id "OB-NIC-RX-DP-CTRL") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "RX_DP_CTL (offset 78h) bit 31 (RX_FFWD) fast-forwards the RX data FIFO to the start of the next frame: the bit remains high until the fast-forward completes, no reads may be issued to the RX data FIFO while it is high (other registers and the other three FIFOs remain accessible), the discarded packet must occupy at least 4 DWORDs — shorter packets are read out and discarded with standard PIO reads — and the RX status FIFO is not fast-forwarded. The receiver does not have to be stopped to fast-forward. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.10, §3.13.1.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RX-DP-CTRL"))) (param (name decision_id) (value (str "D-NIC-RX-DP-CTRL"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RX-DP-CTRL") (required_checks "CHK-NIC-RX-DP-CTRL-POS") (required_checks "CHK-NIC-RX-DP-CTRL-NEG"))

(obligation (id "OB-NIC-FIFO-INF") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "RX_FIFO_INF (offset 7Ch, RO) reports RXSUSED (bits 23:16, RX status FIFO used space in DWORDs) and RXDUSED (bits 15:0, RX data FIFO used space in bytes, each receive frame counted with its length rounded up to the nearest DWORD); TX_FIFO_INF (offset 80h, RO) reports TXSUSED (bits 23:16, TX status FIFO used space in DWORDs) and TDFREE (bits 15:0, TX data FIFO free space in bytes) — the application should never write more data than TDFREE reports available. Reset values 00000000h and 00001200h: the INF counters' resets pin every FIFO empty at reset (TDFREE = 4608 is the default allocation's whole TX data FIFO).") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.11, §5.3.12")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FIFO-INF"))) (param (name decision_id) (value (str "D-NIC-FIFO-INF"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FIFO-INF") (required_checks "CHK-NIC-FIFO-INF-POS") (required_checks "CHK-NIC-FIFO-INF-NEG"))

(obligation (id "OB-NIC-PMT-CTRL") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "PMT_CTRL (offset 84h) controls the power management features and is readable in every power management mode: READY (bit 0, RO) indicates the LAN9118 is stabilized and fully alive — with the exception of HW_CFG and PMT_CTRL, read access to any internal resource is forbidden while READY is clear, and all writes except the wake-up write to BYTE_TEST are forbidden until READY sets; PM_MODE (bits 13:12) selects D0 normal operation, D1 (wake-up frame and magic packet detection enabled) or D2 (energy detect), 11b reserved; PHY_RST (bit 10, SC) resets the PHY with the internal logic holding the reset for a minimum of 100 µs, writes ignored while high; WOL_EN (9) and ED_EN (8) enable the wake-on-LAN and energy-detect events; PME_TYPE (6) and PME_POL (2) are NASR; WUPS (bits 5:4, R/WC) reports the wake-up cause and clears only in D0 with all event sources cleared; PME_IND (3) selects a 50 ms pulsed versus continuous PME signal; PME_EN (1) enables the external PME signal only. Reset value 00000000h, with READY reading 0 until the reset or power-up completes.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.13, §3.10.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PMT-CTRL"))) (param (name decision_id) (value (str "D-NIC-PMT-CTRL"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-PMT-CTRL") (required_checks "CHK-NIC-PMT-CTRL-POS") (required_checks "CHK-NIC-PMT-CTRL-NEG"))

(obligation (id "OB-NIC-FIRST-READ") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The LAN9118 must always be read at least once after power-up, reset, or upon return from a power-saving state, otherwise write operations will not function.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.10.2 Note 3-4; §5.3.9 note; §5.3.13 note")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FIRST-READ"))) (param (name decision_id) (value (str "D-NIC-FIRST-READ"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FIRST-READ") (required_checks "CHK-NIC-FIRST-READ-POS") (required_checks "CHK-NIC-FIRST-READ-NEG"))

(obligation (id "OB-NIC-GPIO-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "GPIO_CFG (offset 88h) configures the GPIO and LED functions: LEDx_EN (bits 30:28) set the associated pin as an LED output versus a GPIO signal; GPIO_INT_POL (bits 26:24) select whether a high or low level on the corresponding GPIO pin sets the GPIOx_INT status bit, the input active for greater than 40 ns to be recognized; EEPR_EN (bits 22:20) mux the EEDIO and EECLK pins between EEPROM, GPO3/GPO4 and internal MII signal functions (Table 5-4) and must not change while an EEPROM read or write cycle is in progress; GPIOBUFn (bits 18:16) select push/pull versus open-drain; GPDIRn (bits 10:8) select output versus input; GPODn (bits 4:3) carry the GPO3/GPO4 output values and GPIODn (bits 2:0) the GPIO0–2 values, reads of which reflect the current state of the corresponding pin. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.14, Table 5-4")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-GPIO-CFG"))) (param (name decision_id) (value (str "D-NIC-GPIO-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-GPIO-CFG") (required_checks "CHK-NIC-GPIO-CFG-POS") (required_checks "CHK-NIC-GPIO-CFG-NEG"))

(obligation (id "OB-NIC-GPT") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "GPT_CFG (offset 8Ch) holds TIMER_EN (bit 29) and the 16-bit GPT_LOAD pre-load (bits 15:0); GPT_CNT (offset 90h, RO) reflects the current value of the GP timer. The GP timer's resolution is 100 µs: writing TIMER_EN 1 loads GPT_LOAD into GPT_CNT and counts down; at 0000h the counter wraps to FFFFh, sets the GPT_INT status bit — a sticky R/WC bit — and asserts IRQ if GPT_INT_EN is set, and continues counting; on a reset, or on the TIMER_EN 1-to-0 transition, GPT_LOAD presets to FFFFh and GPT_CNT initializes to FFFFh. Reset values 0000FFFFh for both registers.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.15, §5.3.16, §3.8")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-GPT"))) (param (name decision_id) (value (str "D-NIC-GPT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-GPT") (required_checks "CHK-NIC-GPT-POS") (required_checks "CHK-NIC-GPT-NEG"))

(obligation (id "OB-NIC-FREE-RUN") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "FREE_RUN (offset 9Ch, RO) reflects the value of a free-running 32-bit counter clocked by the 25 MHz reference: at reset the counter starts at zero and increments every 25 MHz cycle, rolls over at the maximum count, runs regardless of the power management states D0, D1 or D2, can take up to 160 ns to clear after a reset event, and in 16-bit mode latches the count value on the first read.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.18")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FREE-RUN"))) (param (name decision_id) (value (str "D-NIC-FREE-RUN"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FREE-RUN") (required_checks "CHK-NIC-FREE-RUN-POS") (required_checks "CHK-NIC-FREE-RUN-NEG"))

(obligation (id "OB-NIC-WORD-SWAP") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "WORD_SWAP (offset 98h, R/W, NASR) controls how words from the host data bus map to the CSRs and data FIFOs, significant only in 16-bit mode: any value other than FFFFFFFFh maps words with address bit A[1]=1 to the high order words and A[1]=0 to the low order words, and FFFFFFFFh reverses the mapping; in 32-bit mode D[31:16] always maps to the high order word and D[15:0] to the low order word. The LAN9118 always sends the low order word of the TX data FIFO to the network first and receives the low order word first. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.17, §3.7, Table 3-7")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-WORD-SWAP"))) (param (name decision_id) (value (str "D-NIC-WORD-SWAP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-WORD-SWAP") (required_checks "CHK-NIC-WORD-SWAP-POS") (required_checks "CHK-NIC-WORD-SWAP-NEG"))

(obligation (id "OB-NIC-RX-DROP") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "RX_DROP (offset A0h) indicates the number of receive frames dropped: RX_DFC increments every time a receive frame is dropped, is cleared on any read of the register (RC), and issues the RXDFH_INT interrupt when the counter passes through its halfway point (7FFFFFFFh to 80000000h). Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.19")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RX-DROP"))) (param (name decision_id) (value (str "D-NIC-RX-DROP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RX-DROP") (required_checks "CHK-NIC-RX-DROP-POS") (required_checks "CHK-NIC-RX-DROP-NEG"))

(obligation (id "OB-NIC-MAC-SYNC") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The MAC CSRs are accessed indirectly through MAC_CSR_CMD (offset A4h) and MAC_CSR_DATA (offset A8h): writing CSR Busy (bit 31) with R/nW (bit 30) selecting read versus write and the 8-bit CSR Address (bits 7:0) performs the operation on the selected MAC CSR; Busy remains set until the operation is complete — on a read, valid data is then in MAC_CSR_DATA — and MAC_CSR_CMD and MAC_CSR_DATA must not be modified until Busy clears. Reset value 00000000h for both registers.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.20, §5.3.21")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-MAC-SYNC"))) (param (name decision_id) (value (str "D-NIC-MAC-SYNC"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-MAC-SYNC") (required_checks "CHK-NIC-MAC-SYNC-POS") (required_checks "CHK-NIC-MAC-SYNC-NEG"))

(obligation (id "OB-NIC-AFC-CFG") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "AFC_CFG (offset ACh) configures the mechanism controlling automatic and software-initiated transmission of pause frames and back pressure: AFC_HI (bits 23:16, multiples of 64 bytes) is the RX data FIFO level that triggers flow control; AFC_LO (bits 15:8, multiples of 64 bytes) is the level at which a zero-pause-time frame is sent after a pause — when automatic flow control is enabled AFC_LO must always be less than AFC_HI; BACK_DUR (bits 7:4) sets the back-pressure duration per Table 5-5; FCMULT, FCBRD, FCADD and FCANY (bits 3:0) select the received frame classes that trigger back pressure or a pause frame, FCANY overriding bits 3:1. The LAN9118 will not transmit pause frames or assert back pressure if the transmitter is disabled. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.22, Table 5-5")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-AFC-CFG"))) (param (name decision_id) (value (str "D-NIC-AFC-CFG"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-AFC-CFG") (required_checks "CHK-NIC-AFC-CFG-POS") (required_checks "CHK-NIC-AFC-CFG-NEG"))

(obligation (id "OB-NIC-E2P") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "E2P_CMD (offset B0h) and E2P_DATA (offset B4h) control the serial EEPROM: setting EPC Busy (bit 31) executes the EPC command field (bits 30:28 — READ, EWDS, EWEN, WRITE, WRAL, ERASE, ERAL, RELOAD) at the byte-aligned EPC Address (bits 7:0); Busy remains set until the operation completes — read data is then valid in E2P_DATA (bits 7:0) — and neither register may be modified until it clears; EPC Time-out (bit 9, R/WC) sets when an operation has no EEPROM response within 30 ms; MAC Address Loaded (bit 8, RO) reports a successful MAC address load after power-up or a RELOAD. EPC Busy reads high immediately following power-up or reset until the EEPROM controller finishes reading or attempting to read the MAC address. The EEPROM device powers up in the erase/write-disabled state. Reset value 00000000h (E2P_DATA 00h in its data byte).") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.23, §5.3.24, §3.9.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-E2P"))) (param (name decision_id) (value (str "D-NIC-E2P"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-E2P") (required_checks "CHK-NIC-E2P-POS") (required_checks "CHK-NIC-E2P-NEG"))

(obligation (id "OB-NIC-EEPROM-AUTOLOAD") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "On power-up, hard reset or soft reset the EEPROM controller attempts to read the first EEPROM byte (address 00h): if A5h is read, an external serial EEPROM is assumed present and the next six bytes program the 48-bit MAC address (EEPROM 01h→ADDRL[7:0], 02h→ADDRL[15:8], 03h→ADDRL[23:16], 04h→ADDRL[31:24], 05h→ADDRH[7:0], 06h→ADDRH[15:8] — the order of reception on Ethernet), then MAC Address Loaded sets; if A5h is not read, the controller ends initialization and programming ADDRL/ADDRH is the host LAN driver's responsibility. After a POR, nRESET or SRST the application must verify EPC Busy has cleared before accessing the EEPROM, changing the GPIO/EEPROM pin functions, or modifying ADDRH/ADDRL.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.9.1, Table 5-7, §3.11 Note 3-12")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-EEPROM-AUTOLOAD"))) (param (name decision_id) (value (str "D-NIC-EEPROM-AUTOLOAD"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-EEPROM-AUTOLOAD") (required_checks "CHK-NIC-EEPROM-AUTOLOAD-POS") (required_checks "CHK-NIC-EEPROM-AUTOLOAD-NEG"))

(obligation (id "OB-NIC-MAC-CR") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "MAC_CR (MAC CSR index 1) establishes the RX and TX operation modes and the address and packet filtering: RXALL (31), RCVOWN (23 — disable reception of frames when MII TX_EN is asserted; reset when full duplex), LOOPBK (21 — internal loopback through the MII, up to 10 s to change with transmitter and receiver stopped and disabled), FDPX (20 — full duplex, heartbeat check disabled), MCPAS (19), PRMS (18), INVFILT (17 — perfect filtering only), PASSBAD (16 — runts and collided frames included), HO (15 — imperfect hash filtering for physical and multicast), HPFILT (13 — hash versus perfect multicast filtering), LCOLL (12), BCAST (11 — disable broadcast reception), DISRTY (10 — one attempt versus 16), PADSTR (8 — strip pad and FCS when the length field is under 46 bytes), BOLMT (7:6 — back-off limit), DFCHK (5 — abort after deferring over 24288 bit times), TXEN (3) and RXEN (2). Reset value 00040000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-MAC-CR"))) (param (name decision_id) (value (str "D-NIC-MAC-CR"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-MAC-CR") (required_checks "CHK-NIC-MAC-CR-POS") (required_checks "CHK-NIC-MAC-CR-NEG"))

(obligation (id "OB-NIC-MAC-ADDR") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "ADDRH (MAC CSR index 2) and ADDRL (index 3) hold the 48-bit physical address — ADDRH bits 15:0 are address bits 47:32, ADDRL bits 31:0 — optionally loaded from the EEPROM at power-on and writable by the host after the initialization process has completed; the content is undefined until loaded from the EEPROM, with Table 5-6 listing defaults 0000FFFFh and FFFFFFFFh.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.2, §5.4.3, Table 5-6, Table 5-7")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-MAC-ADDR"))) (param (name decision_id) (value (str "D-NIC-MAC-ADDR"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-MAC-ADDR") (required_checks "CHK-NIC-MAC-ADDR-POS") (required_checks "CHK-NIC-MAC-ADDR-NEG"))

(obligation (id "OB-NIC-HASH") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "HASHH (MAC CSR index 4) and HASHL (index 5) form the 64-bit multicast hash table used for group address filtering: a hash of the incoming frame's destination address indexes the table — the most significant hash bit selects the high or low register and the other five bits select the bit within the register — and a 1 accepts the multicast frame; if MCPAS is set, all multicast frames are accepted regardless of the hash values. Reset value 00000000h for both.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.4, §5.4.5")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-HASH"))) (param (name decision_id) (value (str "D-NIC-HASH"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-HASH") (required_checks "CHK-NIC-HASH-POS") (required_checks "CHK-NIC-HASH-NEG"))

(obligation (id "OB-NIC-MII") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "MII_ACC (MAC CSR index 6) and MII_DATA (index 7) run management cycles to the PHY: the PHY Address field (bits 15:11) must be set to 00001b for every access, MIIRINDA (bits 10:6) selects the PHY register, MIIWnR (bit 1) selects a write versus a read, and MIIBZY (bit 0) starts the access and must be polled to 0 before the registers are written again — MII_DATA must be kept valid until the MAC clears MIIBZY on a write and is invalid until MIIBZY clears on a read. Reset value 00000000h for both.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.6, §5.4.7")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-MII"))) (param (name decision_id) (value (str "D-NIC-MII"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-MII") (required_checks "CHK-NIC-MII-POS") (required_checks "CHK-NIC-MII-NEG"))

(obligation (id "OB-NIC-FLOW") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "FLOW (MAC CSR index 8) controls the generation and reception of control (pause command) frames: FCPT (bits 31:16) is the value used in the PAUSE TIME field of a transmitted control frame and must be initialized before full-duplex automatic flow control is enabled; FCPASS (bit 2) sets the Packet Filter bit in the receive packet status for a valid received pause frame; FCEN (bit 1) enables the receive portion of the flow control block — pause decoding in full duplex, the backpressure function in half duplex; FCBSY (bit 0) indicates a pause frame or back pressure is being transmitted, must read 0 before the register is written, and applications always write it 0. Reset value 00000000h.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.8")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-FLOW"))) (param (name decision_id) (value (str "D-NIC-FLOW"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-FLOW") (required_checks "CHK-NIC-FLOW-POS") (required_checks "CHK-NIC-FLOW-NEG"))

(obligation (id "OB-NIC-VLAN") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "VLAN1 (MAC CSR index 9) and VLAN2 (index A) hold the VLAN tag identifiers compared with the 13th and 14th bytes of incoming frames for VLAN1/VLAN2 detection — set to 8100h if used — and for VLAN frames the legal frame length is increased from 1518 to 1522 bytes. Reset value 00000000h for both.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.9, §5.4.10")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-VLAN"))) (param (name decision_id) (value (str "D-NIC-VLAN"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-VLAN") (required_checks "CHK-NIC-VLAN-POS") (required_checks "CHK-NIC-VLAN-NEG"))

(obligation (id "OB-NIC-WAKE") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "WUFF (MAC CSR index B) is write-only and configures the wake-up frame filter through an internal pointer: after power-on reset, hardware reset or soft reset, the MAC loads the first value written to the first filter DWORD (filter 0 byte mask), the second to the second DWORD, and so on through all eight, after which the internal pointer wraps to the first entry. WUCSR (index C) carries GUE (bit 9 — wake on a global unicast frame), WUFR (bit 6 — a valid remote wake-up frame was received), MPR (bit 5 — a valid Magic Packet was received), WUEN (bit 2 — wake-up frame detection enabled) and MPEN (bit 1 — Magic Packet wake-up enabled). Reset value 00000000h (WUCSR).") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.4.11, §5.4.12")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-WAKE"))) (param (name decision_id) (value (str "D-NIC-WAKE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-WAKE") (required_checks "CHK-NIC-WAKE-POS") (required_checks "CHK-NIC-WAKE-NEG"))

(obligation (id "OB-NIC-PHY-MAP") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The PHY registers are not memory mapped: they are 16-bit registers accessed indirectly through the MAC's MII_ACC and MII_DATA registers at PHY address 00001b — index 0 Basic Control, 1 Basic Status, 2 PHY Identifier 1, 3 PHY Identifier 2, 4 Auto-Negotiation Advertisement, 5 Auto-Negotiation Link Partner Ability, 6 Auto-Negotiation Expansion, 17 Mode Control/Status, 18 Special Modes, 27 Special Control/Status Indications, 29 Interrupt Source, 30 Interrupt Mask and 31 PHY Special Control/Status.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.5, Table 5-8")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PHY-MAP"))) (param (name decision_id) (value (str "D-NIC-PHY-MAP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-PHY-MAP") (required_checks "CHK-NIC-PHY-MAP-POS") (required_checks "CHK-NIC-PHY-MAP-NEG"))

(obligation (id "OB-NIC-PHY-ID") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "PHY Identifier 1 (index 2) reads 0007h — the 3rd through 18th bits of the OUI; PHY Identifier 2 (index 3) reads C0D1h in bits 15:10 — OUI bits 19 through 24 — with the six-bit model number (bits 9:4) and four-bit revision number (bits 3:0) given no values in the datasheet.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.5.3, §5.5.4")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PHY-ID"))) (param (name decision_id) (value (str "D-NIC-PHY-ID"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-PHY-ID") (required_checks "CHK-NIC-PHY-ID-POS") (required_checks "CHK-NIC-PHY-ID-NEG"))

(obligation (id "OB-NIC-PHY-BASIC") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "PHY register 0 (Basic Control) carries the self-clearing Reset (bit 15), Loopback (14), Speed Select (13) and Duplex Mode (8) — ignored when Auto-Negotiation Enable (12) is set, the defaults of bits 13 and 12 determined by the SPEED_SEL strap — Power Down (11), Restart Auto-Negotiate (9, self-clearing) and Collision Test (7). PHY register 1 (Basic Status) reads the fixed ability bits 100Base-TX full and half duplex, 10Base-T full and half duplex, Auto-Negotiate Ability and Extended Capabilities (all 1) with 100Base-T4 fixed 0, plus Auto-Negotiate Complete (5), Remote Fault (4, latch-high), Link Status (2, latch-low — 1 is link up) and Jabber Detect (1, latch-high).") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.5.1, §5.5.2, Note 5-1, Table 2-2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PHY-BASIC"))) (param (name decision_id) (value (str "D-NIC-PHY-BASIC"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-PHY-BASIC") (required_checks "CHK-NIC-PHY-BASIC-POS") (required_checks "CHK-NIC-PHY-BASIC-NEG"))

(obligation (id "OB-NIC-PHY-EXT") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The remaining PHY registers: index 4 advertises the pause and technology abilities (100Base-TX fixed able, selector field 00001b, the 10 Mbps and full-duplex advertisement bits strap-determined); index 5 reports the link partner's ability and never a next page; index 6 carries the auto-negotiation expansion flags (parallel detection fault latch-high); index 17 carries EDPWRDOWN and the ENERGYON energy-detect indication (reset to 1 by hardware reset, unaffected by software reset); index 18 carries the PHY MODE selection and the PHYAD address (00001b), both NASR; index 27 carries the 10M receive-PLL lock control and the 10Base-T polarity indication; indices 29 and 30 carry the eight PHY interrupt source flags (latch-high) and their masks; index 31 carries the auto-negotiation-done indication and the HCDSPEED speed indication, its default determined by the default Ethernet settings.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.5.5–§5.5.13, Table 5-9, Notes 5-3/5-4")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PHY-EXT"))) (param (name decision_id) (value (str "D-NIC-PHY-EXT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-PHY-EXT") (required_checks "CHK-NIC-PHY-EXT-POS") (required_checks "CHK-NIC-PHY-EXT-NEG"))

(obligation (id "OB-NIC-TX-CMD") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "Each buffer queued for transmission begins with two command DWORDs in the TX data FIFO: TX command 'A' carries Interrupt on Completion (bit 31), Buffer End Alignment (25:24 — 4-, 16- or 32-byte, 11b reserved), Data Start Offset (20:16, 0–31 bytes), First Segment (13), Last Segment (12) and Buffer Size in bytes (10:0 — excluding the buffer-end alignment padding and the data start offset); TX command 'B' carries the 16-bit Packet Tag (31:16), Add CRC Disable (13), Disable Ethernet Frame Padding (12) and Packet Length in bytes (10:0 — the whole packet, excluding offset and padding). Both command words are required for every buffer of a packet, TX command 'B' must be identical for every buffer of a given packet, and every Packet Length field must equal the actual number of bytes in the packet — a violation asserts TXE.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.12, §3.12.2, Table 3-11, Table 3-12")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TX-CMD"))) (param (name decision_id) (value (str "D-NIC-TX-CMD"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TX-CMD") (required_checks "CHK-NIC-TX-CMD-POS") (required_checks "CHK-NIC-TX-CMD-NEG"))

(obligation (id "OB-NIC-TX-STATUS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "Upon completion of a packet's transmission, irrespective of success or failure, one TX status DWORD is written to the TX status FIFO: Packet Tag echo (bits 31:16), Error Status (15 — the logical OR of bits 11, 10, 9, 8, 2 and 1), Loss of Carrier (11), No Carrier (10), Late Collision (9), Excessive Collisions (8), Collision Count (6:3 — not valid when Excessive Collisions is set), Excessive Deferral (2) and Deferred (0). Data transmission is suspended if the TX status FIFO becomes full and resumes when the host reads status; with TXSAO set the transmitter continues, an overrun generates no TXE, TXSUSED stays at zero and the host is responsible for re-synchronizing TX status.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.12.4")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TX-STATUS"))) (param (name decision_id) (value (str "D-NIC-TX-STATUS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TX-STATUS") (required_checks "CHK-NIC-TX-STATUS-POS") (required_checks "CHK-NIC-TX-STATUS-NEG"))

(obligation (id "OB-NIC-TX-FIFO-USAGE") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The actual TX data FIFO space consumed by a buffer: TX command 'A' is stored for every buffer; TX command 'B' is stored only when the First Segment bit is set; DWORD-long data added as the Data Start Offset or as end padding is removed before the data is written to the FIFO, sub-DWORD remainders are kept; the payload is written. Fragmentation rules: each buffer can start and end on any arbitrary byte alignment, the first and final buffers of a packet can be any length, middle buffers are at least 4 bytes, and a packet's total consumption in the TX FIFO (MIL) must be limited to no more than 2036 bytes — the 86-fragment worst case.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.12.5, §3.12.3.1, §3.12.3.2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TX-FIFO-USAGE"))) (param (name decision_id) (value (str "D-NIC-TX-FIFO-USAGE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TX-FIFO-USAGE") (required_checks "CHK-NIC-TX-FIFO-USAGE-POS") (required_checks "CHK-NIC-TX-FIFO-USAGE-NEG"))

(obligation (id "OB-NIC-TX-ERRORS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "TXE (INT_STS bit 13) asserts when the actual packet length count does not match the Packet Length field of the TX command, when TX command 'B' words differ between buffers of a packet, on host overrun of the TX data FIFO, or on overrun of the TX status FIFO (unless TXSAO is enabled); the transmitter continues operation after TXE.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.12.7")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TX-ERRORS"))) (param (name decision_id) (value (str "D-NIC-TX-ERRORS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-TX-ERRORS") (required_checks "CHK-NIC-TX-ERRORS-POS") (required_checks "CHK-NIC-TX-ERRORS-NEG"))

(obligation (id "OB-NIC-RX-STATUS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The RX status word, one per received frame in the RX status FIFO: Filtering Fail (bit 30 — the frame failed address filtering), Packet Length in bytes (29:16), Error Status (15 — the internal logical OR of bits 11, 7, 6 and 1), Broadcast Frame (13), Length Error (12), Runt Frame (11 — passed to the host only when PASSBAD is set), Multicast Frame (10), Frame Too Long (7 — over the 1518-byte maximum, an indication only, reception is not truncated), Collision Seen (6 — a late collision), Frame Type (5 — set for an Ethernet-type frame, never for runts under 14 bytes), Receive Watchdog time-out (4 — a frame greater than 2048 through 2560 bytes), MII Error (3), Dribbling Bit (2 — with its validity conditions), and CRC Error (1 — not valid for runt frames, late collisions or watchdog time-outs).") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.13.3")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RX-STATUS"))) (param (name decision_id) (value (str "D-NIC-RX-STATUS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RX-STATUS") (required_checks "CHK-NIC-RX-STATUS-POS") (required_checks "CHK-NIC-RX-STATUS-NEG"))

(obligation (id "OB-NIC-RX-ERRORS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "RXE (INT_STS bit 14) asserts on a host underrun of the RX data FIFO, a host underrun of the RX status FIFO, or an overrun of the RX status FIFO; the receiver continues operation after RXE, but if an underrun condition occurs a soft reset is required to regain host synchronization. The host must never read more data than what is available in the FIFOs.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.13.5, §3.13")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RX-ERRORS"))) (param (name decision_id) (value (str "D-NIC-RX-ERRORS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RX-ERRORS") (required_checks "CHK-NIC-RX-ERRORS-POS") (required_checks "CHK-NIC-RX-ERRORS-NEG"))

(obligation (id "OB-NIC-RESETS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The LAN9118 has five reset sources (Table 3-10): power-on reset (the internal reset asserts for approximately 22 ms; READY reads 0 until the POR completes), the nRESET hardware input, soft reset (HW_CFG SRST — a full reset of the MAC CSRs and of the SCSRs except NASR bits, also clearing TXE/RXE, self-clearing when complete, completing only with the internal PHY operational), PHY reset via PMT_CTRL PHY_RST (the internal logic holds the PHY reset for a minimum of 100 µs, the bit self-clearing), and PHY reset via PHY register 0 bit 15 (self-clearing). POR and nRESET reset every circuit group Table 3-10 lists, including latching the configuration straps and the EEPROM MAC-address reload; SRST also triggers the EEPROM presence check. After any PHY reset the application must wait for the PHY's Link Status bit before transmitting or receiving; after a POR, nRESET or SRST it must verify EPC Busy has cleared before EEPROM, GPIO-function or MAC-address changes.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§3.11, Table 3-10, §3.11.1–§3.11.5, §5.3.13, Notes 3-11/3-12")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RESETS"))) (param (name decision_id) (value (str "D-NIC-RESETS"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-NIC-RESETS") (required_checks "CHK-NIC-RESETS-POS") (required_checks "CHK-NIC-RESETS-NEG"))

(obligation (id "OB-NIC-RESERVED") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "Unless otherwise stated, reserved bit fields must be written with zeros to ensure future compatibility, and the value of reserved bits is not supported on a read; the RESERVED register locations (offsets 60h, 94h and B8h–FCh) return a random value when read, must not be modified by system software, and writes to them may cause system failure.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.1, Table 5-1")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-RESERVED"))) (param (name decision_id) (value (str "D-NIC-RESERVED"))) (param (name source_semantics) (value (str "reserved")))) (dependencies "REQ-D-NIC-RESERVED") (required_checks "CHK-NIC-RESERVED-POS") (required_checks "CHK-NIC-RESERVED-NEG"))

(obligation (id "OB-NIC-WIDTH") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The effect of a host access that is neither a 32-bit transfer nor a §3.6-conformant pair of 16-bit transfers — a byte access, or a 16-bit access breaking the DWORD-boundary pairing rules — is not specified: the datasheet defines 32-bit and 16-bit bus transfers only and states no error or truncation behaviour for any other shape.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§1.10, §3.6 (the silence measured against the two defined widths)")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-WIDTH"))) (param (name decision_id) (value (str "D-NIC-WIDTH"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-NIC-WIDTH") (required_checks "CHK-NIC-WIDTH-POS") (required_checks "CHK-NIC-WIDTH-NEG"))

(obligation (id "OB-NIC-STRAP-RESETS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The reset values of HW_CFG bit 2 (the D32/nD16 strap — set is 32-bit operation), PHY register 0 bits 13 and 12 (Speed Select, Auto-Negotiation Enable), PHY register 4 bits 8, 7, 6 and 5 (the technology advertisement) and PHY register 31 bits 4:2 (the HCDSPEED speed indication's default) are determined by the configuration straps — D32/nD16 strapped on EEDIO, SPEED_SEL on pin 74 (Table 2-2: strap 0 is 10 Mbps half-duplex with auto-negotiation disabled; strap 1 is 100 Mbps half-duplex with auto-negotiation enabled) — not by the datasheet; the strap values are the board's composition choice, owned by P5-BOARD.4's composition verdict.") (authority architecture) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.9 bit 2, §5.5.1 Note 5-1, §5.5.5 Note 5-3, §5.5.13 Note 5-4, §3.6, Table 2-2")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-STRAP-RESETS"))) (param (name decision_id) (value (str "D-NIC-STRAP-RESETS"))) (param (name source_semantics) (value (str "implementation-defined"))) (param (name composition_disposition) (value (str "required")))) (dependencies "REQ-D-NIC-STRAP-RESETS") (required_checks "CHK-NIC-STRAP-RESETS-POS") (required_checks "CHK-NIC-STRAP-RESETS-NEG"))

(obligation (id "OB-NIC-TIME-SOURCES") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "FREE_RUN (a 25 MHz free-running 32-bit counter readable at offset 9Ch, running in every power state), GPT_CNT (a 100 µs-resolution timer count readable at offset 90h) and IRQ_CFG's INT_DEAS (a 10 µs-granularity deassertion interval with an MMIO-visible status bit) are guest-readable time sources; rv64i-lab-env-v0 v0 excludes every guest-reachable time source — no CSR counter and no memory-mapped one (OB-ENV-VIRTUAL-TIME) — so the model must not wire these counters to wall-clock time, and the harness's retired-instruction count must never become target-visible through them; their MMIO-visible values are frozen or otherwise guest-deterministic, the exact disposition being P5-BOARD.4's composition verdict.") (authority laboratory) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.18, §5.3.16, §5.3.2 (the tension measured against rv64i-lab-env-v0 v0 OB-ENV-VIRTUAL-TIME)")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-TIME-SOURCES"))) (param (name decision_id) (value (str "D-NIC-TIME-SOURCES"))) (param (name source_semantics) (value (str "implementation-defined"))) (param (name composition_disposition) (value (str "required")))) (dependencies "REQ-D-NIC-TIME-SOURCES") (required_checks "CHK-NIC-TIME-SOURCES-POS") (required_checks "CHK-NIC-TIME-SOURCES-NEG"))

(obligation (id "OB-NIC-PHY-LINK") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "The PHY's link and auto-negotiation state — Basic Status bit 2 (Link Status, latch-low), bit 5 (Auto-Negotiate Complete), register 31's HCDSPEED, register 17's ENERGYON — is wire-domain state, and Note 3-11 makes it load-bearing: after any PHY reset the application must wait for Link Status before transmitting or receiving. On netboard-lab-v0 the wire is the recorded-trace replay backend (D-BOARD-NET-BACKEND), so the values a guest reads are the deterministic replay's declared link scene — never a live host link — the exact scene being P5-BOARD.4's composition verdict.") (authority laboratory) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.5.2, §5.5.13, §5.5.8, §3.11 Note 3-11 (the wire-domain nature measured against D-BOARD-NET-BACKEND)")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-PHY-LINK"))) (param (name decision_id) (value (str "D-NIC-PHY-LINK"))) (param (name source_semantics) (value (str "implementation-defined"))) (param (name composition_disposition) (value (str "required")))) (dependencies "REQ-D-NIC-PHY-LINK") (required_checks "CHK-NIC-PHY-LINK-POS") (required_checks "CHK-NIC-PHY-LINK-NEG"))

(obligation (id "OB-NIC-GPIO-PINS") (contract_id "lan9118-v0") (contract_version "0") (profile_ids "lan9118-lab-v0") (direction device-guarantee) (statement "GPIO_CFG's GPIODn reads reflect the current state of the corresponding GPIO/LED pins, and EEPR_EN can mux the internal MII signals TX_EN, RX_DV, TX_CLK and RX_CLK onto pins (Table 5-4); netboard-lab-v0 wires no GPIO, LED or EEPROM pins, so every pin-readable value is the composition's declared tie-off — never a live host signal — owned by P5-BOARD.4's composition verdict.") (authority laboratory) (source_refs (source_id "MICROCHIP-LAN9118") (locator "§5.3.14, Table 5-4 (the pin-domain nature measured against board.sexp's absences)")) (parameters (param (name requirement_id) (value (str "REQ-D-NIC-GPIO-PINS"))) (param (name decision_id) (value (str "D-NIC-GPIO-PINS"))) (param (name source_semantics) (value (str "implementation-defined"))) (param (name composition_disposition) (value (str "required")))) (dependencies "REQ-D-NIC-GPIO-PINS") (required_checks "CHK-NIC-GPIO-PINS-POS") (required_checks "CHK-NIC-GPIO-PINS-NEG"))

