;; profile.sexp — the resolution dossier of rv64gc-lab-v0 (P4-SYSTEM.1; brief 2026-10-02,
;; executed 2026-10-03).
;; One document form; validate with
;;   python3 scripts/check_sexp_schema.py profiles/rv64gc-lab-v0/profile.sexp schema/profile.sexp

(comment "profiles/rv64gc-lab-v0/profile.sexp — the RESOLVED profile selection for the"
         "Linux-capable processor (P4-SYSTEM.1): nothing is inferred from the letters 'GC';"
         "every element below carries its source locator, and the dependency closure is"
         "measured against the pinned publication (sources.sexp)."
         ""
         "THE STAGE IS DECLARED: (vehicle (route generated-definition)) — the route flipped"
         "at P4-SYSTEM.2 slice (h) (2026-10-03, D-ROUTE-FLIP): the definition pipeline has"
         "landed — the encoding composition, the 33-CSR state document, the 62-guest corpus"
         "and the interaction matrix are tracked and gate-judged, and the full extraction"
         "contract attaches. Until slice (h) this dossier declared (route profile-resolution)"
         "and the pipeline gates refused any encoding, state-census, guest-corpus or matrix"
         "document beside it; the staged payload was authored and proven under"
         "target/p4-system-2/ and moved byte-exact at the flip."
         ""
         "FLOATING POINT IS DECLARED, NOT YET MODELLED: F and D are in the profile (the"
         "standard RV64G userspace ABI is LP64D, which requires D — RVI-PSABI), and the model"
         "implements none of it until the FP backend passes qualification (P4-SYSTEM.7); the"
         "CPU-SYSTEM gate verdict reads incomplete until then.")

(profile (id "rv64gc-lab-v0") (version "0") (status "development") (architecture "RISC-V") (base "RV64I") (chapter_version "2.1") (spec_revision "v20260120") (harts 1) (xlen 64) (ilen 32) (ialign 16) (endianness little) (comment "IALIGN=16 with C (RVI-C 27.1: 'IALIGN=16'); ILEN stays 32. harts 1 — multicore is MC-MULTICORE's, never smuggled in.") (extensions "M") (extensions "A") (extensions "F") (extensions "D") (extensions "C") (extensions "Zicntr") (extensions "Zicsr") (extensions "Zifencei") (extensions "Sstc") (comment "the declared order is the canonical ISA-string order (RVI-NAMING 36.1): rv64imafdc_zicntr_zicsr_zifencei_sstc") (privilege_modes "M") (privilege_modes "S") (privilege_modes "U") (comment "M-mode firmware, S-mode kernel, U-mode userspace; the hypervisor extension is excluded (D-NO-H).") (sources "RVI-INTRO") (sources "RVI-RV32I") (sources "RVI-RV64I") (sources "RVI-NAMING") (sources "RVI-G-LISTING") (sources "RVI-M") (sources "RVI-A") (sources "RVI-F") (sources "RVI-D") (sources "RVI-C") (sources "RVI-ZC") (sources "RVI-ZICSR") (sources "RVI-ZIFENCEI") (sources "RVI-ZICNTR") (sources "RVI-RVWMO") (sources "RVP-INTRO") (sources "RVP-CSR") (sources "RVP-MACHINE") (sources "RVP-SUPERVISOR") (sources "RVP-INSNS") (sources "RVP-SSTC") (sources "RVI-PSABI") (sources "RVI-SBI") (sources "SIFIVE-FU540-C000")
  (comment "─────────────────────────────────────────────────────────────── architectural state")
  (state (integer_registers 32) (comment "x0..x31") (x0_hardwired_zero true) (register_width_bits 64) (program_counter "pc") (comment "the f0–f31 floating-point file and the per-CSR field census land with the state document in the definition leaves (P4-SYSTEM.2/.7)") (csrs "mhartid") (csrs "misa") (csrs "mstatus") (csrs "mtvec") (csrs "medeleg") (csrs "mideleg") (csrs "mie") (csrs "mip") (csrs "mscratch") (csrs "mepc") (csrs "mcause") (csrs "mtval") (csrs "menvcfg") (csrs "mcounteren") (csrs "mcycle") (csrs "minstret") (csrs "sstatus") (csrs "stvec") (csrs "sscratch") (csrs "sepc") (csrs "scause") (csrs "stval") (csrs "sie") (csrs "sip") (csrs "scounteren") (csrs "satp") (csrs "stimecmp") (csrs "cycle") (csrs "time") (csrs "instret") (csrs "fflags") (csrs "frm") (csrs "fcsr") (comment "D-CSR-SET: the committed minimum, 33 named CSRs; WPRI/WARL/WLRL per-field semantics are P4-SYSTEM.2's") (authority architecture) (source "RVI-RV32I §1.1.1 Programmers' Model; RVI-RV64I §3.1.1 Register State; RVP-CSR 1.1 (the CSR listings); RVI-F 20.1.1 (the FP CSRs); RVP-SSTC 12.1 (stimecmp); RVI-ZICNTR 6.1 (the counter CSRs)"))
  (comment "─────────────────────────────────────────────────────────────── instruction scope" "The RV64I base census (52 forms — the same enumeration and source as rv64i-lab-v0, the" "profile this one extends) plus the evidence leaves' extension censuses (D-SCOPE-CENSUS):" "the Zicsr six (RVI-ZICSR §5.1.1), the privileged four (RVP-INSNS 18.1; D-PRIV-INSNS) and" "the Zicntr three (RVI-ZICNTR §6.1.1) — 65 forms at P4-SYSTEM.2 slice (e). The Zicntr" "three are the specification's instruction LISTINGS; the encoding realizes them as csrrs" "specializations (definitions/riscv/zicntr.sexp's pseudos) — the census is the profile's" "spec-facing form set; the pseudo relation is the realization's, and EXERCISE-COVERAGE" "observes the spelling in the expectations' insn text (measured: its numerator is the" "first token of (step (insn …))).")
  (scope (count_base 40) (count_rv64i_additions 12) (count_total 65) (authority architecture) (source "RVI-RV32I §1.1.4–§1.1.8; RVI-RV64I §3.1.2–§3.1.3; RVI-ZICSR §5.1.1; RVI-ZICNTR §6.1.1; RVP-INSNS 18.1") (base_u_type "LUI") (base_u_type "AUIPC") (base_jumps "JAL") (base_jumps "JALR") (base_branches "BEQ") (base_branches "BNE") (base_branches "BLT") (base_branches "BGE") (base_branches "BLTU") (base_branches "BGEU") (base_loads "LB") (base_loads "LH") (base_loads "LW") (base_loads "LBU") (base_loads "LHU") (base_stores "SB") (base_stores "SH") (base_stores "SW") (base_op_imm "ADDI") (base_op_imm "SLTI") (base_op_imm "SLTIU") (base_op_imm "XORI") (base_op_imm "ORI") (base_op_imm "ANDI") (base_op_imm "SLLI") (base_op_imm "SRLI") (base_op_imm "SRAI") (base_op "ADD") (base_op "SUB") (base_op "SLL") (base_op "SLT") (base_op "SLTU") (base_op "XOR") (base_op "SRL") (base_op "SRA") (base_op "OR") (base_op "AND") (base_misc_mem "FENCE") (base_system "ECALL") (base_system "EBREAK") (rv64_loads "LWU") (rv64_loads "LD") (rv64_stores "SD") (rv64_op_imm_32 "ADDIW") (rv64_op_imm_32 "SLLIW") (rv64_op_imm_32 "SRLIW") (rv64_op_imm_32 "SRAIW") (rv64_op_32 "ADDW") (rv64_op_32 "SUBW") (rv64_op_32 "SLLW") (rv64_op_32 "SRLW") (rv64_op_32 "SRAW") (zicsr_csrs "CSRRW") (zicsr_csrs "CSRRS") (zicsr_csrs "CSRRC") (zicsr_csrs "CSRRWI") (zicsr_csrs "CSRRSI") (zicsr_csrs "CSRRCI") (system_privileged "MRET") (system_privileged "SRET") (system_privileged "WFI") (system_privileged "SFENCE.VMA") (zicntr_counters "RDCYCLE") (zicntr_counters "RDTIME") (zicntr_counters "RDINSTRET"))
  (vehicle (route generated-definition) (authority laboratory) (source "docs/tasks/P4-SYSTEM.md, the .2 design brief (2026-10-03), checkpoint (h) — the atomic flip"))
  (comment "─────────────────────────────────────────────────────────────── resolved decisions" "id | authority | the decision | where it comes from")
  (decision (id "D-GC-COMPOSITION") (authority architecture) (statement "The profile's instruction set is RV64I plus the extensions M, A, F, D and C, plus Zicsr and Zifencei, plus Zicntr: 'G' is the defined abbreviation for the IMAFDZicsr_Zifencei base-and-extensions combination, and this profile is G plus C and Zicntr on the unprivileged side and Sstc on the privileged side.") (source "RVI-NAMING 36.1 (the G definition); RVI-ZICNTR 6.1; RVP-SSTC 12.1"))
  (decision (id "D-EXT-CLOSURE") (authority architecture) (statement "The extension dependency closure is complete under the pinned revision: D depends on F; F depends on Zicsr for control and status register access; and C decomposes as Zca always plus Zcd when D is present (Zcf exists only at RV32). Nothing in this profile is inferred from the letter 'G' alone.") (source "RVI-D 21.1; RVI-F 20.1; RVI-ZC 28.1.2; RVI-NAMING 36.1"))
  (decision (id "D-PRIV-REVISION") (authority architecture) (statement "The privileged architecture is the pinned publication's: Machine-Level ISA Version 1.13 and Supervisor-Level ISA Version 1.13, under spec revision v20260120 — the same publication family as the unprivileged pin.") (source "RVP-MACHINE 2.1; RVP-SUPERVISOR 11.1 (the chapters' own stated versions)"))
  (decision (id "D-PRIV-MODES") (authority laboratory) (statement "The profile implements machine, supervisor and user modes — the minimum a Linux-capable profile needs (M-mode firmware, S-mode kernel, U-mode userspace); the hypervisor extension is excluded, and every mode-dependent behaviour is tested in each supported mode (P4-SYSTEM.2).") (source "RVP-INTRO (the modes and their intent); ROADMAP.md §P4"))
  (decision (id "D-SV39") (authority laboratory) (statement "Translation is Sv39: of the three paged virtual-memory schemes defined for SXLEN=64 (Sv39, Sv48, Sv57), the profile selects the minimal Linux-capable one — also the one the pinned SoC precedent implements (the FU540-C000's U54 supports Bare and Sv39). The U54's A/D behaviour (page faults instead of setting PTE A/D bits) is recorded as P4-SYSTEM.3's policy input, not as this profile's rule.") (source "RVP-SUPERVISOR 11.1.3–11.1.4; SIFIVE-FU540-C000 §4.7"))
  (decision (id "D-IALIGN-16") (authority architecture) (statement "With the C extension present, IALIGN is 16 — instructions start on any 16-bit boundary — while ILEN remains 32; no instruction-address-misaligned exception arises from C's 16-bit forms.") (source "RVI-C 27.1"))
  (decision (id "D-ZICNTR") (authority laboratory) (statement "The Zicntr base counters (cycle, time, instret) are included — explicitly beyond the G abbreviation — because a Linux-capable profile must offer the supervisor-mode time read; the counters' rate and progress semantics are the environment contract's to declare (P4-SYSTEM.5 and P4-SYSTEM.9), not this resolution's. Zihpm (hardware performance monitors) is not selected.") (source "RVI-ZICNTR 6.1; ROADMAP.md §P4"))
  (decision (id "D-SSTC") (authority laboratory) (statement "Sstc is included — the supervisor timer-compare register stimecmp, gated by menvcfg.STCE — so an S-mode kernel programs its own timer without an M-mode round trip.") (source "RVP-SSTC 12.1"))
  (decision (id "D-FP-DEFER") (authority laboratory) (statement "F and D are in the profile because the standard RV64G userspace ABI is LP64D, which requires the D extension; the model implements no floating point until the floating-point backend passes qualification (P4-SYSTEM.7), the CPU-SYSTEM gate verdict reads incomplete until then, and a Sail-versus-Spike floating-point comparison is one implementation twice (the SoftFloat shared ancestry), never independent numeric evidence.") (source "RVI-PSABI (the LP64D statement); docs/decisions/reference_softfloat-shared-ancestry.md; the P4-SYSTEM tree's non-goals"))
  (decision (id "D-ABI") (authority laboratory) (statement "The toolchain ABI is LP64D — the standard RV64G ABI (ELFCLASS64 with EF_RISCV_FLOAT_ABI_DOUBLE, the hardware floating-point calling convention with ABI_FLEN=64); the toolchain is the host's clang/lld 21.1.8 with an rv64gc target (the existing guest-toolchain decision).") (source "RVI-PSABI (the ABI table and the LP64D note); docs/decisions/decision_c-guest-routing-and-toolchain.md"))
  (decision (id "D-SBI") (authority laboratory) (statement "The firmware contract for the Linux boot route is SBI 2.0: compatible M-mode firmware provides selected SBI services (timer, console, system reset, hart state management) before entering the S-mode kernel — real firmware, and a host-modelled SBI is a different contract, never silently substituted.") (source "RVI-SBI (the extension inventory: base, TIME, sPI, RFENCE, HSM, SRST, DBCN); ROADMAP.md §P6"))
  (decision (id "D-CSR-SET") (authority laboratory) (statement "The implemented CSR set is the committed minimum of 33: mhartid and misa; mstatus, mtvec, medeleg, mideleg, mie, mip, mscratch, mepc, mcause and mtval; menvcfg, mcounteren, mcycle and minstret; sstatus, stvec, sscratch, sepc, scause, stval, sie, sip and scounteren; satp; stimecmp; cycle, time and instret; and fflags, frm and fcsr. Per-CSR field semantics (WPRI/WARL/WLRL) belong to the privilege leaf (P4-SYSTEM.2).") (source "RVP-MACHINE 2.1; RVP-SUPERVISOR 11.1; RVP-CSR 1.1; RVI-F 20.1.1; RVI-ZICNTR 6.1; RVP-SSTC 12.1"))
  (decision (id "D-NO-PMP") (authority laboratory) (statement "PMP is excluded at v0: the privileged architecture's physical memory protection unit is optional, and the first boot contract does not require it; the decision is revisited by the board branch that needs it.") (source "RVP-MACHINE §2.1.7 ('an optional physical memory protection (PMP) unit'); ROADMAP.md §P4"))
  (decision (id "D-NO-H") (authority laboratory) (statement "The hypervisor extension is excluded: the profile has one hart and no virtualization workload in the first Linux profile; H would arrive with a consumer, never ahead of one.") (source "RVP-INTRO; ROADMAP.md §P4"))
  (decision (id "D-RVWMO") (authority architecture) (statement "The memory consistency model is RVWMO: with the A extension in the profile the memory model is load-bearing even at one hart (the AMOs and their aq/rl annotations), and the multicore exposure of the weak model is MC-MULTICORE's, never smuggled in.") (source "RVI-RVWMO 17.1; RVI-A 12.1"))
  (decision (id "D-PRIV-INSNS") (authority architecture) (statement "The privileged instructions in scope are mret, sret, wfi and sfence.vma (the pinned privileged instruction listings); wfi's wake semantics belong to the interrupt/counter/wait leaf (P4-SYSTEM.5).") (source "RVP-INSNS 18.1; RVP-MACHINE 2.1; RVP-SUPERVISOR 11.1"))
  (decision (id "D-RESOLUTION-ROUTE") (authority laboratory) (statement "This unit is a profile resolution: the selection is exact and citable, and the definition pipeline (encoding fragments, semantics, guests) has not started; the dossier declares the profile-resolution vehicle route, and the definition-pipeline gates refuse any encoding, state-census or guest-corpus document beside the declaration.") (source "docs/tasks/P4-SYSTEM.md, the .1 design brief (2026-10-02)") (note "Superseded by D-ROUTE-FLIP (P4-SYSTEM.2 slice h, 2026-10-03): the definition pipeline landed — the statement's 'has not started' is the historical record of the resolution stage, kept verbatim because the requirement catalogue mirrors it (RECORD-SCHEMA rule 4); the route it declared is replaced, not edited."))
  (decision (id "D-ROUTE-FLIP") (authority laboratory) (statement "The definition pipeline has landed and the dossier declares the generated-definition vehicle route: the unit carries its encoding composition (the RV64I base plus Zicsr, Zicntr and the privileged-system fragment — (status partial) with six declared slots for M/A/F/D/C/Zifencei), the 33-CSR state document, the 62-guest corpus (the base mirror plus the mode matrix) and the 7-axis interaction matrix, and the generated mirrors (state_rv64gc.rs, definition_rv64gc.rs, guests_rv64gc.rs) are tracked because their canonical inputs are tracked in the same commit (decision_generated-mirror-needs-tracked-input).") (source "docs/tasks/P4-SYSTEM.md, the .2 design brief (2026-10-03), checkpoint (h)"))
  (decision (id "D-SCOPE-CENSUS") (authority laboratory) (statement "The scope block enumerates the RV64I base census (52 forms — the same enumeration and source as rv64i-lab-v0); each extension's instruction census lands with its encoding fragment in the evidence leaves (the RV32/64G listings and the privileged listings are the census references), and the declared scope grows only with them.") (source "RVI-RV32I §1.1.4–§1.1.8; RVI-RV64I §3.1.2–§3.1.3; RVI-G-LISTING 35.1; RVP-INSNS 18.1")))
