;; state.sexp — the architectural-state document of `rv64gc-lab-v0` (P4-SYSTEM.2 slice c1).
;; One document form; validate with
;;   python3 scripts/check_sexp_schema.py target/p4-system-2/state.sexp schema/state.sexp
;;
;; ⛔ STAGED, NOT PLACED (2026-10-03): the unit declares (vehicle (route profile-resolution)),
;; under which a state.sexp in profiles/rv64gc-lab-v0/ is a refused contradiction (EXTRACTION).
;; This document therefore lives at target/p4-system-2/state.sexp — untracked, fully validated
;; from here (the commands are the slice's checklist), and MOVES into the unit unchanged at the
;; atomic route flip (P4-SYSTEM.2 slice h). Nothing under profiles/ is allowed to reference it
;; until then.
;;
;; RESET PHILOSOPHY (the rv64i laboratory-reset precedent, extended): RVP-MACHINE §2.1.4 fixes
;; little (mode <- M; mstatus.MIE <- 0; mstatus.MPRV <- 0; misa <- the maximal extension set;
;; pc <- the reset vector; mcause <- the reset cause) and leaves "all other hart state
;; UNSPECIFIED". Every UNSPECIFIED reset below is a laboratory pick of a defined value —
;; authority laboratory, stated per field, never silence. Bit POSITIONS derive from the pinned
;; encoding.h masks (the specification renders the layouts as figure images); discipline terms
;; are RVP-CSR §1.1.3.1–3's.
;;
;; VIEWS HAVE NO STORAGE: sstatus/sie/sip restrict mstatus/mie/mip; cycle/instret shadow
;; mcycle/minstret. A `view_of` row declares the underlying register; a write through a view is
;; a write to the underlying storage under the view's mask (the alias discipline the integer
;; file already states). The `time` register is special: its value source is the ENVIRONMENT's
;; memory-mapped mtime — environment state, not a CSR (P4-SYSTEM.5/.9's contract).

(state
  (profile_id "rv64gc-lab-v0")
  (xlen 64)
  (note "Architectural state of the resolved rv64gc-lab-v0 selection (P4-SYSTEM.1): the RV64I integer file and pc; the current privilege mode (M/S/U, D-PRIV-MODES); the f0-f31 floating-point file at FLEN=64 (P4-SYSTEM.7 slice b); and the 33 CSRs of D-CSR-SET with their per-field WPRI/WARL/WLRL tables. Staged at target/p4-system-2/ until the route flip; see the header.")
  (integer_registers
    (count 32) (width_bits 64) (ids "x0..x31") (authority architecture)
    (source "RVI-RV32I §1.1.1; RVI-RV64I §3.1.1")
    (x0 (hardwired_zero true) (authority architecture) (source "RVI-RV32I §1.1.1")
        (statement "Register x0 is hardwired with all bits equal to 0. A write to it is discarded; a read of it yields 0."))
    (named_by_the_isa_chapter (named-register (reg "x1") (role "return address for a call") (authority software-convention) (source "RVI-RV32I §1.1.1")))
    (named_by_the_isa_chapter (named-register (reg "x5") (role "alternate link register") (authority software-convention) (source "RVI-RV32I §1.1.1")))
    (named_by_the_isa_chapter (named-register (reg "x2") (role "stack pointer") (authority software-convention) (source "RVI-RV32I §1.1.1")))
    (reset (value "0 for x1..x31") (authority laboratory) (source "RVI-INTRO, RISC-V Software Execution Environments and Harts")
           (statement "The unprivileged specification does not define the initial contents of x1..x31 — the EEI defines the initial state of the program (the rv64i document's identical declaration; the base file is mode-independent under the reset state: M-mode, MPRV=0, no PMP — the .2 brief's soundness assertion, measured by execution).")))

  (special_registers
    (register (id "pc") (width_bits 64) (holds "the address of the current instruction") (authority architecture) (source "RVI-RV32I §1.1.1") (reset "the declared entry address of the loaded image") (reset_authority laboratory)))

  ;; ---- the current privilege mode ------------------------------------------------------------
  (privilege_mode
    (modes m) (modes s) (modes u)
    (authority architecture)
    (source "RVP-INTRO (the modes and their intent); D-PRIV-MODES")
    (reset (value "m") (authority architecture) (source "RVP-MACHINE §2.1.4")
           (statement "Upon reset, a hart's privilege mode is set to M. The mode is hart state, not a CSR: it changes on trap delivery and xret and is readable nowhere as a register; the two-level stack that restores it (xPP/xPIE/xIE) lives in mstatus, architected.")))

  ;; ---- the floating-point register file (P4-SYSTEM.7 slice b — modelled after the slice-(a)
  ;;      qualification, SEMULITH-P4-0039) -----------------------------------------------------
  (fp_registers (count 32) (width_bits 64) (ids "f0..f31")
       (authority architecture) (source "RVI-F §20.1.1 (the f registers f0-f31); RVI-D §21.1.2 (FLEN=64 with D selected; the LP64D ABI, D-ABI)")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The f-file's reset content is architecturally UNSPECIFIED; the laboratory resets it to 0 — unobservable as such (FS resets Off, so the file is unreadable until software enables FP, and NaN-boxing is the write-side discipline of the instructions that fill it, not the file's). The file is census-hidden state: observations are through the x-registers alone (the leaf's decision 8 — fmv/fclass/compares/stores, fflags/frm via Zicsr).")))

  ;; ==========================================================================================
  ;; the 33 CSRs of D-CSR-SET (profile.sexp's state block), machine level first
  ;; ==========================================================================================

  (csr (id "mhartid") (address 3860) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.5")
       (field (id "hart_id") (bit_hi 63) (bit_lo 0) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.5; the profile's harts field"))
       (reset (value "0") (authority architecture) (source "RVP-MACHINE §2.1.1.5")
              (statement "The mhartid register is read-only; the hart id of the single hart is 0.")))

  (csr (id "misa") (address 769) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.1")
       (field (id "MXL") (bit_hi 63) (bit_lo 62) (discipline warl)
              (legalize (read-only 2)) (reset "2") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.1 (the MXL table)"))
       (field (id "Extensions") (bit_hi 25) (bit_lo 0) (discipline warl)
              (legalize (read-only 1315117)) (reset "0x14112D") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.1; D-GC-COMPOSITION"))
       (field (id "wpri_61_26") (bit_hi 61) (bit_lo 26) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0x800000000014112D") (authority architecture) (source "RVP-MACHINE §2.1.4")
              (statement "The misa register is reset to enable the maximal set of supported extensions — here exactly the declared selection; the laboratory makes the whole register read-only at that value (a legal WARL choice, recorded rather than hidden).")))

  (csr (id "mstatus") (address 768) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.6; bit positions from the pinned encoding.h masks")
       (field (id "SIE") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.1"))
       (field (id "MIE") (bit_hi 3) (bit_lo 3) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.4 (MIE is reset to 0)"))
       (field (id "SPIE") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.1"))
       (field (id "MPIE") (bit_hi 7) (bit_lo 7) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.1"))
       (field (id "SPP") (bit_hi 8) (bit_lo 8) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.1"))
       (field (id "VS") (bit_hi 10) (bit_lo 9) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.7; D-GC-COMPOSITION"))
       (field (id "MPP") (bit_hi 12) (bit_lo 11) (discipline warl)
              (legalize (one-of 0 1 3)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.1"))
       (field (id "FS") (bit_hi 14) (bit_lo 13) (discipline warl)
              (legalize (one-of 0 1 2 3)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.7; D-FP-DEFER"))
       (field (id "XS") (bit_hi 16) (bit_lo 15) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.7"))
       (field (id "MPRV") (bit_hi 17) (bit_lo 17) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.4 (MPRV is reset to 0)"))
       (field (id "SUM") (bit_hi 18) (bit_lo 18) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.4"))
       (field (id "MXR") (bit_hi 19) (bit_lo 19) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.4"))
       (field (id "TVM") (bit_hi 20) (bit_lo 20) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.6"))
       (field (id "TW") (bit_hi 21) (bit_lo 21) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.6"))
       (field (id "TSR") (bit_hi 22) (bit_lo 22) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.6"))
       (field (id "wpri_31_23") (bit_hi 31) (bit_lo 23) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "UXL") (bit_hi 33) (bit_lo 32) (discipline warl)
              (legalize (read-only 2)) (reset "2") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.5; the profile's xlen field"))
       (field (id "SXL") (bit_hi 35) (bit_lo 34) (discipline warl)
              (legalize (read-only 2)) (reset "2") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.5; the profile's xlen field"))
       (field (id "SBE") (bit_hi 36) (bit_lo 36) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.5"))
       (field (id "MBE") (bit_hi 37) (bit_lo 37) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.5"))
       (field (id "GVA") (bit_hi 38) (bit_lo 38) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.6; D-NO-H"))
       (field (id "MPV") (bit_hi 39) (bit_lo 39) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.6.6; D-NO-H"))
       (field (id "wpri_62_40") (bit_hi 62) (bit_lo 40) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "SD") (bit_hi 63) (bit_lo 63) (discipline warl)
              (legalize (computed)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.1.6.7"))
       (field (id "wpri_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_2") (bit_hi 2) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4") (bit_hi 4) (bit_lo 4) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_6") (bit_hi 6) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0x0000000A00000000") (authority laboratory) (source "RVP-MACHINE §2.1.4")
              (statement "§2.1.4 fixes MIE=0 and MPRV=0 and leaves the rest UNSPECIFIED; the laboratory resets every remaining writable field to 0, so the composite is UXL=2 and SXL=2 alone standing (2 << 32 | 2 << 34).")))

  (csr (id "mtvec") (address 773) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.7")
       (field (id "BASE") (bit_hi 63) (bit_lo 2) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.7"))
       (field (id "MODE") (bit_hi 1) (bit_lo 0) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.7"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.7; §2.1.4 (UNSPECIFIED)")
              (statement "The specification leaves mtvec's reset UNSPECIFIED; the laboratory resets it to direct mode at address 0 — a harness declaration, not an architectural guarantee (the rv64i reset precedent).")))

  (csr (id "medeleg") (address 770) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.8")
       (field (id "cause_0_to_10") (bit_hi 10) (bit_lo 0) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8; the .2 brief's pinned subset"))
       (field (id "cause_11") (bit_hi 11) (bit_lo 11) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.1.8"))
       (field (id "cause_12_to_15") (bit_hi 15) (bit_lo 12) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8; the .2 brief's pinned subset"))
       (field (id "cause_16") (bit_hi 16) (bit_lo 16) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.1.8; causes.csv (0x10 double trap)"))
       (field (id "cause_17") (bit_hi 17) (bit_lo 17) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "cause_18_to_20") (bit_hi 20) (bit_lo 18) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8; the .2 brief's pinned subset"))
       (field (id "wpri_63_21") (bit_hi 63) (bit_lo 21) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.8; §2.1.4 (UNSPECIFIED)")
              (statement "Nothing delegated at reset: every trap is delivered to M-mode until M-mode software says otherwise.")))

  (csr (id "mideleg") (address 771) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.8")
       (field (id "SSIP") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8"))
       (field (id "STIP") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8"))
       (field (id "SEIP") (bit_hi 9) (bit_lo 9) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.8"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_2") (bit_hi 4) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_8_6") (bit_hi 8) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_63_10") (bit_hi 63) (bit_lo 10) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.8; §2.1.4 (UNSPECIFIED)")
              (statement "No interrupt delegated at reset. Interrupt ACCEPTANCE semantics are P4-SYSTEM.5's; this table is the storage and its discipline.")))

  (csr (id "mie") (address 772) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.9")
       (field (id "SSIE") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "MSIE") (bit_hi 3) (bit_lo 3) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.9; the profile's harts field"))
       (field (id "STIE") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "MTIE") (bit_hi 7) (bit_lo 7) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "SEIE") (bit_hi 9) (bit_lo 9) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "MEIE") (bit_hi 11) (bit_lo 11) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_2_2") (bit_hi 2) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_4") (bit_hi 4) (bit_lo 4) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_6_6") (bit_hi 6) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_8_8") (bit_hi 8) (bit_lo 8) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_10_10") (bit_hi 10) (bit_lo 10) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_63_12") (bit_hi 63) (bit_lo 12) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.9; §2.1.4 (UNSPECIFIED)")
              (statement "All interrupts disabled at reset. Enable/acceptance behaviour is P4-SYSTEM.5's.")))

  (csr (id "mip") (address 836) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.9")
       (field (id "SSIP") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "MSIP") (bit_hi 3) (bit_lo 3) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "STIP") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (computed)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9; RVP-SSTC 12.1"))
       (field (id "MTIP") (bit_hi 7) (bit_lo 7) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "SEIP") (bit_hi 9) (bit_lo 9) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "MEIP") (bit_hi 11) (bit_lo 11) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.9"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_2_2") (bit_hi 2) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_4") (bit_hi 4) (bit_lo 4) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_6_6") (bit_hi 6) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_8_8") (bit_hi 8) (bit_lo 8) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_10_10") (bit_hi 10) (bit_lo 10) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_63_12") (bit_hi 63) (bit_lo 12) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.9; §2.1.4 (UNSPECIFIED)")
              (statement "Nothing pending at reset. Pending-state behaviour is P4-SYSTEM.5's.")))

  (csr (id "mscratch") (address 832) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.13")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.13; §2.1.4 (UNSPECIFIED)")
              (statement "A read/write scratch register with no architectural fields; the laboratory resets it to 0.")))

  (csr (id "mepc") (address 833) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.14")
       (field (id "value_63_2") (bit_hi 63) (bit_lo 2) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.14"))
       (field (id "value_1") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.14; D-IALIGN-16"))
       (field (id "value_0") (bit_hi 0) (bit_lo 0) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-MACHINE §2.1.1.14"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.14; §2.1.4 (UNSPECIFIED)")
              (statement "The WLRL discipline is the specification's own term for mepc; the laboratory resets it to 0. Trap delivery writes it (the semantics language's trap-deliver).")))

  (csr (id "mcause") (address 834) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.15")
       (field (id "Interrupt") (bit_hi 63) (bit_lo 63) (discipline wlrl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.15"))
       (field (id "code_62_0") (bit_hi 62) (bit_lo 0) (discipline wlrl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.15; causes.csv"))
       (reset (value "a value indicating the cause of the reset") (authority architecture) (source "RVP-MACHINE §2.1.4")
              (statement "§2.1.4 sets mcause to the reset's cause — the one CSR whose reset is architecturally defined and non-constant; the laboratory's reset cause is 0 (power-on), recorded here so the reset is total.")))

  (csr (id "mtval") (address 835) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.16")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.16; §2.1.4 (UNSPECIFIED)")
              (statement "A read/write register with no architectural fields; the laboratory resets it to 0. Trap delivery writes it (bad address, instruction bits, or 0 per cause).")))

  (csr (id "menvcfg") (address 778) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.18")
       (field (id "STCE") (bit_hi 63) (bit_lo 63) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.18; RVP-SSTC 12.1"))
       (field (id "wpri_62_0") (bit_hi 62) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.18; D-GC-COMPOSITION"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.18; §2.1.4 (UNSPECIFIED)")
              (statement "stimecmp starts gated off: an S-mode kernel sees the M-mode timer contract until M-mode software sets STCE.")))

  (csr (id "mcounteren") (address 774) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.11")
       (field (id "CY") (bit_hi 0) (bit_lo 0) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.11"))
       (field (id "TM") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.11; RVP-SSTC 12.1"))
       (field (id "IR") (bit_hi 2) (bit_lo 2) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-MACHINE §2.1.1.11"))
       (field (id "HPM31_3") (bit_hi 31) (bit_lo 3) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-MACHINE §2.1.1.11; D-ZICNTR"))
       (field (id "wpri_63_32") (bit_hi 63) (bit_lo 32) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.11; §2.1.4 (UNSPECIFIED)")
              (statement "Counters start gated off below M: access-legality is visible from reset (the .2 acceptance's mode-matrix needs a gate that can move), and enabling is M-mode software's act. The counters keep counting while gated (§2.1.1.11); counter VALUES/rate are P4-SYSTEM.5/.9's.")))

  (csr (id "mcycle") (address 2816) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.10; RVI-ZICNTR §6.1.1")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.10; §2.1.4 (UNSPECIFIED)")
              (statement "The cycle counter, writable in M; the laboratory resets it to 0. It IS the declared virtual-time domain's storage (P4-SYSTEM.5 decision 1, authority laboratory): the domain advances ONE TICK PER STEP BOUNDARY, retired or halted — the declared rate as data, a pure function of the step index (the Zicntr §6.1 rate latitude; determinism by construction). cycle and time view it read-only.")))

  (csr (id "minstret") (address 2818) (width_bits 64) (authority architecture)
       (source "RVP-MACHINE §2.1.1.10; RVI-ZICNTR §6.1.1")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.1.10; §2.1.4 (UNSPECIFIED)")
              (statement "The instructions-retired counter, writable in M; the laboratory resets it to 0. It counts GENUINELY (P4-SYSTEM.5 decision 1): +1 per retired instruction — a step that delivers a trap, decodes reserved (no instruction), or halts does not increment; time advances regardless.")))

  ;; ---- supervisor level ----------------------------------------------------------------------
  (csr (id "sstatus") (address 256) (width_bits 64) (view_of "mstatus") (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.1")
       (field (id "SIE") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "SPIE") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "SPP") (bit_hi 8) (bit_lo 8) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "VS") (bit_hi 10) (bit_lo 9) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "FS") (bit_hi 14) (bit_lo 13) (discipline warl)
              (legalize (one-of 0 1 2 3)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1; D-FP-DEFER"))
       (field (id "XS") (bit_hi 16) (bit_lo 15) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "SUM") (bit_hi 18) (bit_lo 18) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1.2"))
       (field (id "MXR") (bit_hi 19) (bit_lo 19) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1.2"))
       (field (id "UXL") (bit_hi 33) (bit_lo 32) (discipline warl)
              (legalize (read-only 2)) (reset "2") (reset_authority architecture)
              (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.1.3"))
       (field (id "SD") (bit_hi 63) (bit_lo 63) (discipline warl)
              (legalize (computed)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.1"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_2") (bit_hi 4) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_7_6") (bit_hi 7) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_12_11") (bit_hi 12) (bit_lo 11) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_17_17") (bit_hi 17) (bit_lo 17) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_31_20") (bit_hi 31) (bit_lo 20) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_62_34") (bit_hi 62) (bit_lo 34) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "the mstatus subset, per its fields") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.1")
              (statement "A view of mstatus: no storage of its own, so no independent reset — the underlying mstatus fields carry it. The supervisor chapter defines sstatus as exactly the subset of mstatus fields visible to S-mode.")))

  (csr (id "stvec") (address 261) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.2")
       (field (id "BASE") (bit_hi 63) (bit_lo 2) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.2"))
       (field (id "MODE") (bit_hi 1) (bit_lo 0) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.2"))
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.2; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The laboratory resets stvec to direct mode at address 0, as mtvec.")))

  (csr (id "sscratch") (address 320) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.6")
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.6; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "A read/write scratch register with no architectural fields; the laboratory resets it to 0.")))

  (csr (id "sepc") (address 321) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.7")
       (field (id "value_63_2") (bit_hi 63) (bit_lo 2) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.7"))
       (field (id "value_1") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.7; D-IALIGN-16"))
       (field (id "value_0") (bit_hi 0) (bit_lo 0) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.7"))
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.7; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "As mepc: the laboratory resets it to 0; trap delivery writes it.")))

  (csr (id "scause") (address 322) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.8")
       (field (id "Interrupt") (bit_hi 63) (bit_lo 63) (discipline wlrl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.8"))
       (field (id "code_62_0") (bit_hi 62) (bit_lo 0) (discipline wlrl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.8; causes.csv"))
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.8; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The laboratory resets scause to 0; trap delivery writes it.")))

  (csr (id "stval") (address 323) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.9")
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.9; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "A read/write register with no architectural fields; the laboratory resets it to 0. Trap delivery writes it.")))

  (csr (id "sie") (address 260) (width_bits 64) (view_of "mie") (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.3")
       (field (id "SSIE") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3"))
       (field (id "STIE") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3"))
       (field (id "SEIE") (bit_hi 9) (bit_lo 9) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_2") (bit_hi 4) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_8_6") (bit_hi 8) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_63_10") (bit_hi 63) (bit_lo 10) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "the mie subset, per its fields") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.3")
              (statement "A view of mie restricted to the supervisor bits; no storage, no independent reset.")))

  (csr (id "sip") (address 324) (width_bits 64) (view_of "mip") (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.3")
       (field (id "SSIP") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3; RVP-MACHINE §2.1.1.9"))
       (field (id "STIP") (bit_hi 5) (bit_lo 5) (discipline warl)
              (legalize (computed)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3; RVP-SSTC 12.1"))
       (field (id "SEIP") (bit_hi 9) (bit_lo 9) (discipline warl)
              (legalize (computed)) (reset "0") (reset_authority architecture)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.3; RVP-MACHINE §2.1.1.9"))
       (field (id "wpri_0_0") (bit_hi 0) (bit_lo 0) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_4_2") (bit_hi 4) (bit_lo 2) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_8_6") (bit_hi 8) (bit_lo 6) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (field (id "wpri_63_10") (bit_hi 63) (bit_lo 10) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "the mip subset, per its fields") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.3")
              (statement "A view of mip restricted to the supervisor bits; no storage, no independent reset.")))

  (csr (id "scounteren") (address 262) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.5")
       (field (id "CY") (bit_hi 0) (bit_lo 0) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.5"))
       (field (id "TM") (bit_hi 1) (bit_lo 1) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.5"))
       (field (id "IR") (bit_hi 2) (bit_lo 2) (discipline warl)
              (legalize (one-of 0 1)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.5"))
       (field (id "HPM31_3") (bit_hi 31) (bit_lo 3) (discipline warl)
              (legalize (read-only 0)) (reset "0") (reset_authority architecture)
              (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.5; D-ZICNTR"))
       (field (id "wpri_63_32") (bit_hi 63) (bit_lo 32) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.5; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "U-mode counter access starts gated off, as mcounteren; U sees a counter exactly when M and S both allow it.")))

  (csr (id "satp") (address 384) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.11")
       (field (id "MODE") (bit_hi 63) (bit_lo 60) (discipline warl)
              (legalize (one-of 0 8)) (reset "0") (reset_authority laboratory)
              (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.11; D-SV39"))
       (field (id "ASID") (bit_hi 59) (bit_lo 44) (discipline wlrl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.11"))
       (field (id "PPN") (bit_hi 43) (bit_lo 0) (discipline wlrl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-SUPERVISOR §11.1.1.11"))
       (reset (value "0") (authority laboratory) (source "RVP-SUPERVISOR §11.1.1.11; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "Bare at reset: no translation until S-mode software chooses Sv39. satp's BEHAVIOUR (the walk, A/D, ASIDs) is P4-SYSTEM.3's; only its storage, discipline and access permissions (TVM) are .2's.")))

  (csr (id "stimecmp") (address 333) (width_bits 64) (authority architecture)
       (source "RVP-SUPERVISOR §11.1.1.12; RVP-SSTC 12.1")
       (reset (value "0") (authority laboratory) (source "RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The supervisor timer-compare register, 64-bit on RV64 (§11.1.1.12); the laboratory resets it to 0. Its access gates (mcounteren.TM, menvcfg.STCE) live in the uniform CSR permission model; the interrupt it posts is P4-SYSTEM.5's.")))

  ;; ---- the unprivileged counter views (Zicntr) ------------------------------------------------
  (csr (id "cycle") (address 3072) (width_bits 64) (view_of "mcycle") (authority architecture)
       (source "RVI-ZICNTR §6.1.1")
       (reset (value "mcycle's") (authority laboratory) (source "RVI-ZICNTR §6.1.1")
              (statement "A read-only shadow of mcycle (csr[11:10]=0b11 makes every write an illegal instruction — the uniform permission model's); no storage, no independent reset. Access gating: mcounteren.CY then scounteren.CY.")))

  (csr (id "time") (address 3073) (width_bits 64) (view_of "mcycle") (authority architecture)
       (source "RVI-ZICNTR §6.1.1")
       (reset (value "mcycle's") (authority laboratory) (source "RVI-ZICNTR §6.1.1")
              (statement "A read-only view of the declared virtual-time domain — mcycle's storage ('cycle count might represent a valid implementation of RDTIME', Zicntr §6.1); no storage, no independent reset. The domain IS the environment's time supply (P4-SYSTEM.5 decision 1; the 'environment's mtime' phrasing refined, not contradicted — the contract wording for the supply is .9's). Access gating: mcounteren.TM then scounteren.TM.")))

  (csr (id "instret") (address 3074) (width_bits 64) (view_of "minstret") (authority architecture)
       (source "RVI-ZICNTR §6.1.1")
       (reset (value "minstret's") (authority laboratory) (source "RVI-ZICNTR §6.1.1")
              (statement "A read-only shadow of minstret; no storage, no independent reset. Access gating: mcounteren.IR then scounteren.IR.")))

  ;; ---- the floating-point CSRs (semantics landed at P4-SYSTEM.7 slice b) ----------------------
  (csr (id "fflags") (address 1) (width_bits 64) (authority architecture)
       (source "RVI-F §20.1.1 — the FP accrued-flags register")
       (field (id "flags_4_0") (bit_hi 4) (bit_lo 0) (discipline warl)
              (legalize (any)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVI-F §20.1.1"))
       (field (id "wpri_63_5") (bit_hi 63) (bit_lo 5) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVI-F §20.1.1; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The accrued exception flags (NV/DZ/OF/UF/NX at bits 4..0): STICKY — the FP instructions accrue by OR-ing (Sail's accrue_fflags shape; the accrual lands with the F bind, slice c) and never clear themselves; software clears with an explicit write. Access is gated by mstatus.FS: at FS=Off the access is illegal-instruction (the Off-state sentence, RVP-MACHINE §2.1.1.6.7; Sail 0.14 fdext_control.sail).")))

  (csr (id "frm") (address 2) (width_bits 64) (authority architecture)
       (source "RVI-F §20.1.1 — the FP rounding-mode register")
       (field (id "frm_2_0") (bit_hi 2) (bit_lo 0) (discipline warl)
              (legalize (one-of 0 1 2 3 4)) (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVI-F §20.1.1"))
       (field (id "wpri_63_3") (bit_hi 63) (bit_lo 3) (discipline wpri)
              (reset "0") (reset_authority laboratory)
              (authority architecture) (source "RVP-CSR §1.1.3.1"))
       (reset (value "0") (authority laboratory) (source "RVI-F §20.1.1; RVP-MACHINE §2.1.4 (UNSPECIFIED)")
              (statement "The dynamic rounding mode: WARL one-of 0..4 (RNE/RTZ/RDN/RUP/RMM) — an illegal write retains the old value (the laboratory's WARL choice; Sail stores anything, a named difference for slice e's match). An instruction rm field of 111 (dyn) resolves to frm; rm 101/110 are reserved — the instruction is illegal (RVI-F §20.1.1's rm table; the resolution is the semantics layer's, slice c). Access FS-gated as fflags.")))

  (csr (id "fcsr") (address 3) (width_bits 64) (view_of "fflags, frm") (authority architecture)
       (source "RVI-F §20.1.1 — fflags and frm as one register")
       (reset (value "fflags' and frm's") (authority laboratory) (source "RVI-F §20.1.1")
              (statement "The combined view of fflags (bits 4:0) and frm (bits 7:5); no storage, no independent reset. A MULTI-owner view: the read composes the owners' non-WPRI field bits low-to-high in list order and a write splits back into the owners under each owner's own field table (the engine's composition rule, P4-SYSTEM.7 slice b — the single-owner resolution read 0 and refused writes, measured pre-slice). Access FS-gated as fflags.")))

  ;; ---- the re-earned census (SEM-08) ----------------------------------------------------------
  (hidden_state_census
    (question "Is there any state, not listed above, that can influence a future supported observation? (SEM-08, catalog C02 — re-earned for the privileged state)")
    (answer "No — for this stage of the profile, with every candidate below accounted for and the later slices that reopen them named.")
      (candidates (checked (candidate "the 33 CSRs of D-CSR-SET") (present true)
               (why "declared above, each with its per-field discipline table; the privilege stack (xIE/xPIE/xPP) is mstatus FIELDS, architected state, not hidden state")))
      (candidates (checked (candidate "the current privilege mode") (present true)
               (why "declared as hart state above — it changes on trap delivery and xret and is readable nowhere as a register; without it the mode-matrix corpus could observe nothing")))
      (candidates (checked (candidate "reservation set (LR/SC)") (present true)
               (why "answered by P4-SYSTEM.4 slice (c): one reservation — (physical address, width, valid) of the most recent LR, the minimal conformant reservation set (exactly the accessed word's/doubleword's bytes, RVI-A §12.1.2), keyed on the PHYSICAL address (the aliasing latitude resolved to exact physical match, authority laboratory). Invalidation is exactly the spec's one-hart set: any LR replaces; any SC — success or failure, any address — clears; a trap does NOT invalidate (the SC's own trap included — the trap path is neither success nor failure). The deterministic SC policy (authority laboratory, decision 3): SC succeeds iff the reservation is valid ∧ physical address equal ∧ width equal, writing rs2's value and rd←0; otherwise it fails with rd←1 (the 'unspecified failure' code), writing nothing; it NEVER spuriously fails — one legal point of the architectural nondeterminism, chosen so exact-value expectations stay derivable (EVD-05). Misaligned atomics take the access-fault family by kind (5 for LR, 7 for SC/AMO — decision 6, reference-matched to the override's declared PMAs, the exception table's kind mapping). The reservation is a pure function of the hart's own history — invalid at reset, changed only by the hart's own LR/SC — so cold-reset re-execution stays trace-identical and a cold-restored (invalid) reservation is always a legal state")))
      (candidates (checked (candidate "floating-point registers f0-f31 and the fcsr behaviour") (present true)
               (why "answered by P4-SYSTEM.7 slice (b) after slice (a)'s qualification (SEMULITH-P4-0039, rustc_apfloat): the file is modelled — 32 x 64-bit (FLEN=64 with D, the LP64D ABI), declared above with its laboratory reset; mstatus.FS gates the FP instructions AND the fflags/frm/fcsr CSRs (four-state FS, reset 0 = Off, Dirty on any FP state write — Sail 0.14's dirty_fd_context measured; SD is the computed summary and follows); fflags is the sticky accrued-flags register (software-clearable); frm is WARL one-of 0..4 with dyn/reserved-rm resolution stated; fcsr is the two-owner VIEW, composed by the engine from fflags[4:0] and frm[2:0] (the pre-slice single-owner resolution read 0 and refused writes — measured, fixed at root). Observation stays through the x-registers (decision 8): the file itself is never an expectations-vocabulary item")))
      (candidates (checked (candidate "environment state (mtime, interrupt sources, the time register's value)") (present true)
               (why "answered by P4-SYSTEM.5 slice (a) for the COUNTER-PROGRESS part: the laboratory declares the virtual-time domain — one tick per step boundary, retired or halted (authority laboratory, Zicntr §6.1's rate latitude; the domain IS the environment's supply, the contract wording .9's) — mcycle is the domain's storage, time views it, minstret counts genuinely; and by slice (b) for the PENDING/SOURCE-EVALUATION part (the (a)(b)(c) taken-rule with the global rule, the delegation mask and the fixed priorities, interrupt-caused delivery honoring both xtvec.MODEs). mtime/mtimecmp and the interrupt controllers stay memory-mapped ENVIRONMENT state, not CSRs (the .9 contract)")))
      (candidates (checked (candidate "PMP configuration") (present false)
               (why "PMP is excluded at v0 (D-NO-PMP)")))
      (candidates (checked (candidate "hypervisor state") (present false)
               (why "the hypervisor extension is excluded (D-NO-H)")))
      (candidates (checked (candidate "vector state (vtype, vl, vstart)") (present false)
               (why "V is not in this profile")))
      (candidates (checked (candidate "instruction-fetch cache state") (present false)
               (why "the model re-reads memory on every fetch (D-CODE-VISIBILITY) — a laboratory choice, not an absence of the possibility: Zifencei is declared AND bound (P4-SYSTEM.6 slice b), and the chapter's own latitude permits a caching hart regardless (visibility is guaranteed only after a FENCE.I), so the re-read choice stays laboratory policy and FENCE.I's nop is this unit's sanctioned implementation of the synchronization (the coherent/uncached-RAM latitude — nothing to flush). Re-answered in place at the bind, replacing rv64i's verbatim recording, which argued the choice from the extension's absence (true of rv64i, stale here)")))
      (candidates (checked (candidate "pending or partially committed effects") (present false)
               (why "at this stage every instruction completes or faults as a unit; fault priority and partial commits are P4-SYSTEM.8's, which reopens this candidate")))
      (candidates (checked (candidate "address-translation caches (TLBs)") (present true)
               (why "answered by P4-SYSTEM.3 slice (d): a minimal fully-specified TLB — 4 entries, fully-associative, FIFO replacement, ASID-tagged at ASIDLEN 16, keyed by 4 KiB page, G-bit entries retained across per-ASID and per-address+ASID fences (authority laboratory; the cache is a pure function of the hart's own history, so cold-reset re-execution stays trace-identical and a cold-restored cache is always a legal state)")))
      (candidates (checked (candidate "hart wait state (ACTIVE/WAITING)") (present true)
               (why "answered by P4-SYSTEM.5 slice (c): one hart-state bit — ACTIVE or WAITING (Sail 0.14's HART_WAITING precedent), cold-ACTIVE at reset. A legal WFI ENTERS waiting (the nop latitude recorded-not-taken — taking it would leave the leaf's acceptance untestable); while WAITING a step retires nothing, issues no fetch, advances the virtual-time domain one tick, and the step's head evaluates the wake — resume on a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg (RVP-MACHINE §2.1.3.3's musts); on resume the taken-rule decides trap (xepc = the WFI's pc + 4) or pc + 4 continuation. The bit is a pure function of the hart's own history — changed only by the hart's own WFI/wake — so cold-reset re-execution stays trace-identical (the TLB/reservation determinism argument)")))
    (consequence "A complete snapshot for this stage is the integer file, pc, memory, the current mode, and the 33 CSRs' storage (mstatus/mie/mip once — views carry none). Each later slice reopens its named candidate: .3 translation state, .4 the reservation, .5 interrupt/counter progress, .7 the FP file, .8 partial effects, .9 the environment contract.")))
