;; d-fs-off.expected.sexp — the expected observations for `d-fs-off.s` (P4-SYSTEM.7,
;; the floating-point corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .7 brief's declared FP-state rules by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py d-fs-off.expected.sexp schema/expectations.sexp

(expectations (program "d-fs-off.s") (entry "0x0000000080000000") (instructions 52)
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "x1 holds this instruction's own address.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 68") (writes (write (reg "x1") (value "0x0000000080000044")))
    (derivation "the trap handler sits at entry + 0x44 — after the 17-instruction main body.") (source "RVI-RV32I §1.1.4"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec <- the handler.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "addi x6, x0, 3") (writes (write (reg "x6") (value "0x0000000000000003")))
    (derivation "an integer to convert.") (source "RVI-RV32I §1.1.4"))
  (step (n 4) (insn "fld f1, x0, 0") (writes)
    (derivation "FS=Off (reset): illegal-instruction — the load is never attempted (x0+0 is outside the region, and still cause 2, not 5).") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 5) (insn "csrrs x29, mcause, x0") (writes (write (reg "x29") (value "0x0000000000000002")))
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 6) (insn "csrrs x30, mepc, x0") (writes (write (reg "x30") (value "0x0000000080000010")))
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 7) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x0000000080000014")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 8) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 9) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 10) (insn "fadd.d f2, f1, f1, 0") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 11) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 12) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 13) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x0000000080000018")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 14) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 16) (insn "fmv.x.d x7, f1") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 17) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 18) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 19) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x000000008000001c")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 20) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 21) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 22) (insn "fmv.d.x f3, x6") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 23) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 24) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 25) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x0000000080000020")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 26) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 27) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 28) (insn "fcvt.d.w f4, x6, 0") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 29) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 30) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 31) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x0000000080000024")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 32) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 33) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 34) (insn "fcvt.s.d f5, f1, 0") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 35) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 36) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 37) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x0000000080000028")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 38) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 39) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 40) (insn "fcvt.d.s f5, f1, 0") (writes)
    (derivation "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 41) (insn "csrrs x29, mcause, x0") (writes)
    (derivation "the handler: the cause.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 42) (insn "csrrs x30, mepc, x0") (writes)
    (derivation "mepc is the trapping instruction's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 43) (insn "addi x30, x30, 4") (writes (write (reg "x30") (value "0x000000008000002c")))
    (derivation "step past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 44) (insn "csrrw x0, mepc, x30") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 45) (insn "mret") (writes)
    (derivation "back to M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 46) (insn "addi x31, x0, 1") (writes (write (reg "x31") (value "0x0000000000000001")))
    (derivation "the FS=Initial pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 47) (insn "slli x31, x31, 13") (writes (write (reg "x31") (value "0x0000000000002000")))
    (derivation "1 << 13 — mstatus.FS's low bit.") (source "RVP-CSR (the mstatus field table)"))
  (step (n 48) (insn "csrrs x0, mstatus, x31") (writes)
    (derivation "FS := Initial: the floating-point state is enabled before any D instruction.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 49) (insn "fcvt.d.w f4, x6, 0") (writes)
    (derivation "fcvt.d.w (RNE): 0x4008000000000000; flags none.") (source "RVI-D §21.1.5"))
  (step (n 50) (insn "fmv.x.d x9, f4") (writes (write (reg "x9") (value "0x4008000000000000")))
    (derivation "fmv.x.d: f4's 64 bits, unmodified: x9 = 0x4008000000000000.") (source "RVI-D §21.1.5"))
  (step (n 51) (insn "csrrs x10, mstatus, x0") (writes (write (reg "x10") (value "0x8000000a00006080")))
    (derivation "FS=Dirty with SD — the conversion wrote an f-register.") (source "RVP-MACHINE §2.1.1.6.7 #|end"))
)
