;; fp-fs-off.expected.sexp — the expected observations for `fp-fs-off.s` (P4-SYSTEM.7,
;; the floating-point corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .7 brief's declared FP-state rules by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py fp-fs-off.expected.sexp schema/expectations.sexp

(expectations (program "fp-fs-off.s") (entry "0x0000000080000000") (instructions 40)
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "x1 holds this instruction's own address (entry + 0x0).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 80") (writes (write (reg "x1") (value "0x0000000080000050")))
    (derivation "the trap handler sits at entry + 0x50.") (source "RVI-RV32I §1.1.4"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler; rd=x0 discards the old value.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "csrrs x5, fflags, x0") (writes)
    (derivation "FS resets Off (the laboratory's reset row): the fflags access is illegal-instruction — cause 2, xtval the instruction word, mepc this instruction (entry+0x0C).") (source "RVP-MACHINE §2.1.1.6.7 (the Off-state sentence); RVI-F §20.1.2"))
  (step (n 4) (insn "csrrs x15, mcause, x0") (writes (write (reg "x15") (value "0x0000000000000002")))
    (derivation "the handler: cause 2 (illegal instruction).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 5) (insn "csrrs x16, mepc, x0") (writes (write (reg "x16") (value "0x000000008000000c")))
    (derivation "mepc is the faulting access's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 6) (insn "addi x16, x16, 4") (writes (write (reg "x16") (value "0x0000000080000010")))
    (derivation "step mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 7) (insn "csrrw x0, mepc, x16") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 8) (insn "mret") (writes)
    (derivation "MPP was set to M by the trap, so the return lands back in M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 9) (insn "csrrs x6, frm, x0") (writes)
    (derivation "FS still Off: the frm access traps identically (mepc entry+0x10).") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 10) (insn "csrrs x15, mcause, x0") (writes)
    (derivation "the handler: cause 2 (illegal instruction).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 11) (insn "csrrs x16, mepc, x0") (writes)
    (derivation "mepc is the faulting access's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 12) (insn "addi x16, x16, 4") (writes (write (reg "x16") (value "0x0000000080000014")))
    (derivation "step mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 13) (insn "csrrw x0, mepc, x16") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 14) (insn "mret") (writes)
    (derivation "MPP was set to M by the trap, so the return lands back in M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 15) (insn "csrrs x7, fcsr, x0") (writes)
    (derivation "and fcsr (mepc entry+0x14) — the gate covers all three FP CSRs.") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 16) (insn "csrrs x15, mcause, x0") (writes)
    (derivation "the handler: cause 2 (illegal instruction).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 17) (insn "csrrs x16, mepc, x0") (writes)
    (derivation "mepc is the faulting access's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 18) (insn "addi x16, x16, 4") (writes (write (reg "x16") (value "0x0000000080000018")))
    (derivation "step mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 19) (insn "csrrw x0, mepc, x16") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 20) (insn "mret") (writes)
    (derivation "MPP was set to M by the trap, so the return lands back in M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 21) (insn "addi x8, x0, 1") (writes (write (reg "x8") (value "0x0000000000000001")))
    (derivation "the FS=Initial pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 22) (insn "slli x8, x8, 13") (writes (write (reg "x8") (value "0x0000000000002000")))
    (derivation "1 << 13 is the FS field's low bit (mstatus[14:13]).") (source "RVP-CSR (the mstatus field table)"))
  (step (n 23) (insn "csrrs x0, mstatus, x8") (writes)
    (derivation "set FS=Initial; rd=x0 discards the old mstatus.") (source "RVI-ZICSR §5.1.1"))
  (step (n 24) (insn "csrrs x9, fflags, x0") (writes)
    (derivation "legal now: fflags reads its reset 0 (x9 already holds 0 — the step's trap-free passage is the observation).") (source "RVI-F §20.1.2"))
  (step (n 25) (insn "csrrs x10, frm, x0") (writes)
    (derivation "legal: frm reads 0 (RNE).") (source "RVI-F §20.1.2"))
  (step (n 26) (insn "csrrs x11, fcsr, x0") (writes)
    (derivation "legal: the composed view reads 0.") (source "RVI-F §20.1.2"))
  (step (n 27) (insn "csrrs x12, mstatus, x0") (writes (write (reg "x12") (value "0x0000000a00002080")))
    (derivation "x12 observes FS=Initial with SD=0 (MPIE=1 is the trap returns' stack).") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 28) (insn "addi x17, x0, 3") (writes (write (reg "x17") (value "0x0000000000000003")))
    (derivation "the FS=Dirty pattern.") (source "RVI-RV32I §1.1.4"))
  (step (n 29) (insn "slli x17, x17, 13") (writes (write (reg "x17") (value "0x0000000000006000")))
    (derivation "3 << 13.") (source "RVP-CSR (the mstatus field table)"))
  (step (n 30) (insn "csrrs x0, mstatus, x17") (writes)
    (derivation "set FS=Dirty.") (source "RVI-ZICSR §5.1.1"))
  (step (n 31) (insn "csrrs x13, mstatus, x0") (writes (write (reg "x13") (value "0x8000000a00006080")))
    (derivation "x13 observes FS=Dirty with SD computed 1 — SD reacts to the FS write.") (source "RVP-MACHINE §2.1.1.6.7 (SD)"))
  (step (n 32) (insn "csrrc x0, mstatus, x17") (writes)
    (derivation "clear both FS bits — FS=Off again.") (source "RVI-ZICSR §5.1.1"))
  (step (n 33) (insn "csrrs x14, fflags, x0") (writes)
    (derivation "the gate closes: fflags at FS=Off traps (mepc entry+0x48).") (source "RVP-MACHINE §2.1.1.6.7"))
  (step (n 34) (insn "csrrs x15, mcause, x0") (writes)
    (derivation "the handler: cause 2 (illegal instruction).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 35) (insn "csrrs x16, mepc, x0") (writes (write (reg "x16") (value "0x0000000080000048")))
    (derivation "mepc is the faulting access's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 36) (insn "addi x16, x16, 4") (writes (write (reg "x16") (value "0x000000008000004c")))
    (derivation "step mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 37) (insn "csrrw x0, mepc, x16") (writes)
    (derivation "mepc <- the next instruction.") (source "RVI-ZICSR §5.1.1"))
  (step (n 38) (insn "mret") (writes)
    (derivation "MPP was set to M by the trap, so the return lands back in M at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 39) (insn "csrrs x19, mstatus, x0") (writes (write (reg "x19") (value "0x0000000a00000080")))
    (derivation "x19 observes FS=Off with SD=0 — the gate's pre- and post-state both readable.") (source "RVP-MACHINE §2.1.1.6.7 #|end"))
)
