;; i-nest.expected.sexp — the expected observations for `i-nest.s` (P4-SYSTEM.5
;; slice b, the interrupts corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .5 brief's declared delivery rule by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py i-nest.expected.sexp schema/expectations.sexp

(expectations (program "i-nest.s") (entry "0x0000000080000000") (instructions 31) (fetches 29)
  (never_written "x28")
  (never_written "x29")
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "x1 = this instruction's own address.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 45") (writes (write (reg "x1") (value "0x000000008000002d")))
    (derivation "mtvec's BASE rides 44 bytes in; MODE adds 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 2) (insn "ori x1, x1, 1") (writes)
    (derivation "MODE = Vectored (the two handlers get their own slots).") (source "RVI-RV32I §1.1.4"))
  (step (n 3) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec = BASE") (source "1. | RVI-ZICSR §5.1.1"))
  (step (n 4) (insn "addi x2, x0, 2") (writes (write (reg "x2") (value "0x0000000000000002")))
    (derivation "the SSIP bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 5) (insn "csrrs x0, mip, x2") (writes)
    (derivation "SSIP <- 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 6) (insn "csrrs x0, mie, x2") (writes)
    (derivation "SSIE <- 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 7) (insn "addi x6, x0, 8") (writes (write (reg "x6") (value "0x0000000000000008")))
    (derivation "the MIE bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 8) (insn "csrrs x0, mstatus, x6") (writes)
    (derivation "MIE <- 1.") (source "RVP-MACHINE §2.1.1.6.1"))
  (step (n 9) (insn "addi x7, x0, 0") (writes)
    (derivation "the pending evaluation takes the SSI interrupt in M: xcause carries the Interrupt bit with cause 1, xepc is the un-fetched pc (interrupts are taken BETWEEN instructions), and pc moves to the vector as declared (no register observation — the handler's csrr reads below are the evidence).") (source "RVP-MACHINE §2.1.1.9; RVP-SUPERVISOR §11.1.1.3; the .5 brief's decision 3"))
  (step (n 10) (insn "jal x0, ssi_handler") (writes)
    (derivation "BASE+4 slot: the vectored SSI delivery's landing.") (source "RVP-MACHINE §2.1.1.7"))
  (step (n 11) (insn "csrrs x11, mcause, x0") (writes (write (reg "x11") (value "0x8000000000000001")))
    (derivation "handler A observes the Interrupt bit with cause 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 12) (insn "csrrs x12, mstatus, x0") (writes (write (reg "x12") (value "0x0000000a00001880")))
    (derivation "the push: MPIE <- 1, MIE <- 0 (the handler is quiet).") (source "RVP-MACHINE §2.1.1.6.1"))
  (step (n 13) (insn "csrrc x0, mip, x2") (writes)
    (derivation "clear SSIP FIRST — otherwise the resume head after the nested return re-fires it.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 14) (insn "csrrs x14, mepc, x0") (writes (write (reg "x14") (value "0x0000000080000024")))
    (derivation "save the outer resume address in a REGISTER before re-enabling — the nested delivery clobbers mepc.") (source "RVP-MACHINE §2.1.1.14"))
  (step (n 15) (insn "addi x14, x14, 4") (writes (write (reg "x14") (value "0x0000000080000028")))
    (derivation "step it past the delivery placeholder.") (source "RVI-RV32I §1.1.4"))
  (step (n 16) (insn "addi x8, x0, 1") (writes (write (reg "x8") (value "0x0000000000000001")))
    (derivation "raw material for SEIP's bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 17) (insn "slli x8, x8, 9") (writes (write (reg "x8") (value "0x0000000000000200")))
    (derivation "x8 = 1 << 9.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 18) (insn "csrrs x0, mip, x8") (writes)
    (derivation "SEIP <- 1: a second cause is posted from inside the handler.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 19) (insn "csrrs x0, mie, x8") (writes)
    (derivation "SEIE <- 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 20) (insn "csrrs x0, mstatus, x6") (writes)
    (derivation "MIE <- 1 again: the next boundary takes SEI NESTED inside A.") (source "RVP-MACHINE §2.1.1.6.1"))
  (step (n 21) (insn "csrrw x0, mepc, x14") (writes)
    (derivation "the pending evaluation takes the SEI interrupt in M: xcause carries the Interrupt bit with cause 9, xepc is the un-fetched pc (interrupts are taken BETWEEN instructions), and pc moves to the vector as declared (no register observation — the handler's csrr reads below are the evidence).") (source "RVP-MACHINE §2.1.1.9; RVP-SUPERVISOR §11.1.1.3; the .5 brief's decision 3"))
  (step (n 22) (insn "jal x0, sei_handler") (writes)
    (derivation "BASE+36 slot: the vectored SEI delivery's landing.") (source "RVP-MACHINE §2.1.1.7"))
  (step (n 23) (insn "csrrs x21, mcause, x0") (writes (write (reg "x21") (value "0x8000000000000009")))
    (derivation "handler B (nested) observes the Interrupt bit with cause 9.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 24) (insn "csrrs x22, mstatus, x0") (writes (write (reg "x22") (value "0x0000000a00001880")))
    (derivation "the second push: MPIE <- the MIE software set inside A.") (source "RVP-MACHINE §2.1.1.6.1"))
  (step (n 25) (insn "csrrc x0, mip, x8") (writes)
    (derivation "clear SEIP before returning.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 26) (insn "csrrs x23, mepc, x0") (writes (write (reg "x23") (value "0x000000008000007c")))
    (derivation "B's mepc is the instruction A was about to run.") (source "RVP-MACHINE §2.1.1.14"))
  (step (n 27) (insn "mret") (writes)
    (derivation "the NESTED mret: pops back into A with MIE <- MPIE restored.") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 28) (insn "csrrw x0, mepc, x14") (writes)
    (derivation "the nested mret lands here: restore the stepped outer mepc.") (source "RVI-ZICSR §5.1.1"))
  (step (n 29) (insn "mret") (writes)
    (derivation "the OUTER mret: the stack pops per MPP and pc <- the restored mepc — the landing marker.") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 30) (insn "addi x9, x0, 42") (writes (write (reg "x9") (value "0x000000000000002a")))
    (derivation "the landing marker: the outer mret returns here.") (source "RVI-RV32I §1.1.4 #|end"))
)
