;; mm-csr-legality-u.expected.sexp — the expected observations for `mm-csr-legality-u.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus). EVD-05: every value below was derived from the
;; pinned chapters BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-csr-legality-u.expected.sexp schema/expectations.sexp

(expectations (program "mm-csr-legality-u.s") (entry "0x0000000080000000") (instructions 16)
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "auipc writes the instruction's own address (entry + 0x0).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 116") (writes (write (reg "x1") (value "0x0000000080000074")))
    (derivation "the delta 116 from the auipc's pc lands on the trap handler's first instruction at entry+0x74.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler; rd=x0 discards the old value.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "csrrw x0, mstatus, x0") (writes)
    (derivation "mstatus <- 0 clears MPP to U; UXL/SXL are held by the WARL rule.") (source "RVP-CSR (mstatus field table)"))
  (step (n 4) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000010")))
    (derivation "auipc writes the instruction's own address (entry + 0x10).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 5) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x0000000080000030")))
    (derivation "the delta 32 from the auipc's pc lands on the U-mode cell at entry+0x30.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 6) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- the U-mode cell's address.") (source "RVI-ZICSR §5.1.1"))
  (step (n 7) (insn "mret") (writes)
    (derivation "mret with MPP=U drops to U-mode at mepc.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 8) (insn "addi x5, x0, 42") (writes (write (reg "x5") (value "0x000000000000002a")))
    (derivation "an ordinary U-mode write: base arithmetic is privilege-agnostic.") (source "RVI-RV32I §1.1.4"))
  (step (n 9) (insn "csrrw x0, mscratch, x5") (writes)
    (derivation "in U-mode, mscratch is an M-level CSR: the access traps illegal-instruction with mtval = the instruction word 0x34029073.") (source "RVP-CSR §2.1 (CSR accessibility by privilege)"))
  (step (n 10) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "the handler observes cause 2.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 11) (insn "csrrs x9, mtval, x0") (writes (write (reg "x9") (value "0x0000000034029073")))
    (derivation "for an illegal-instruction trap, mtval is the faulting instruction's word.") (source "RVP-MACHINE §2.1.3.1 (mtval)"))
  (step (n 12) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x0000000080000034")))
    (derivation "mepc is the trapped csrrw's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 13) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x0000000080000038")))
    (derivation "the handler steps mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 14) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x38.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "mret") (writes)
    (derivation "the trap recorded MPP=U, so the return lands back in U at entry+0x38.") (source "RVP-INSNS §3.3.2 (mret)")))
