;; mm-csr-legality-s.expected.sexp — the expected observations for `mm-csr-legality-s.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus). EVD-05: every value below was derived from the
;; pinned chapters BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-csr-legality-s.expected.sexp schema/expectations.sexp

(expectations (program "mm-csr-legality-s.s") (entry "0x0000000080000000") (instructions 17)
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "auipc writes the instruction's own address (entry + 0x0).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 120") (writes (write (reg "x1") (value "0x0000000080000078")))
    (derivation "the delta 120 from the auipc's pc lands on the trap handler's first instruction at entry+0x78.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler; rd=x0 discards the old value.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "addi x3, x0, 1") (writes (write (reg "x3") (value "0x0000000000000001")))
    (derivation "the MPP=S pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 4) (insn "slli x3, x3, 11") (writes (write (reg "x3") (value "0x0000000000000800")))
    (derivation "1 << 11 is the MPP field's S encoding.") (source "RVP-CSR (mstatus.MPP is bits 12:11)"))
  (step (n 5) (insn "csrrw x0, mstatus, x3") (writes)
    (derivation "mstatus <- 0x800: MPP=S; UXL/SXL are held by the WARL rule.") (source "RVP-CSR (mstatus field table)"))
  (step (n 6) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000018")))
    (derivation "auipc writes the instruction's own address (entry + 0x18).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 7) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x0000000080000038")))
    (derivation "the delta 32 from the auipc's pc lands on the S-mode cell at entry+0x38.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 8) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- the S-mode cell's address.") (source "RVI-ZICSR §5.1.1"))
  (step (n 9) (insn "mret") (writes)
    (derivation "mret with MPP=S drops to S-mode at mepc; MPP becomes U, MPIE becomes 1.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 10) (insn "csrrs x5, mstatus, x0") (writes)
    (derivation "in S-mode, mstatus is an M-level CSR: the access traps illegal-instruction; mepc is the faulting instruction's own address (entry+0x38), mtval its word.") (source "RVP-CSR §2.1 (CSR accessibility by privilege)"))
  (step (n 11) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "the handler observes cause 2 (illegal instruction).") (source "RVP-MACHINE §2.1.3.1 (mcause vocabulary)"))
  (step (n 12) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x0000000080000038")))
    (derivation "mepc is the trapped csrrs's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 13) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x000000008000003c")))
    (derivation "the handler steps mepc past the faulting instruction.") (source "RVI-RV32I §1.1.4"))
  (step (n 14) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x3C.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "mret") (writes)
    (derivation "MPP was set to S by the trap, so the return lands back in S at entry+0x3C.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 16) (insn "csrrs x6, sstatus, x0") (writes (write (reg "x6") (value "0x0000000200000000")))
    (derivation "sstatus IS S-accessible: the read is legal and returns the sstatus view — UXL held at 2 (bits 33:32), every other sstatus field 0.") (source "RVP-SUPERVISOR §4.1.1 (sstatus is the restricted mstatus view)")))
