;; mm-counters.expected.sexp — the expected observations for `mm-counters.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus; the 7 counter cells RE-DERIVED BY DESIGN at
;; P4-SYSTEM.5 slice (a) for the declared virtual-time domain — the .2 IALIGN-16
;; precedent: re-derived from the pinned chapters + the declared rate, never fitted).
;; EVD-05: every value below was derived from the pinned chapters BEFORE any engine
;; run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-counters.expected.sexp schema/expectations.sexp

(expectations (program "mm-counters.s") (entry "0x0000000080000000") (instructions 52)
  (step (n 0) (insn "rdcycle x5") (writes)
    (derivation "in M the counters are always readable; the laboratory's counters read 0 — and x5 already holds 0, so no change is observed.") (source "RVI-Zicntr §2.1 (RDCYCLE); the laboratory's fixed-zero counter policy"))
    (step (n 1) (insn "rdtime x6") (writes (write (reg "x6") (value "0x0000000000000001")))
    (derivation "one step boundary has passed: the declared virtual-time domain reads 1 (one tick per step boundary, retired or halted — the read at executed step k sees k). time is mcycle's read-only shadow, a valid RDTIME implementation.") (source "RVI-ZICNTR §6.1.1; state.sexp's mcycle row (P4-SYSTEM.5 decision 1)"))
    (step (n 2) (insn "rdinstret x7") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "minstret counts GENUINELY: two instructions retired cleanly (rdcycle, rdtime — no trap, no halt), so it reads 2. A trap-delivering, reserved-decoding or halted step would not increment.") (source "RVI-ZICNTR §6.1.1; state.sexp's minstret row (P4-SYSTEM.5 decision 1)"))
  (step (n 3) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x000000008000000c")))
    (derivation "auipc writes the instruction's own address (entry + 0xc).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 4) (insn "addi x1, x1, 168") (writes (write (reg "x1") (value "0x00000000800000b4")))
    (derivation "the delta 168 from the auipc's pc lands on the trap handler's first instruction at entry+0xB4.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 5) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler.") (source "RVI-ZICSR §5.1.1"))
  (step (n 6) (insn "addi x3, x0, 1") (writes (write (reg "x3") (value "0x0000000000000001")))
    (derivation "the MPP=S pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 7) (insn "slli x3, x3, 11") (writes (write (reg "x3") (value "0x0000000000000800")))
    (derivation "1 << 11 is the MPP field's S encoding.") (source "RVP-CSR (mstatus.MPP)"))
  (step (n 8) (insn "csrrw x0, mstatus, x3") (writes)
    (derivation "mstatus <- 0x800: MPP=S.") (source "RVP-CSR (mstatus field table)"))
  (step (n 9) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000024")))
    (derivation "auipc writes the instruction's own address (entry + 0x24).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 10) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x0000000080000044")))
    (derivation "the delta 32 from the auipc's pc lands on the S-mode cell at entry+0x44.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 11) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- entry+0x44.") (source "RVI-ZICSR §5.1.1"))
  (step (n 12) (insn "mret") (writes)
    (derivation "drop to S at the counter cell.") (source "RVP-INSNS §3.3.2 (mret)"))
    (step (n 13) (insn "rdcycle x8") (writes)
    (derivation "in S with mcounteren.CY clear, RDCYCLE traps illegal-instruction; mepc is entry+0x44.") (source "RVP-MACHINE §3.1.10 (mcounteren gates S/U counter reads)"))
  (step (n 14) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 0 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 0: branch to the first enable stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 16) (insn "addi x12, x0, 1") (writes (write (reg "x12") (value "0x0000000000000001")))
    (derivation "the stage counter becomes 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 17) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 1.") (source "RVI-ZICSR §5.1.1"))
  (step (n 18) (insn "csrrs x9, mcause, x0") (writes (write (reg "x9") (value "0x0000000000000002")))
    (derivation "the handler observes cause 2 for the gated read.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 19) (insn "addi x10, x0, 1") (writes (write (reg "x10") (value "0x0000000000000001")))
    (derivation "the CY bit pattern.") (source "RVI-RV32I §1.1.4"))
  (step (n 20) (insn "csrrs x0, mcounteren, x10") (writes)
    (derivation "set mcounteren.CY: S-mode cycle reads become legal.") (source "RVP-MACHINE §3.1.10 (mcounteren)"))
  (step (n 21) (insn "csrrs x11, mepc, x0") (writes (write (reg "x11") (value "0x0000000080000044")))
    (derivation "mepc is the trapped rdcycle's address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 22) (insn "addi x11, x11, 4") (writes (write (reg "x11") (value "0x0000000080000048")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 23) (insn "csrrw x0, mepc, x11") (writes)
    (derivation "mepc <- entry+0x48.") (source "RVI-ZICSR §5.1.1"))
  (step (n 24) (insn "mret") (writes)
    (derivation "back to S at the retry.") (source "RVP-INSNS §3.3.2 (mret)"))
    (step (n 25) (insn "rdcycle x8") (writes (write (reg "x8") (value "0x0000000000000019")))
    (derivation "the read at executed step k sees k = 25 — one tick per step boundary, retired or halted, every step in this flow included (the trapping .word steps tick too; only the values change, the trap/mode machinery is untouched).") (source "RVI-ZICNTR §6.1.1; state.sexp's mcycle row (P4-SYSTEM.5 decision 1)"))
  (step (n 26) (insn "ecall") (writes)
    (derivation "ecall from S: cause 9 — proves the rdcycle before it did NOT trap.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 27) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 1 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 28) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 1: the first branch does not fire.") (source "RVI-RV32I §1.1.5"))
  (step (n 29) (insn "addi x13, x0, 1") (writes (write (reg "x13") (value "0x0000000000000001")))
    (derivation "the comparison constant 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 30) (insn "beq x12, x13, stage2") (writes)
    (derivation "stage 1: branch to the drop-to-U stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 31) (insn "addi x12, x0, 2") (writes (write (reg "x12") (value "0x0000000000000002")))
    (derivation "the stage counter becomes 2.") (source "RVI-RV32I §1.1.4"))
  (step (n 32) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 2.") (source "RVI-ZICSR §5.1.1"))
  (step (n 33) (insn "csrrs x14, mcause, x0") (writes (write (reg "x14") (value "0x0000000000000009")))
    (derivation "the handler's second visit observes cause 9 (the S ecall).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 34) (insn "csrrw x0, mstatus, x0") (writes)
    (derivation "mstatus <- 0 clears MPP to U.") (source "RVP-CSR (mstatus field table)"))
  (step (n 35) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000114")))
    (derivation "auipc writes the instruction's own address.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 36) (insn "addi x4, x4, -144") (writes (write (reg "x4") (value "0x0000000080000084")))
    (derivation "the delta -144 lands on the U-mode counter cell at entry+0x84.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 37) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- entry+0x84.") (source "RVI-ZICSR §5.1.1"))
  (step (n 38) (insn "mret") (writes)
    (derivation "drop to U at the counter cell.") (source "RVP-INSNS §3.3.2 (mret)"))
    (step (n 39) (insn "rdcycle x13") (writes)
    (derivation "in U, BOTH mcounteren and scounteren must permit the read: scounteren.CY is still clear, so the read traps illegal-instruction even though mcounteren.CY is set.") (source "RVP-SUPERVISOR §5.1.7 (scounteren gates U-mode counter reads)"))
  (step (n 40) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 2 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 41) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 2: the first branch does not fire.") (source "RVI-RV32I §1.1.5"))
  (step (n 42) (insn "addi x13, x0, 1") (writes)
    (derivation "the comparison constant 1 — x13 already holds 1, no change observed.") (source "RVI-RV32I §1.1.4"))
  (step (n 43) (insn "beq x12, x13, stage2") (writes)
    (derivation "stage 2: the second branch does not fire either — fall through.") (source "RVI-RV32I §1.1.5"))
  (step (n 44) (insn "addi x10, x0, 1") (writes)
    (derivation "the CY bit pattern — x10 already holds 1, no change observed.") (source "RVI-RV32I §1.1.4"))
  (step (n 45) (insn "csrrs x0, scounteren, x10") (writes)
    (derivation "set scounteren.CY: U-mode cycle reads become legal.") (source "RVP-SUPERVISOR §5.1.7 (scounteren)"))
  (step (n 46) (insn "csrrs x15, mcause, x0") (writes (write (reg "x15") (value "0x0000000000000002")))
    (derivation "the handler's third visit observes cause 2 (the U-gated read).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 47) (insn "csrrs x11, mepc, x0") (writes (write (reg "x11") (value "0x0000000080000084")))
    (derivation "mepc is the trapped U-mode rdcycle's address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 48) (insn "addi x11, x11, 4") (writes (write (reg "x11") (value "0x0000000080000088")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 49) (insn "csrrw x0, mepc, x11") (writes)
    (derivation "mepc <- entry+0x88.") (source "RVI-ZICSR §5.1.1"))
  (step (n 50) (insn "mret") (writes)
    (derivation "back to U at the retry.") (source "RVP-INSNS §3.3.2 (mret)"))
    (step (n 51) (insn "rdcycle x13") (writes (write (reg "x13") (value "0x0000000000000033")))
    (derivation "the read at executed step k sees k = 51 — one tick per step boundary, retired or halted, every step in this flow included (the trapping .word steps tick too; only the values change, the trap/mode machinery is untouched).") (source "RVI-ZICNTR §6.1.1; state.sexp's mcycle row (P4-SYSTEM.5 decision 1)"))
)
