;; mm-ebreak.expected.sexp — the expected observations for `mm-ebreak.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus). EVD-05: every value below was derived from the
;; pinned chapters BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-ebreak.expected.sexp schema/expectations.sexp

(expectations (program "mm-ebreak.s") (entry "0x0000000080000000") (instructions 24)
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "auipc writes the instruction's own address (entry + 0x0).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 128") (writes (write (reg "x1") (value "0x0000000080000080")))
    (derivation "the delta 128 from the auipc's pc lands on the trap handler's first instruction at entry+0x80.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler; rd=x0 discards the old value.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "ebreak") (writes)
    (derivation "the requested breakpoint trap: with medeleg reset (bit 3 clear) it is taken in M; mepc and mtval are the ebreak's own address, mcause 3.") (source "RVI-RV32I §1.1.8 (D-ECALL-EBREAK); RVP-MACHINE §2.1.3.1"))
  (step (n 4) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000003")))
    (derivation "the handler observes cause 3 (breakpoint).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 5) (insn "csrrs x9, mtval, x0") (writes (write (reg "x9") (value "0x000000008000000c")))
    (derivation "mtval is the breakpoint's own address.") (source "RVP-MACHINE §2.1.3.1 (mtval)"))
  (step (n 6) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x000000008000000c")))
    (derivation "mepc is the ebreak's own address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 7) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x0000000080000010")))
    (derivation "the handler steps mepc past the ebreak.") (source "RVI-RV32I §1.1.4"))
  (step (n 8) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x10.") (source "RVI-ZICSR §5.1.1"))
  (step (n 9) (insn "mret") (writes)
    (derivation "the trap recorded MPP=M, so the return lands in M at entry+0x10.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 10) (insn "addi x5, x0, 1") (writes (write (reg "x5") (value "0x0000000000000001")))
    (derivation "execution resumed after a delivered breakpoint — the run continues.") (source "RVI-RV32I §1.1.4"))
  (step (n 11) (insn "csrrw x0, mstatus, x0") (writes)
    (derivation "mstatus <- 0 clears MPP to U.") (source "RVP-CSR (mstatus field table)"))
  (step (n 12) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000018")))
    (derivation "auipc writes the instruction's own address (entry + 0x18).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 13) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x0000000080000038")))
    (derivation "the delta 32 from the auipc's pc lands on the U-mode ebreak cell at entry+0x38.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 14) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- entry+0x38.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "mret") (writes)
    (derivation "mret with MPP=U drops to U-mode at the second ebreak.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 16) (insn "ebreak") (writes)
    (derivation "the U-mode breakpoint: medeleg bit 3 is clear, so it is still taken in M; mepc/mtval are entry+0x38.") (source "RVP-MACHINE §2.1.3.1 (medeleg)"))
  (step (n 17) (insn "csrrs x7, mcause, x0") (writes)
    (derivation "cause is again 3 — and x7 already holds 3, so no register change is observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 18) (insn "csrrs x9, mtval, x0") (writes (write (reg "x9") (value "0x0000000080000038")))
    (derivation "mtval is now the U-mode ebreak's address.") (source "RVP-MACHINE §2.1.3.1 (mtval)"))
  (step (n 19) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x0000000080000038")))
    (derivation "mepc is the U-mode ebreak's address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 20) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x000000008000003c")))
    (derivation "the handler steps mepc past the ebreak.") (source "RVI-RV32I §1.1.4"))
  (step (n 21) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x3C.") (source "RVI-ZICSR §5.1.1"))
  (step (n 22) (insn "mret") (writes)
    (derivation "the trap recorded MPP=U, so the return lands in U at entry+0x3C.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 23) (insn "addi x6, x0, 2") (writes (write (reg "x6") (value "0x0000000000000002")))
    (derivation "the U-mode continuation after the delivered breakpoint runs.") (source "RVI-RV32I §1.1.4")))
