;; mm-sfence.expected.sexp — the expected observations for `mm-sfence.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus). EVD-05: every value below was derived from the
;; pinned chapters BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-sfence.expected.sexp schema/expectations.sexp

(expectations (program "mm-sfence.s") (entry "0x0000000080000000") (instructions 43)
  (step (n 0) (insn "sfence.vma x0, x0") (writes)
    (derivation "SFENCE.VMA in M is always legal.") (source "RVP-INSNS §4.2.1 (sfence.vma)"))
  (step (n 1) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000004")))
    (derivation "auipc writes the instruction's own address (entry + 0x4).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 2) (insn "addi x1, x1, 168") (writes (write (reg "x1") (value "0x00000000800000ac")))
    (derivation "the delta 168 from the auipc's pc lands on the trap handler's first instruction at entry+0xAC.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 3) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler.") (source "RVI-ZICSR §5.1.1"))
  (step (n 4) (insn "addi x3, x0, 1") (writes (write (reg "x3") (value "0x0000000000000001")))
    (derivation "the MPP=S pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 5) (insn "slli x3, x3, 11") (writes (write (reg "x3") (value "0x0000000000000800")))
    (derivation "1 << 11 is the MPP field's S encoding.") (source "RVP-CSR (mstatus.MPP)"))
  (step (n 6) (insn "csrrw x0, mstatus, x3") (writes)
    (derivation "mstatus <- 0x800: MPP=S.") (source "RVP-CSR (mstatus field table)"))
  (step (n 7) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x000000008000001c")))
    (derivation "auipc writes the instruction's own address (entry + 0x1c).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 8) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x000000008000003c")))
    (derivation "the delta 32 from the auipc's pc lands on the S-mode cell at entry+0x3C.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 9) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- entry+0x3C.") (source "RVI-ZICSR §5.1.1"))
  (step (n 10) (insn "mret") (writes)
    (derivation "drop to S at the sfence cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 11) (insn "sfence.vma x0, x0") (writes)
    (derivation "SFENCE.VMA in S with TVM=0 is legal.") (source "RVP-INSNS §4.2.1 (sfence.vma; TVM=0)"))
  (step (n 12) (insn "ecall") (writes)
    (derivation "ecall from S: cause 9, entering the handler at stage 0.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 13) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000009")))
    (derivation "the handler observes cause 9.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 14) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 0 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 15) (insn "bne x12, x0, stage2") (writes)
    (derivation "stage 0: the branch does not fire.") (source "RVI-RV32I §1.1.5"))
  (step (n 16) (insn "addi x12, x0, 1") (writes (write (reg "x12") (value "0x0000000000000001")))
    (derivation "the stage counter becomes 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 17) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 1.") (source "RVI-ZICSR §5.1.1"))
  (step (n 18) (insn "addi x2, x0, 1") (writes (write (reg "x2") (value "0x0000000000000001")))
    (derivation "the TVM pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 19) (insn "slli x2, x2, 20") (writes (write (reg "x2") (value "0x0000000000100000")))
    (derivation "1 << 20 is TVM.") (source "RVP-CSR (mstatus.TVM is bit 20)"))
  (step (n 20) (insn "csrrs x0, mstatus, x2") (writes)
    (derivation "set mstatus.TVM.") (source "RVP-CSR (mstatus field table)"))
  (step (n 21) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x0000000080000040")))
    (derivation "mepc is the ecall's address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 22) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x0000000080000044")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 23) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x44.") (source "RVI-ZICSR §5.1.1"))
  (step (n 24) (insn "mret") (writes)
    (derivation "back to S at the TVM=1 sfence cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 25) (insn "sfence.vma x0, x0") (writes)
    (derivation "SFENCE.VMA in S with TVM=1 traps illegal-instruction.") (source "RVP-INSNS §4.2.1 (TVM=1 makes sfence.vma illegal in S)"))
  (step (n 26) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "the handler's second visit observes cause 2.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 27) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 1 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 28) (insn "bne x12, x0, stage2") (writes)
    (derivation "stage 1: branch to the resume stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 29) (insn "csrrs x7, mcause, x0") (writes)
    (derivation "cause 2 again — x7 already holds 2, no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 30) (insn "csrrs x8, mepc, x0") (writes)
    (derivation "mepc is entry+0x44 — x8 already holds it, no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 31) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x0000000080000048")))
    (derivation "step mepc past the sfence.") (source "RVI-RV32I §1.1.4"))
  (step (n 32) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x48.") (source "RVI-ZICSR §5.1.1"))
  (step (n 33) (insn "mret") (writes)
    (derivation "back to S at the satp cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 34) (insn "csrrs x9, satp, x0") (writes)
    (derivation "with TVM=1, even READING satp in S traps illegal-instruction.") (source "RVP-CSR §2.1 (TVM=1 traps S-mode satp access)"))
  (step (n 35) (insn "csrrs x7, mcause, x0") (writes)
    (derivation "cause 2 again — no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 36) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter still reads 1 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 37) (insn "bne x12, x0, stage2") (writes)
    (derivation "stage 1 again: branch to the resume stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 38) (insn "csrrs x7, mcause, x0") (writes)
    (derivation "cause 2 — no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 39) (insn "csrrs x8, mepc, x0") (writes)
    (derivation "mepc is entry+0x48 — x8 already holds it, no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 40) (insn "addi x8, x8, 4") (writes (write (reg "x8") (value "0x000000008000004c")))
    (derivation "step mepc past the satp read.") (source "RVI-RV32I §1.1.4"))
  (step (n 41) (insn "csrrw x0, mepc, x8") (writes)
    (derivation "mepc <- entry+0x4C.") (source "RVI-ZICSR §5.1.1"))
  (step (n 42) (insn "mret") (writes)
    (derivation "back to S at entry+0x4C.") (source "RVP-INSNS §3.3.2 (mret)")))
