;; mm-stimecmp.expected.sexp — the expected observations for `mm-stimecmp.s` (P4-SYSTEM.2
;; slice f, the mode-matrix corpus). EVD-05: every value below was derived from the
;; pinned chapters BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-stimecmp.expected.sexp schema/expectations.sexp

(expectations (program "mm-stimecmp.s") (entry "0x0000000080000000") (instructions 35)
  (step (n 0) (insn "csrrs x5, stimecmp, x0") (writes)
    (derivation "in M, stimecmp is always accessible and resets to 0 — x5 already holds 0, no change observed.") (source "RVP-SSTC §2.1 (stimecmp); the state document's reset"))
  (step (n 1) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000004")))
    (derivation "auipc writes the instruction's own address (entry + 0x4).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 2) (insn "addi x1, x1, 116") (writes (write (reg "x1") (value "0x0000000080000078")))
    (derivation "the delta 116 from the auipc's pc lands on the trap handler's first instruction at entry+0x78.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 3) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec is programmed to the handler.") (source "RVI-ZICSR §5.1.1"))
  (step (n 4) (insn "addi x3, x0, 1") (writes (write (reg "x3") (value "0x0000000000000001")))
    (derivation "the MPP=S pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 5) (insn "slli x3, x3, 11") (writes (write (reg "x3") (value "0x0000000000000800")))
    (derivation "1 << 11 is the MPP field's S encoding.") (source "RVP-CSR (mstatus.MPP)"))
  (step (n 6) (insn "csrrw x0, mstatus, x3") (writes)
    (derivation "mstatus <- 0x800: MPP=S.") (source "RVP-CSR (mstatus field table)"))
  (step (n 7) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x000000008000001c")))
    (derivation "auipc writes the instruction's own address (entry + 0x1c).") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 8) (insn "addi x4, x4, 32") (writes (write (reg "x4") (value "0x000000008000003c")))
    (derivation "the delta 32 from the auipc's pc lands on the S-mode cell at entry+0x3C.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 9) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc <- entry+0x3C.") (source "RVI-ZICSR §5.1.1"))
  (step (n 10) (insn "mret") (writes)
    (derivation "drop to S at the stimecmp cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 11) (insn "csrrs x6, stimecmp, x0") (writes)
    (derivation "in S with mcounteren.TM clear, ANY stimecmp access traps illegal-instruction.") (source "RVP-SSTC §2.1 (mcounteren.TM gates S access to stimecmp)"))
  (step (n 12) (insn "csrrs x8, mcause, x0") (writes (write (reg "x8") (value "0x0000000000000002")))
    (derivation "the handler observes cause 2.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 13) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 0 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 14) (insn "bne x12, x0, second") (writes)
    (derivation "stage 0: the branch does not fire.") (source "RVI-RV32I §1.1.5"))
  (step (n 15) (insn "addi x9, x0, 2") (writes (write (reg "x9") (value "0x0000000000000002")))
    (derivation "the TM bit pattern (bit 1).") (source "RVI-RV32I §1.1.4"))
  (step (n 16) (insn "csrrs x0, mcounteren, x9") (writes)
    (derivation "set mcounteren.TM.") (source "RVP-MACHINE §3.1.10 (mcounteren)"))
  (step (n 17) (insn "addi x12, x0, 1") (writes (write (reg "x12") (value "0x0000000000000001")))
    (derivation "the stage counter becomes 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 18) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 1.") (source "RVI-ZICSR §5.1.1"))
  (step (n 19) (insn "beq x0, x0, resume") (writes)
    (derivation "unconditional branch to the shared resume sequence.") (source "RVI-RV32I §1.1.5"))
  (step (n 20) (insn "csrrs x10, mepc, x0") (writes (write (reg "x10") (value "0x000000008000003c")))
    (derivation "mepc is the trapped csrrs's address.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 21) (insn "addi x10, x10, 4") (writes (write (reg "x10") (value "0x0000000080000040")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 22) (insn "csrrw x0, mepc, x10") (writes)
    (derivation "mepc <- entry+0x40.") (source "RVI-ZICSR §5.1.1"))
  (step (n 23) (insn "mret") (writes)
    (derivation "back to S at the second stimecmp cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 24) (insn "csrrs x7, stimecmp, x0") (writes)
    (derivation "TM is set but menvcfg.STCE is clear: with STCE=0 the stimecmp CSR does not exist for S, so the access still traps illegal-instruction.") (source "RVP-SSTC §2.1 (STCE enables the stimecmp CSR)"))
  (step (n 25) (insn "csrrs x8, mcause, x0") (writes)
    (derivation "cause 2 again — x8 already holds 2, no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 26) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter reads 1 — no change observed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 27) (insn "bne x12, x0, second") (writes)
    (derivation "stage 1: branch to the STCE-enable stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 28) (insn "lui x9, 0x80000") (writes (write (reg "x9") (value "0xffffffff80000000")))
    (derivation "lui 0x80000 places a 1 in bit 31 of the upper immediate — sign-extended to bit 63, which is menvcfg.STCE.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC); RVP-CSR (menvcfg.STCE is bit 63)"))
  (step (n 29) (insn "csrrs x0, menvcfg, x9") (writes)
    (derivation "set menvcfg.STCE: the stimecmp CSR now exists for S.") (source "RVP-SSTC §2.1 (STCE)"))
  (step (n 30) (insn "csrrs x10, mepc, x0") (writes)
    (derivation "mepc is the trapped csrrs's address (entry+0x40) — x10 already holds it, no change observed.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 31) (insn "addi x10, x10, 4") (writes (write (reg "x10") (value "0x0000000080000044")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 32) (insn "csrrw x0, mepc, x10") (writes)
    (derivation "mepc <- entry+0x44.") (source "RVI-ZICSR §5.1.1"))
  (step (n 33) (insn "mret") (writes)
    (derivation "back to S at the third stimecmp cell.") (source "RVP-INSNS §3.3.2 (mret)"))
  (step (n 34) (insn "csrrs x15, stimecmp, x0") (writes)
    (derivation "TM set and STCE set: the S-mode read is legal and returns 0 — x15 already holds 0, so no change is observed; legality is proven by control flow reaching the run's end without another trap.") (source "RVP-SSTC §2.1 (stimecmp); the state document's reset")))
