;; mm-wfi.expected.sexp — the expected observations for `mm-wfi.s` (P4-SYSTEM.5
;; slice b, the interrupts corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .5 brief's declared delivery rule by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py mm-wfi.expected.sexp schema/expectations.sexp

(expectations (program "mm-wfi.s") (entry "0x0000000080000000") (instructions 61) (fetches 57)
  (never_written "x28")
  (never_written "x29")
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "x1 = this instruction's own address.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 96") (writes (write (reg "x1") (value "0x0000000080000060")))
    (derivation "the handler rides 96 bytes in.") (source "RVI-RV32I §1.1.4"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec programmed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "addi x15, x0, 1") (writes (write (reg "x15") (value "0x0000000000000001")))
    (derivation "raw material for STI's bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 4) (insn "slli x15, x15, 5") (writes (write (reg "x15") (value "0x0000000000000020")))
    (derivation "x15 = 1 << 5.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 5) (insn "csrrs x0, mie, x15") (writes)
    (derivation "STIE <- 1 (MIE stays clear: the legal cells wake WITHOUT a trap).") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 6) (insn "addi x8, x0, 11") (writes (write (reg "x8") (value "0x000000000000000b")))
    (derivation "the M cell's stimecmp: 11 — three ticks past the wfi's head (time 8 there).") (source "RVI-RV32I §1.1.4"))
  (step (n 7) (insn "csrrw x0, stimecmp, x8") (writes)
    (derivation "stimecmp <- 11 (time 7 < 11: STIP computes 0, the wfi's head is quiet).") (source "RVP-SSTC 12.1"))
  (step (n 8) (insn "wfi") (writes)
    (derivation "the M cell: legal — the hart ENTERS the wait (the nop latitude recorded-not-taken); TWO halted steps follow (time 9, 10 < 11).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decision 4"))
  (step (n 9) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 10) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 11) (insn "rdtime x7") (writes (write (reg "x7") (value "0x000000000000000b")))
    (derivation "time is 11: the M cell's span, observed — the arrival woke the hart, M with MIE clear took nothing, execution resumed at pc + 4.") (source "RVP-MACHINE §2.1.3.3; RVP-SSTC 12.1"))
  (step (n 12) (insn "csrrs x0, mideleg, x15") (writes)
    (derivation "mideleg[5] <- 1: the S cell's source is DELEGATED — and must still wake the hart ('even if it has been delegated to a less-privileged mode').") (source "RVP-MACHINE §2.1.3.3, §2.1.1.8"))
  (step (n 13) (insn "addi x8, x0, 25") (writes (write (reg "x8") (value "0x0000000000000019")))
    (derivation "the S cell's stimecmp: 25 — three ticks past its wfi's head (time 22 there).") (source "RVI-RV32I §1.1.4"))
  (step (n 14) (insn "csrrw x0, stimecmp, x8") (writes)
    (derivation "stimecmp <- 25: STIP <- 0 by computation (time 15 at the next head < 25).") (source "RVP-SSTC 12.1"))
  (step (n 15) (insn "addi x3, x0, 1") (writes (write (reg "x3") (value "0x0000000000000001")))
    (derivation "the MPP=S pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 16) (insn "slli x3, x3, 11") (writes (write (reg "x3") (value "0x0000000000000800")))
    (derivation "1 << 11 is the MPP field's S encoding.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 17) (insn "csrrw x0, mstatus, x3") (writes)
    (derivation "mstatus <- 0x800: MPP=S.") (source "RVI-ZICSR §5.1.1"))
  (step (n 18) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x0000000080000040")))
    (derivation "x4 = this address.") (source "RVI-RV32I §1.1.4"))
  (step (n 19) (insn "addi x4, x4, 16") (writes (write (reg "x4") (value "0x0000000080000050")))
    (derivation "the S cell rides 16 bytes past this auipc (entry+0x50).") (source "RVI-RV32I §1.1.4"))
  (step (n 20) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc = the S cell.") (source "RVI-ZICSR §5.1.1"))
  (step (n 21) (insn "mret") (writes)
    (derivation "drop to S at the WFI cell (SIE lands clear from SPIE).") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 22) (insn "wfi") (writes)
    (derivation "the S cell: TW=0, legal — the hart ENTERS the wait; TWO halted steps follow (time 23, 24 < 25).") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 23) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 24) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 25) (insn "ecall") (writes)
    (derivation "the wake resumed at pc + 4 (the delegated arrival woke it, SIE clear took nothing): ecall from S, cause 9, entering the handler at stage 0.") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 26) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter (0, then 1, then 2 — the latter two visits read back their own value, no change observed).") (source "RVI-ZICSR §5.1.1"))
  (step (n 27) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 0: branch to the TW-enable stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 28) (insn "addi x12, x0, 1") (writes (write (reg "x12") (value "0x0000000000000001")))
    (derivation "the stage counter becomes 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 29) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 1.") (source "RVI-ZICSR §5.1.1"))
  (step (n 30) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000009")))
    (derivation "the handler observes cause 9 (the ecall).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 31) (insn "addi x2, x0, 1") (writes (write (reg "x2") (value "0x0000000000000001")))
    (derivation "the TW pattern starts as a 1.") (source "RVI-RV32I §1.1.4"))
  (step (n 32) (insn "slli x2, x2, 21") (writes (write (reg "x2") (value "0x0000000000200000")))
    (derivation "1 << 21 is TW.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 33) (insn "csrrs x0, mstatus, x2") (writes)
    (derivation "set mstatus.TW.") (source "RVI-ZICSR §5.1.1"))
  (step (n 34) (insn "csrrs x10, mepc, x0") (writes (write (reg "x10") (value "0x0000000080000054")))
    (derivation "mepc is the ecall's address (entry+0x54).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 35) (insn "addi x10, x10, 4") (writes (write (reg "x10") (value "0x0000000080000058")))
    (derivation "step mepc past it.") (source "RVI-RV32I §1.1.4"))
  (step (n 36) (insn "csrrw x0, mepc, x10") (writes)
    (derivation "mepc <- entry+0x58 — the TW=1 cell.") (source "RVI-ZICSR §5.1.1"))
  (step (n 37) (insn "mret") (writes)
    (derivation "back to S at the TW=1 WFI cell.") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 38) (insn "wfi") (writes)
    (derivation "the TW=1 cell: WFI in S with TW=1 traps illegal-instruction (the .2 resolution, standing).") (source "RVP-MACHINE §2.1.3.3, §2.1.1.6.6"))
  (step (n 39) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter (0, then 1, then 2 — the latter two visits read back their own value, no change observed).") (source "RVI-ZICSR §5.1.1"))
  (step (n 40) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 0: branch to the TW-enable stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 41) (insn "addi x13, x0, 1") (writes (write (reg "x13") (value "0x0000000000000001")))
    (derivation "the comparison constant 1 (the third visit rewrites its own value, no change observed).") (source "RVI-RV32I §1.1.4"))
  (step (n 42) (insn "beq x12, x13, stage2") (writes)
    (derivation "stage 1: branch to the drop-to-U stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 43) (insn "addi x12, x0, 2") (writes (write (reg "x12") (value "0x0000000000000002")))
    (derivation "the stage counter becomes 2.") (source "RVI-RV32I §1.1.4"))
  (step (n 44) (insn "csrrw x0, mscratch, x12") (writes)
    (derivation "mscratch <- 2.") (source "RVI-ZICSR §5.1.1"))
  (step (n 45) (insn "csrrs x7, mcause, x0") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "the handler's second visit observes cause 2 (the TW=1 WFI).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 46) (insn "addi x13, x0, 1") (writes)
    (derivation "raw material for the high stimecmp.") (source "RVI-RV32I §1.1.4"))
  (step (n 47) (insn "slli x13, x13, 16") (writes (write (reg "x13") (value "0x0000000000010000")))
    (derivation "x13 = 0x10000.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 48) (insn "csrrw x0, stimecmp, x13") (writes)
    (derivation "disarm the timer FIRST: the delegated STI is still pending, and in U it would be taken in S — the drop must find nothing pending.") (source "RVP-SSTC 12.1; RVP-MACHINE §2.1.1.8"))
  (step (n 49) (insn "csrrw x0, mstatus, x0") (writes)
    (derivation "mstatus <- 0 clears MPP to U (and TW back to 0).") (source "RVI-ZICSR §5.1.1"))
  (step (n 50) (insn "auipc x4, 0") (writes (write (reg "x4") (value "0x00000000800000c8")))
    (derivation "x4 = this address.") (source "RVI-RV32I §1.1.4"))
  (step (n 51) (insn "addi x4, x4, -108") (writes (write (reg "x4") (value "0x000000008000005c")))
    (derivation "the U-mode WFI cell rides 108 bytes back (entry+0x5C).") (source "RVI-RV32I §1.1.4"))
  (step (n 52) (insn "csrrw x0, mepc, x4") (writes)
    (derivation "mepc = the U cell.") (source "RVI-ZICSR §5.1.1"))
  (step (n 53) (insn "mret") (writes)
    (derivation "drop to U at the WFI cell.") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 54) (insn "wfi") (writes)
    (derivation "the U cell: WFI in U-mode traps illegal-instruction on this composition (the laboratory's WFI-in-U policy, standing).") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 55) (insn "csrrs x12, mscratch, x0") (writes)
    (derivation "the stage counter (0, then 1, then 2 — the latter two visits read back their own value, no change observed).") (source "RVI-ZICSR §5.1.1"))
  (step (n 56) (insn "beq x12, x0, stage1") (writes)
    (derivation "stage 0: branch to the TW-enable stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 57) (insn "addi x13, x0, 1") (writes (write (reg "x13") (value "0x0000000000000001")))
    (derivation "the comparison constant 1 (the third visit rewrites its own value, no change observed).") (source "RVI-RV32I §1.1.4"))
  (step (n 58) (insn "beq x12, x13, stage2") (writes)
    (derivation "stage 1: branch to the drop-to-U stage.") (source "RVI-RV32I §1.1.5"))
  (step (n 59) (insn "csrrs x15, mcause, x0") (writes (write (reg "x15") (value "0x0000000000000002")))
    (derivation "the handler's third visit observes cause 2 (the U-mode WFI).") (source "RVP-MACHINE §2.1.3.1"))
  (step (n 60) (insn "csrrs x8, mepc, x0") (writes (write (reg "x8") (value "0x000000008000005c")))
    (derivation "mepc is the trapped U-mode wfi's own address (entry+0x5C).") (source "RVP-MACHINE §2.1.3.1 #|end"))
)
