;; w-notrap.expected.sexp — the expected observations for `w-notrap.s` (P4-SYSTEM.5
;; slice b, the interrupts corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .5 brief's declared delivery rule by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py w-notrap.expected.sexp schema/expectations.sexp

(expectations (program "w-notrap.s") (entry "0x0000000080000000") (instructions 19) (fetches 16)
  (never_written "x28")
  (never_written "x29")
  (step (n 0) (insn "addi x8, x0, 8") (writes (write (reg "x8") (value "0x0000000000000008")))
    (derivation "the first stimecmp: 8 — three ticks past the first wfi's head (time 5 there).") (source "RVI-RV32I §1.1.4"))
  (step (n 1) (insn "csrrw x0, stimecmp, x8") (writes)
    (derivation "stimecmp <- 8 (time 1 < 8: STIP computes 0, the wfi's head is quiet).") (source "RVP-SSTC 12.1"))
  (step (n 2) (insn "addi x15, x0, 1") (writes (write (reg "x15") (value "0x0000000000000001")))
    (derivation "raw material for STIE's bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 3) (insn "slli x15, x15, 5") (writes (write (reg "x15") (value "0x0000000000000020")))
    (derivation "x15 = 1 << 5.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 4) (insn "csrrs x0, mie, x15") (writes)
    (derivation "STIE <- 1 (MIE stays CLEAR the whole guest — no trap can be taken).") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 5) (insn "wfi") (writes)
    (derivation "the first halt: TWO halted steps (time 6, 7 < 8), then STIP's arrival wakes the hart — M with MIE clear takes nothing, so execution resumes at pc + 4.") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 6) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 7) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 8) (insn "rdtime x7") (writes (write (reg "x7") (value "0x0000000000000008")))
    (derivation "time is 8 — the wake's own tick, observed: the hart WOKE though nothing traps.") (source "RVP-SSTC 12.1; RVP-MACHINE §2.1.3.3"))
  (step (n 9) (insn "csrrs x11, mip, x0") (writes (write (reg "x11") (value "0x0000000000000020")))
    (derivation "STIP reads 1 (time 9 >= 8): the locally-enabled pending that woke it.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 10) (insn "addi x8, x0, 14") (writes (write (reg "x8") (value "0x000000000000000e")))
    (derivation "the second stimecmp: 14 — two ticks past the second wfi's head (time 12 there).") (source "RVI-RV32I §1.1.4"))
  (step (n 11) (insn "csrrw x0, stimecmp, x8") (writes)
    (derivation "stimecmp <- 14: STIP <- 0 by computation (time 11 < 14) — the loop's re-arm.") (source "RVP-SSTC 12.1"))
  (step (n 12) (insn "wfi") (writes)
    (derivation "the loop-back: the second halt — ONE halted step (time 13 < 14), then the arrival wakes it again.") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 13) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 14) (insn "csrrs x7, mip, x0") (writes (write (reg "x7") (value "0x0000000000000020")))
    (derivation "STIP reads 1 again (time 14 >= 14) — the second wake's cause.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 15) (insn "addi x13, x0, 1") (writes (write (reg "x13") (value "0x0000000000000001")))
    (derivation "raw material for the high stimecmp.") (source "RVI-RV32I §1.1.4"))
  (step (n 16) (insn "slli x13, x13, 16") (writes (write (reg "x13") (value "0x0000000000010000")))
    (derivation "x13 = 0x10000.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 17) (insn "csrrw x0, stimecmp, x13") (writes)
    (derivation "disarm the timer for good.") (source "RVP-SSTC 12.1"))
  (step (n 18) (insn "addi x9, x0, 42") (writes (write (reg "x9") (value "0x000000000000002a")))
    (derivation "the landing marker: both halts woke, no trap ever fired.") (source "RVI-RV32I §1.1.4 #|end"))
)
