;; w-sw.expected.sexp — the expected observations for `w-sw.s` (P4-SYSTEM.5
;; slice b, the interrupts corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .5 brief's declared delivery rule by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py w-sw.expected.sexp schema/expectations.sexp

(expectations (program "w-sw.s") (entry "0x0000000080000000") (instructions 17)
  (never_written "x28")
  (never_written "x29")
  (step (n 0) (insn "addi x13, x0, 1") (writes (write (reg "x13") (value "0x0000000000000001")))
    (derivation "raw material for the high stimecmp.") (source "RVI-RV32I §1.1.4"))
  (step (n 1) (insn "slli x13, x13, 16") (writes (write (reg "x13") (value "0x0000000000010000")))
    (derivation "x13 = 0x10000.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 2) (insn "csrrw x0, stimecmp, x13") (writes)
    (derivation "disarm the reset-quirk STIP first (STIE is never set, but the mip reads below want single-bit values).") (source "RVP-SSTC 12.1"))
  (step (n 3) (insn "addi x2, x0, 2") (writes (write (reg "x2") (value "0x0000000000000002")))
    (derivation "the SSIP bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 4) (insn "csrrs x0, mip, x2") (writes)
    (derivation "SSIP <- 1 (MIE is clear: the taken-rule passes it by, so the wfi's own head is quiet).") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 5) (insn "csrrs x0, mie, x2") (writes)
    (derivation "SSIE <- 1 — the local enable is all the wake needs.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 6) (insn "wfi") (writes)
    (derivation "the first halt: the wake fires at the VERY NEXT head (a software-posted source is already pending) — M with MIE clear takes nothing, so execution resumes at pc + 4.") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 7) (insn "csrrs x7, mip, x0") (writes (write (reg "x7") (value "0x0000000000000002")))
    (derivation "x7 = SSIP alone (0x2 — the timer disarmed): the pending that woke it, interrogated per the spec's own guidance ('the mip or sip registers can be interrogated').") (source "RVP-MACHINE §2.1.3.3, §2.1.1.9"))
  (step (n 8) (insn "csrrc x0, mip, x2") (writes)
    (derivation "clear SSIP.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 9) (insn "addi x8, x0, 1") (writes (write (reg "x8") (value "0x0000000000000001")))
    (derivation "raw material for SEIP's bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 10) (insn "slli x8, x8, 9") (writes (write (reg "x8") (value "0x0000000000000200")))
    (derivation "x8 = 1 << 9.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 11) (insn "csrrs x0, mip, x8") (writes)
    (derivation "SEIP <- 1 (the software-writable B part).") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 12) (insn "csrrs x0, mie, x8") (writes)
    (derivation "SEIE <- 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 13) (insn "wfi") (writes)
    (derivation "the second halt: SEI wakes it the same way — globals still clear.") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 14) (insn "csrrs x7, mip, x0") (writes (write (reg "x7") (value "0x0000000000000200")))
    (derivation "x7 = SEIP alone (0x200).") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 15) (insn "csrrc x0, mip, x8") (writes)
    (derivation "clear SEIP.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 16) (insn "addi x9, x0, 42") (writes (write (reg "x9") (value "0x000000000000002a")))
    (derivation "the landing marker: both software sources woke the hart with the globals off.") (source "RVI-RV32I §1.1.4 #|end"))
)
