;; w-timer.expected.sexp — the expected observations for `w-timer.s` (P4-SYSTEM.5
;; slice b, the interrupts corpus). EVD-05: every value below was derived from the pinned
;; chapters and the .5 brief's declared delivery rule by the spec-side authoring model
;; BEFORE any engine run; the corpus runner falsifies against it.
;; Validate with
;;   python3 scripts/check_sexp_schema.py w-timer.expected.sexp schema/expectations.sexp

(expectations (program "w-timer.s") (entry "0x0000000080000000") (instructions 23) (fetches 20)
  (never_written "x28")
  (never_written "x29")
  (step (n 0) (insn "auipc x1, 0") (writes (write (reg "x1") (value "0x0000000080000000")))
    (derivation "x1 = this instruction's own address.") (source "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"))
  (step (n 1) (insn "addi x1, x1, 48") (writes (write (reg "x1") (value "0x0000000080000030")))
    (derivation "the handler rides 48 bytes in.") (source "RVI-RV32I §1.1.4"))
  (step (n 2) (insn "csrrw x0, mtvec, x1") (writes)
    (derivation "mtvec programmed.") (source "RVI-ZICSR §5.1.1"))
  (step (n 3) (insn "addi x8, x0, 13") (writes (write (reg "x8") (value "0x000000000000000d")))
    (derivation "stimecmp's target: 13 — three ticks past the wfi's head (time 10 there, by the declared domain).") (source "RVI-RV32I §1.1.4"))
  (step (n 4) (insn "csrrw x0, stimecmp, x8") (writes)
    (derivation "stimecmp <- 13: STIP computes 0 for now (time 4 < 13), so the wfi's own head is quiet.") (source "RVP-SSTC 12.1"))
  (step (n 5) (insn "addi x15, x0, 1") (writes (write (reg "x15") (value "0x0000000000000001")))
    (derivation "raw material for STIE's bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 6) (insn "slli x15, x15, 5") (writes (write (reg "x15") (value "0x0000000000000020")))
    (derivation "x15 = 1 << 5.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 7) (insn "csrrs x0, mie, x15") (writes)
    (derivation "STIE <- 1.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 8) (insn "addi x6, x0, 8") (writes (write (reg "x6") (value "0x0000000000000008")))
    (derivation "the MIE bit.") (source "RVI-RV32I §1.1.4"))
  (step (n 9) (insn "csrrs x0, mstatus, x6") (writes)
    (derivation "MIE <- 1: when the timer arrives, the taken-rule will hold.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 10) (insn "wfi") (writes)
    (derivation "the M cell: legal, so the hart ENTERS the wait (the nop latitude recorded-not-taken) — TWO halted steps follow (time 11, 12 < 13), then the arrival wakes it and the trap is taken — mepc is the NEXT instruction.") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decision 4"))
  (step (n 11) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 12) (insn "<halted>") (writes)
    (derivation "the halt: the hart is WAITING — nothing retires and no fetch issues this step; the domain ticks one, and the wake re-evaluates at the next head (a locally-enabled pending interrupt at any privilege level, regardless of the global enables and of mideleg).") (source "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"))
  (step (n 13) (insn "addi x9, x0, 42") (writes)
    (derivation "the pending evaluation takes the STI interrupt in M: xcause carries the Interrupt bit with cause 5, xepc is the un-fetched pc (interrupts are taken BETWEEN instructions), and pc moves to the vector as declared (no register observation — the handler's csrr reads below are the evidence).") (source "RVP-MACHINE §2.1.1.9; RVP-SUPERVISOR §11.1.1.3; the .5 brief's decision 3"))
  (step (n 14) (insn "rdinstret x14") (writes (write (reg "x14") (value "0x000000000000000b")))
    (derivation "instret is 11 at the handler's FIRST step — the ten setup instructions and the wfi, and NOTHING across the halt or the delivery: the timer wake occurred WITHOUT CPU RETIREMENT (the leaf's acceptance, observed).") (source "RVP-MACHINE §2.1.1.9; the .5 brief's decision 1"))
  (step (n 15) (insn "rdtime x13") (writes (write (reg "x13") (value "0x000000000000000f")))
    (derivation "time is 15: the wfi retired at 10 and five boundaries passed (two halted steps, the delivery, the handler's own) — the halt spanned REAL ticks.") (source "RVP-SSTC 12.1; the .5 brief's decision 1"))
  (step (n 16) (insn "csrrs x11, mcause, x0") (writes (write (reg "x11") (value "0x8000000000000005")))
    (derivation "the handler observes the Interrupt bit with cause 5 — the timer, delivered.") (source "RVP-MACHINE §2.1.1.9"))
  (step (n 17) (insn "csrrs x12, mepc, x0") (writes (write (reg "x12") (value "0x000000008000002c")))
    (derivation "mepc is the wfi's pc + 4 (0x80000044) — §2.1.3.3's WFI-specific rule, which the generic between-instructions delivery computes for free.") (source "RVP-MACHINE §2.1.3.3"))
  (step (n 18) (insn "addi x16, x0, 1") (writes (write (reg "x16") (value "0x0000000000000001")))
    (derivation "raw material for the high stimecmp.") (source "RVI-RV32I §1.1.4"))
  (step (n 19) (insn "slli x16, x16, 16") (writes (write (reg "x16") (value "0x0000000000010000")))
    (derivation "x16 = 0x10000, far above this guest's clock.") (source "RVI-RV64I §3.1.2.1"))
  (step (n 20) (insn "csrrw x0, stimecmp, x16") (writes)
    (derivation "disarm the timer for good (STIP <- 0 by computation).") (source "RVP-SSTC 12.1"))
  (step (n 21) (insn "mret") (writes)
    (derivation "the stack pops per MPP and pc <- mepc — the landing marker.") (source "RVP-MACHINE §2.1.3.2"))
  (step (n 22) (insn "addi x9, x0, 42") (writes (write (reg "x9") (value "0x000000000000002a")))
    (derivation "the landing marker: the handler's mret returns here (mepc was already the continuation — no +4 step).") (source "RVI-RV32I §1.1.4 #|end"))
)
