;; contract-obligations.sexp — the device contract for `sifive-uart-lab-v0` (P5-BOARD.2,
;; 2026-10-02). One (obligation …) per record. Validate:
;;   python3 scripts/check_sexp_schema.py profiles/sifive-uart-lab-v0/contract-obligations.sexp schema/contract-obligations.sexp
;; The contract id is `sifive-uart-v0` v0. Every obligation is a DEVICE GUARANTEE
;; (direction device-guarantee — the schema's third direction, added by P5-BOARD.2): what
;; the datasheet lets a composing board rely on, or — for the `unspecified`-category mirrors — what it
;; forbids the board from relying on. Each mirrors its requirement's statement EXACTLY
;; (RECORD-SCHEMA rule 9); the board definition's `satisfies` fields and P5-BOARD.4's
;; discharge verdict name these ids.

(obligation (id "OB-UART-MAP") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The UART register map is seven 32-bit registers — txdata 0x00, rxdata 0x04, txctrl 0x08, rxctrl 0x0C, ie 0x10, ip 0x14, div 0x18 — designed to require only naturally aligned 32-bit memory accesses.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3, Table 59")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-MAP"))) (param (name decision_id) (value (str "D-UART-MAP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-MAP") (required_checks "CHK-UART-MAP-POS") (required_checks "CHK-UART-MAP-NEG"))

(obligation (id "OB-UART-INSTANCE") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "UART instance 0 is at base address 0x10010000 with div_width = 20, div_init = 289 and 8-entry transmit and receive FIFOs; instance 1 at 0x10011000 has identical parameters.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.2, Table 58")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-INSTANCE"))) (param (name decision_id) (value (str "D-UART-INSTANCE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-INSTANCE") (required_checks "CHK-UART-INSTANCE-POS") (required_checks "CHK-UART-INSTANCE-NEG"))

(obligation (id "OB-UART-TXDATA-WRITE") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "Writing txdata enqueues the data field's character into the transmit FIFO if the FIFO can accept new entries; when the full flag is set, writes to data are ignored.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.4, Table 60")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-TXDATA-WRITE"))) (param (name decision_id) (value (str "D-UART-TXDATA-WRITE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-TXDATA-WRITE") (required_checks "CHK-UART-TXDATA-WRITE-POS") (required_checks "CHK-UART-TXDATA-WRITE-NEG"))

(obligation (id "OB-UART-TXDATA-READ") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "Reading txdata returns the current value of the full flag (bit 31) and zero in the data field; the full flag indicates whether the transmit FIFO can accept new entries.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.4, Table 60")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-TXDATA-READ"))) (param (name decision_id) (value (str "D-UART-TXDATA-READ"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-TXDATA-READ") (required_checks "CHK-UART-TXDATA-READ-POS") (required_checks "CHK-UART-TXDATA-READ-NEG"))

(obligation (id "OB-UART-RXDATA-READ") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "Reading rxdata dequeues a character from the receive FIFO and returns it in the data field; the empty flag (bit 31) indicates whether the receive FIFO was empty, and when set the data field does not contain a valid character.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.5, Table 61")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-RXDATA-READ"))) (param (name decision_id) (value (str "D-UART-RXDATA-READ"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-RXDATA-READ") (required_checks "CHK-UART-RXDATA-READ-POS") (required_checks "CHK-UART-RXDATA-READ-NEG"))

(obligation (id "OB-UART-RXDATA-WRITE") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "Writes to rxdata are ignored.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.5")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-RXDATA-WRITE"))) (param (name decision_id) (value (str "D-UART-RXDATA-WRITE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-RXDATA-WRITE") (required_checks "CHK-UART-RXDATA-WRITE-POS") (required_checks "CHK-UART-RXDATA-WRITE-NEG"))

(obligation (id "OB-UART-TXCTRL") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "txctrl is read-write: txen (bit 0) controls whether the Tx channel is active — when cleared, transmission of Tx FIFO contents is suppressed and the txd pin is driven high; nstop (bit 1) selects one (0) or two (1) stop bits; txcnt (bits [18:16]) is the transmit watermark threshold. txctrl resets to 0.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.6, Table 62")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-TXCTRL"))) (param (name decision_id) (value (str "D-UART-TXCTRL"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-TXCTRL") (required_checks "CHK-UART-TXCTRL-POS") (required_checks "CHK-UART-TXCTRL-NEG"))

(obligation (id "OB-UART-RXCTRL") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "rxctrl is read-write: rxen (bit 0) controls whether the Rx channel is active — when cleared, the state of the rxd pin is ignored and no characters are enqueued into the Rx FIFO; rxcnt (bits [18:16]) is the receive watermark threshold. rxctrl resets to 0. Characters are enqueued when a zero (low) start bit is seen.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.7, Table 63")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-RXCTRL"))) (param (name decision_id) (value (str "D-UART-RXCTRL"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-RXCTRL") (required_checks "CHK-UART-RXCTRL-POS") (required_checks "CHK-UART-RXCTRL-NEG"))

(obligation (id "OB-UART-IE") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "ie is read-write: txwm (bit 0) is the transmit watermark interrupt enable and rxwm (bit 1) is the receive watermark interrupt enable. ie resets to 0.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 64")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-IE"))) (param (name decision_id) (value (str "D-UART-IE"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-IE") (required_checks "CHK-UART-IE-POS") (required_checks "CHK-UART-IE-NEG"))

(obligation (id "OB-UART-IP") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "ip is read-only: txwm (bit 0) becomes raised when the number of entries in the transmit FIFO is strictly less than txcnt and is cleared when sufficient entries have been enqueued to exceed the watermark; rxwm (bit 1) becomes raised when the number of entries in the receive FIFO is strictly greater than rxcnt and is cleared when sufficient entries have been dequeued to fall below the watermark.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 65")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-IP"))) (param (name decision_id) (value (str "D-UART-IP"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-IP") (required_checks "CHK-UART-IP-POS") (required_checks "CHK-UART-IP-NEG"))

(obligation (id "OB-UART-WM-MODE") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "Whether an ip watermark bit is a pure level function of FIFO occupancy or holds its value between its raised and cleared conditions is not specified: §13.8 gives each bit a strict-inequality raised condition and a strict-inequality cleared condition, so the == boundary and any value before a condition first holds — including after reset, where the bits are X — are undetermined.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 65 (the two strict sentences per bit; the gap measured against them)")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-WM-MODE"))) (param (name decision_id) (value (str "D-UART-WM-MODE"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-WM-MODE") (required_checks "CHK-UART-WM-MODE-POS") (required_checks "CHK-UART-WM-MODE-NEG"))

(obligation (id "OB-UART-DIV") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "div is a read-write div_width-bit register (div_width = 20) specifying the divisor used by baud-rate generation for both channels; its reset value is div_init = 289, tuned to provide 115200 baud out of reset given the expected tlclk frequency, and the divide ratio is one greater than the value stored in div.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.9, Table 58, Table 66")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-DIV"))) (param (name decision_id) (value (str "D-UART-DIV"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-DIV") (required_checks "CHK-UART-DIV-POS") (required_checks "CHK-UART-DIV-NEG"))

(obligation (id "OB-UART-FIFO-DEPTH") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The transmit and receive FIFOs are 8 entries each.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.1, Table 58")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-FIFO-DEPTH"))) (param (name decision_id) (value (str "D-UART-FIFO-DEPTH"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-FIFO-DEPTH") (required_checks "CHK-UART-FIFO-DEPTH-POS") (required_checks "CHK-UART-FIFO-DEPTH-NEG"))

(obligation (id "OB-UART-FORMAT") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The UART supports 8-N-1 and 8-N-2 formats — 8 data bits, no parity, 1 start bit, 1 or 2 stop bits — with 16x Rx oversampling and 2/3 majority voting per bit; it does not support hardware flow control, other modem control signals, or synchronous serial data transfers.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.1")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-FORMAT"))) (param (name decision_id) (value (str "D-UART-FORMAT"))) (param (name source_semantics) (value (str "defined")))) (dependencies "REQ-D-UART-FORMAT") (required_checks "CHK-UART-FORMAT-POS") (required_checks "CHK-UART-FORMAT-NEG"))

(obligation (id "OB-UART-RESERVED") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The behaviour of the Reserved bit fields (txdata [30:8], rxdata [30:8], txctrl [15:2] and [31:19], rxctrl [15:1] and [31:19], ie [31:2], ip [31:2]) is not specified: the tables mark them Reserved with no read or write semantics.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "Tables 60–65")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-RESERVED"))) (param (name decision_id) (value (str "D-UART-RESERVED"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-RESERVED") (required_checks "CHK-UART-RESERVED-POS") (required_checks "CHK-UART-RESERVED-NEG"))

(obligation (id "OB-UART-RESET-X") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The reset values of txdata.full, rxdata.data, rxdata.empty, ip.txwm and ip.rxwm are unspecified: the tables mark their reset column X. The stated resets are txctrl = 0, rxctrl = 0, ie = 0 and div = div_init.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "Tables 60, 61, 65; §13.6, §13.7, §13.8, §13.9")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-RESET-X"))) (param (name decision_id) (value (str "D-UART-RESET-X"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-RESET-X") (required_checks "CHK-UART-RESET-X-POS") (required_checks "CHK-UART-RESET-X-NEG"))

(obligation (id "OB-UART-FIFO-RESET") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The transmit and receive FIFO contents and occupancies at reset are not specified: §13 gives register reset values only and no FIFO reset statement.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13 (whole chapter; the silence measured against §13.6–§13.9's explicit reset statements)")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-FIFO-RESET"))) (param (name decision_id) (value (str "D-UART-FIFO-RESET"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-FIFO-RESET") (required_checks "CHK-UART-FIFO-RESET-POS") (required_checks "CHK-UART-FIFO-RESET-NEG"))

(obligation (id "OB-UART-OFFMAP") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The effect of an access at an offset outside Table 59's seven registers within the instance's address window is not specified.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3, Table 59 (the map defines 0x00–0x18 only; the board's 0x1000 window is D-BOARD-MEMORY-MAP's)")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-OFFMAP"))) (param (name decision_id) (value (str "D-UART-OFFMAP"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-OFFMAP") (required_checks "CHK-UART-OFFMAP-POS") (required_checks "CHK-UART-OFFMAP-NEG"))

(obligation (id "OB-UART-WIDTH") (contract_id "sifive-uart-v0") (contract_version "0") (profile_ids "sifive-uart-lab-v0") (direction device-guarantee) (statement "The effect of an access that is not a naturally aligned 32-bit access is not specified: the map is 'designed to require only' such accesses, and the manual states no error or truncation behaviour for any other width or alignment.") (authority architecture) (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3")) (parameters (param (name requirement_id) (value (str "REQ-D-UART-WIDTH"))) (param (name decision_id) (value (str "D-UART-WIDTH"))) (param (name source_semantics) (value (str "unspecified")))) (dependencies "REQ-D-UART-WIDTH") (required_checks "CHK-UART-WIDTH-POS") (required_checks "CHK-UART-WIDTH-NEG"))
