;; requirements.sexp — the requirement catalogue for `sifive-uart-lab-v0` (P5-BOARD.2,
;; 2026-10-02). One (requirement …) per record. Validate:
;;   python3 scripts/check_sexp_schema.py profiles/sifive-uart-lab-v0/requirements.sexp schema/requirements.sexp
;; Every statement was read against the pinned artifact (sources.sexp); locators name the
;; manual's §13 sections and tables. The records whose source_semantics category is
;; `unspecified` are the datasheet's measured
;; silences, recorded as requirements of NON-commitment — a dossier that papers over an
;; unspecified case is describing a device the source does not define.

(requirement (id "REQ-D-UART-MAP") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "The UART register map is seven 32-bit registers — txdata 0x00, rxdata 0x04, txctrl 0x08, rxctrl 0x0C, ie 0x10, ip 0x14, div 0x18 — designed to require only naturally aligned 32-bit memory accesses.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3, Table 59")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "The manual states the offsets and the access rule outright; the model has no latitude.")) (risk low) (obligation_ids "OB-UART-MAP"))

(requirement (id "REQ-D-UART-INSTANCE") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "UART instance 0 is at base address 0x10010000 with div_width = 20, div_init = 289 and 8-entry transmit and receive FIFOs; instance 1 at 0x10011000 has identical parameters.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.2, Table 58")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in Table 58. The dossier models instance 0 — the board's uart0 (D-BOARD-MEMORY-MAP); instance 1 is out of scope, not absent.")) (risk low) (obligation_ids "OB-UART-INSTANCE"))

(requirement (id "REQ-D-UART-TXDATA-WRITE") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "Writing txdata enqueues the data field's character into the transmit FIFO if the FIFO can accept new entries; when the full flag is set, writes to data are ignored.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.4, Table 60")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.4.")) (risk medium) (obligation_ids "OB-UART-TXDATA-WRITE"))

(requirement (id "REQ-D-UART-TXDATA-READ") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "Reading txdata returns the current value of the full flag (bit 31) and zero in the data field; the full flag indicates whether the transmit FIFO can accept new entries.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.4, Table 60")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.4; the amoor.w read-modify-write idiom the manual names depends on exactly this shape.")) (risk medium) (obligation_ids "OB-UART-TXDATA-READ"))

(requirement (id "REQ-D-UART-RXDATA-READ") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "Reading rxdata dequeues a character from the receive FIFO and returns it in the data field; the empty flag (bit 31) indicates whether the receive FIFO was empty, and when set the data field does not contain a valid character.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.5, Table 61")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.5 — the read has the dequeue side effect, the sharpest side effect in the map.")) (risk high) (obligation_ids "OB-UART-RXDATA-READ"))

(requirement (id "REQ-D-UART-RXDATA-WRITE") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "Writes to rxdata are ignored.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.5")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.5.")) (risk low) (obligation_ids "OB-UART-RXDATA-WRITE"))

(requirement (id "REQ-D-UART-TXCTRL") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "txctrl is read-write: txen (bit 0) controls whether the Tx channel is active — when cleared, transmission of Tx FIFO contents is suppressed and the txd pin is driven high; nstop (bit 1) selects one (0) or two (1) stop bits; txcnt (bits [18:16]) is the transmit watermark threshold. txctrl resets to 0.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.6, Table 62")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.6, including the reset value.")) (risk medium) (obligation_ids "OB-UART-TXCTRL"))

(requirement (id "REQ-D-UART-RXCTRL") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "rxctrl is read-write: rxen (bit 0) controls whether the Rx channel is active — when cleared, the state of the rxd pin is ignored and no characters are enqueued into the Rx FIFO; rxcnt (bits [18:16]) is the receive watermark threshold. rxctrl resets to 0. Characters are enqueued when a zero (low) start bit is seen.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.7, Table 63")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.7, including the reset value.")) (risk medium) (obligation_ids "OB-UART-RXCTRL"))

(requirement (id "REQ-D-UART-IE") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "ie is read-write: txwm (bit 0) is the transmit watermark interrupt enable and rxwm (bit 1) is the receive watermark interrupt enable. ie resets to 0.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 64")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.8, including the reset value.")) (risk low) (obligation_ids "OB-UART-IE"))

(requirement (id "REQ-D-UART-IP") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "ip is read-only: txwm (bit 0) becomes raised when the number of entries in the transmit FIFO is strictly less than txcnt and is cleared when sufficient entries have been enqueued to exceed the watermark; rxwm (bit 1) becomes raised when the number of entries in the receive FIFO is strictly greater than rxcnt and is cleared when sufficient entries have been dequeued to fall below the watermark.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 65")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "§13.8's two sentences per bit, restated — the strict inequalities are the manual's own. What they leave open is REQ-D-UART-WM-MODE's, not this record's.")) (risk high) (obligation_ids "OB-UART-IP"))

(requirement (id "REQ-D-UART-WM-MODE") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "Whether an ip watermark bit is a pure level function of FIFO occupancy or holds its value between its raised and cleared conditions is not specified: §13.8 gives each bit a strict-inequality raised condition and a strict-inequality cleared condition, so the == boundary and any value before a condition first holds — including after reset, where the bits are X — are undetermined.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.8, Table 65 (the two strict sentences per bit; the gap measured against them)")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "A polled driver may not rely on the bit at the == boundary nor before the first raise/clear; the safe pattern is to drain rxdata to empty and to fill txdata to full rather than trust the watermark bit (the board's drivers poll, D-BOARD-NO-TIMER-IRQ). A public reference implementation (QEMU's sifive_uart) computes both bits combinationally — an independent reading, not a source.")) (risk high) (obligation_ids "OB-UART-WM-MODE"))

(requirement (id "REQ-D-UART-DIV") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "div is a read-write div_width-bit register (div_width = 20) specifying the divisor used by baud-rate generation for both channels; its reset value is div_init = 289, tuned to provide 115200 baud out of reset given the expected tlclk frequency, and the divide ratio is one greater than the value stored in div.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.9, Table 58, Table 66")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "§13.9 states width, reset and the 115200 tuning outright; the div+1 relationship is Table 66's own note ('the divide ratios … are one greater than the value stored in the div register'), cross-checked against its rows (500 MHz / 4340 = 115207 baud, the table's 115200 / 0.0064% row). §13.9's formula itself is a rendered image in the PDF; the derivable statement is the table note.")) (risk medium) (obligation_ids "OB-UART-DIV"))

(requirement (id "REQ-D-UART-FIFO-DEPTH") (profile_ids "sifive-uart-lab-v0") (kind state) (statement "The transmit and receive FIFOs are 8 entries each.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.1, Table 58")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.1's feature list and in both instance rows of Table 58.")) (risk medium) (obligation_ids "OB-UART-FIFO-DEPTH"))

(requirement (id "REQ-D-UART-FORMAT") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "The UART supports 8-N-1 and 8-N-2 formats — 8 data bits, no parity, 1 start bit, 1 or 2 stop bits — with 16x Rx oversampling and 2/3 majority voting per bit; it does not support hardware flow control, other modem control signals, or synchronous serial data transfers.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.1")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "Stated outright in §13.1 — the absences (flow control, modem signals, synchronous mode) are stated as absences by the manual itself.")) (risk low) (obligation_ids "OB-UART-FORMAT"))

(requirement (id "REQ-D-UART-RESERVED") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "The behaviour of the Reserved bit fields (txdata [30:8], rxdata [30:8], txctrl [15:2] and [31:19], rxctrl [15:1] and [31:19], ie [31:2], ip [31:2]) is not specified: the tables mark them Reserved with no read or write semantics.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "Tables 60–65")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "The datasheet is silent; the device contract makes no claim. An implementation may choose read-zero/write-ignored, but that choice is laboratory, never architecture.")) (risk medium) (obligation_ids "OB-UART-RESERVED"))

(requirement (id "REQ-D-UART-RESET-X") (profile_ids "sifive-uart-lab-v0") (kind state) (statement "The reset values of txdata.full, rxdata.data, rxdata.empty, ip.txwm and ip.rxwm are unspecified: the tables mark their reset column X. The stated resets are txctrl = 0, rxctrl = 0, ie = 0 and div = div_init.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "Tables 60, 61, 65; §13.6, §13.7, §13.8, §13.9")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "The manual's own reset columns; an expected result may not pin an X-marked value, however physically plausible (an empty FIFO implying full = 0) — plausibility is not a source.")) (risk high) (obligation_ids "OB-UART-RESET-X"))

(requirement (id "REQ-D-UART-FIFO-RESET") (profile_ids "sifive-uart-lab-v0") (kind state) (statement "The transmit and receive FIFO contents and occupancies at reset are not specified: §13 gives register reset values only and no FIFO reset statement.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13 (whole chapter; the silence measured against §13.6–§13.9's explicit reset statements)")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "The chapter states resets for txctrl/rxctrl/ie/div and marks the flag bits X; it never says the FIFOs reset empty. Consistent with REQ-D-UART-RESET-X, not proof of it.")) (risk high) (obligation_ids "OB-UART-FIFO-RESET"))

(requirement (id "REQ-D-UART-OFFMAP") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "The effect of an access at an offset outside Table 59's seven registers within the instance's address window is not specified.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3, Table 59 (the map defines 0x00–0x18 only; the board's 0x1000 window is D-BOARD-MEMORY-MAP's)")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "The datasheet defines the seven offsets and nothing beyond them.")) (risk medium) (obligation_ids "OB-UART-OFFMAP"))

(requirement (id "REQ-D-UART-WIDTH") (profile_ids "sifive-uart-lab-v0") (kind device) (statement "The effect of an access that is not a naturally aligned 32-bit access is not specified: the map is 'designed to require only' such accesses, and the manual states no error or truncation behaviour for any other width or alignment.") (source_refs (source_id "SIFIVE-FU540-C000") (locator "§13.3")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category unspecified) (detail "A design requirement on the accessor, not a defined device behaviour. The board dispositions it: D-BOARD-ACCESS-POLICY makes any other width a board-reported contract violation, never a silently serviced access — so the composition needs no invented device behaviour here.")) (risk high) (obligation_ids "OB-UART-WIDTH"))
