;; requirements.sexp — the requirement catalogue for `dsp56300-lab-v0` (P3-BREADTH.6 slice 1).
;; One record per profile decision — RECORD-SCHEMA's COVERAGE rule: every (decision …) in
;; profile.sexp carries a REQ-D-<id> whose statement is the decision's, byte-identical.
;; Validate with
;;   python3 scripts/check_sexp_schema.py profiles/dsp56300-lab-v0/requirements.sexp schema/requirements.sexp

(requirement (id "REQ-D-SUBSET-V0") (profile_ids "dsp56300-lab-v0") (kind configuration) (statement "Subset v0 is non-parallel moves (including the A2/B2 extension readout), the immediate/register data-ALU core, signed mpy/mac, nop/jmp/jsr/rts, do/enddo/rep, and linear addressing only; every exclusion is named with its reason in the selection record.") (source_refs (source_id "DSP56300FM") (locator "§13 (the instruction set the subset is drawn from)")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category implementation-defined) (detail "The architecture defines the full DSP56300 instruction set; the subset boundary is the laboratory's declared choice over it (decision_dsp56300-lab-v0-subset), and no claim is made beyond the boundary.")) (risk high) (obligation_ids "OB-SUBSET-V0"))
(requirement (id "REQ-D-ACC-READOUT") (profile_ids "dsp56300-lab-v0") (kind state) (statement "A2/B2 read as the sign-extended extension byte; A1/B1 read RAW — the shifter/limiter sits on the whole-accumulator read path only (measured: the alu guest stores $FE00FF from A1 with L clear; the FM's limiting prose over-applies to the A1/B1 path).") (insns "move") (source_refs (source_id "DSP56300FM") (locator "§3.4.1.2")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "The FM defines the extension-byte readout; where its limiting prose over-applies to the A1/B1 path the truth was settled by measurement against the pinned reference (P3-BREADTH.4 slice 4) — the correction is recorded in the statement, not silently adopted.")) (risk high) (obligation_ids "OB-ACC-READOUT") (dependencies "REQ-D-SUBSET-V0"))
(requirement (id "REQ-D-SHORTIMM-ACC") (profile_ids "dsp56300-lab-v0") (kind instruction) (statement "A short immediate moved to a whole accumulator sign-extends the 8-bit signed fraction through the extension byte — the FM's 'the remaining bits are zeroed' (13-113) does NOT hold for A2 (measured: move #$80,a leaves A2=$FF).") (insns "move") (source_refs (source_id "DSP56300FM") (locator "§3.4.1.3 / 13-113")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "The FM states the short-immediate rule, and its 'remaining bits are zeroed' clause was measured NOT to hold for A2 against the pinned reference (P3-BREADTH.4 slice 4); the statement carries the measured truth with the FM's text quoted for contrast.")) (risk high) (obligation_ids "OB-SHORTIMM-ACC") (dependencies "REQ-D-ACC-READOUT"))
(requirement (id "REQ-D-RTS-PC-ONLY") (profile_ids "dsp56300-lab-v0") (kind instruction) (statement "RTS restores PC only (SSH → PC; SP − 1 → SP); SR is NOT pulled — that is RTI's shape (13-167).") (insns "rts") (source_refs (source_id "DSP56300FM") (locator "13-167, 13-168")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "The FM defines RTS and RTI as distinct forms; the PC-only truth is pinned by the jsr guest (U survives both returns) against the pinned reference.")) (risk medium) (obligation_ids "OB-RTS-PC-ONLY") (dependencies "REQ-D-SUBSET-V0"))
(requirement (id "REQ-D-SBIT-LOCUS") (profile_ids "dsp56300-lab-v0") (kind state) (statement "The sticky S bit sets only on whole-accumulator reads to the XDB/YDB bus; subset v0 decodes no such read, so S never leaves reset (measured: an ASR of a negative accumulator does not set it).") (source_refs (source_id "DSP56300FM") (locator "Table 5-1")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category defined) (detail "The FM's CCR table names S's setting condition; the locus (whole-accumulator bus reads only) was measured against the pinned reference (P3-BREADTH.4 slice 4).")) (risk medium) (obligation_ids "OB-SBIT-LOCUS") (dependencies "REQ-D-SUBSET-V0"))
(requirement (id "REQ-D-COMPARISON") (profile_ids "dsp56300-lab-v0") (kind environment) (statement "The comparison surface is checkpoint-level canonical end-state equality against the pinned reference's difftest dump: registers, deviation-encoded X/Y windows, 15 stack slots; steps compared, cyc never (timing is informational upstream).") (source_refs (source_id "DSP56300FM") (locator "§3, §5 (the architectural state the dump captures); the surface itself is references.sexp's trace_granularity")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category implementation-defined) (detail "The comparison surface is the laboratory's declared evidence contract, not an architectural fact; the FM anchors only which state exists to be compared.")) (risk high) (obligation_ids "OB-COMPARISON") (dependencies "REQ-D-SUBSET-V0"))
(requirement (id "REQ-D-RESET-STATE") (profile_ids "dsp56300-lab-v0") (kind state) (statement "Reset: SR $C00300 (CP=11, I1=I0=1, CCR clear), OMR $000300, LA and all M registers $FFFFFF, everything else zero; pc is set by the runner from the case's load base.") (source_refs (source_id "DSP56300FM") (locator "Table 5-1 and §3/§5 reset states")) (applicability included) (research_status resolved) (implementation_status planned) (source_semantics (category implementation-defined) (detail "The FM defines the reset values; the entry pc is the harness's declaration (the case's load base), cross-checked against the reference's observed reset dump.")) (risk medium) (obligation_ids "OB-RESET-STATE") (dependencies "REQ-D-SUBSET-V0"))
