;; sources.sexp — pinned specification sources for `dsp56300-lab-v0` (P3-BREADTH.4).
;; One document form; validate with
;;   python3 scripts/check_sexp_schema.py profiles/dsp56300-lab-v0/sources.sexp schema/sources.sexp
;; Re-derive with `scripts/fetch_sources.sh [--verify-only] dsp56300-lab-v0` (needs the
;; network; deliberately NOT a commit gate).

(comment "profiles/dsp56300-lab-v0/sources.sexp — the pinned specification sources for the bounded" "DSP56300 subset (decision_dsp56300-lab-v0-subset)." "" "⛔ THE PUBLICATION IS PART OF THE IDENTITY. `Rev. 5` identifies nothing on its own: the same" "PDF circulates on third-party mirror sites, and the pin here is NXP's own reference-manual" "locator. The manual's cover names the family 'DSP56300 16-Bit Digital Signal Processor' — a" "historical marketing name; the datapath this profile models is 24-bit, and the title is" "recorded verbatim because an identity is not edited for sense." "" "TWO ACQUISITION ROUTES, ONE ARTIFACT, byte-equality VERIFIED `2026-10-01`: the materials" "corpus holds the same manual as NXP-DSP56300-FAMILY-MANUAL (cache-path" "nxp/dsp56300-family-manual.pdf, adopted through the chipdoc channel, sha256 b2e8e346…), and" "a fresh fetch from the pinned base_url returned exactly those bytes (24,396,254 B, HTTP 200)." "The corpus copy is the offline fallback; the fetch ledger below is the re-derivation route." "" "Terms: unrecorded in the materials catalog (`licence-evidence` there says why). The artifact" "is READ, not redistributed — fetched into the untracked `target/sources/` working area and" "no copy is committed. SRC-01 requires the actual terms before the artifact is relied on for" "anything shipped; that obligation stands.")

(sources (publication "DSP56300 Family Manual (DSP56300FM) — NXP reference manuals, nxp.com") (not_this_publication "third-party PDF mirrors of the same manual — the pin is NXP's own locator") (revision "Rev. 5, April 2005") (base_url "https://www.nxp.com/docs/en/reference-manual") (retrieved "2026-10-01") (work_dir "target/sources/dsp56300-lab-v0") (comment "repo-volume, untracked") (source (id "DSP56300FM") (file "DSP56300FM.pdf") (title "DSP56300 16-Bit Digital Signal Processor Family Manual, Rev. 5 (April 2005)") (chapter_version "Rev. 5") (sha256 "b2e8e346fe55b05d20ad0e6bc03d45fd1e080d46d9a9cd9540271c0c37f5a31e") (bytes 24396254) (http_status 200) (supplies "the whole DSP56300 family architecture the subset is drawn from: 24-bit P/X/Y words, the 56-bit accumulators A2:A1:A0 with the 8-bit extension and its readout (§3.4.1.3's short-immediate rule was already load-bearing in the path demo), the data ALU and its CCR effects, the AGU address-generation forms, the DO/REP loop machinery, and the encoding space every dsp56300-lab-v0 decode/semantics citation resolves against")))
