;; references.sexp — the schema for a reference candidate dossier (references.sexp).
;;
;; `SOT-FORMAT.4`: the retired references.toml is one document form. A candidate list is the
;; easiest document to fill from reputation, so the load-bearing fields (role, status,
;; origin, lineage) are required here and PROFILE-CONSISTENCY's 39 arms enforce the rest —
;; an `obtained` claim must name a binary and its digest, an agreement must record the
;; control that was observed failing, and every compared pair must have an independence
;; row. `sha256` fields carry the 64-hex facet. The dossier's extensive ⚠️ commentary
;; survives conversion as (comment "…") forms — first-class, never dropped.

(schema (id "references"))

(construct (name references)
  (field (name profile) (type string) (min-length 1))
  (field (name retrieved) (type string) (min-length 1))
  (field (name work_dir) (type string) (min-length 1))
  (field (name host) (type form) (head host))
  (field (name candidate) (type form) (head candidate) (repeat yes) (min 1))
  (field (name attempt) (type form) (head attempt) (repeat yes))
  (field (name experiment) (type form) (head experiment) (repeat yes))
  (field (name difference) (type form) (head difference) (repeat yes))
  (field (name independence) (type form) (head independence) (repeat yes))
  (field (name encoding_source) (type form) (head encoding_source) (repeat yes)))

(construct (name host)
  (field (name os) (type string) (min-length 1))
  (field (name kernel) (type string) (min-length 1))
  (field (name arch) (type string) (min-length 1))
  (field (name cxx) (type string) (min-length 1))
  (field (name note) (type string) (optional yes)))

(construct (name candidate)
  (field (name id) (type string) (min-length 1))
  (field (name role) (type string) (min-length 1))
  (field (name status) (type string) (min-length 1))
  (field (name kind) (type string) (optional yes))
  (field (name origin) (type string) (min-length 1))
  (field (name release) (type string) (optional yes))
  (field (name released) (type string) (optional yes))
  (field (name asset) (type string) (optional yes))
  (field (name asset_sha256) (type string) (optional yes) (pattern "^[0-9a-f]{64}$"))
  (field (name asset_bytes) (type integer) (optional yes))
  (field (name http_status) (type integer) (optional yes))
  (field (name binary) (type string) (optional yes))
  (field (name binary_sha256) (type string) (optional yes) (pattern "^[0-9a-f]{64}$"))
  (field (name build_info) (type string) (optional yes))
  (field (name version) (type string) (optional yes))
  (field (name source_commit) (type string) (optional yes))
  (field (name source_authored) (type string) (optional yes))
  (field (name release_assets) (type string) (optional yes))
  (field (name build_prefix) (type string) (optional yes))
  (field (name build_note) (type string) (optional yes))
  (field (name invocation) (type string) (optional yes))
  (field (name trace_granularity) (type string) (optional yes))
  (field (name injection) (type string) (optional yes))
  (field (name matched_config) (type string) (optional yes))
  (field (name matched_isa_string) (type string) (optional yes))
  (field (name matched_isa_string_source) (type string) (optional yes))
  (field (name matched_scope) (type string) (optional yes))
  (field (name terms) (type string) (optional yes))
  (field (name lineage) (type string) (min-length 1))
  (field (name default_branch) (type string) (optional yes))
  (field (name tags_listed) (type integer) (optional yes))
  (field (name tag_shape) (type string) (optional yes))
  (field (name status_reason) (type string) (optional yes))
  (field (name license) (type string) (optional yes))
  (field (name cross_volume) (type string) (optional yes))
  (field (name redirect_note) (type string) (optional yes))
  (field (name last_pushed) (type string) (optional yes)))

(construct (name attempt)
  (field (name what) (type string) (min-length 1))
  (field (name command) (type string) (optional yes))
  (field (name outcome) (type string) (min-length 1))
  (field (name consequence) (type string) (min-length 1)))

(construct (name experiment)
  (field (name id) (type string) (min-length 1))
  (field (name program) (type string) (min-length 1))
  (field (name instructions) (type integer))
  (field (name models) (type string) (repeat yes) (min 1))
  (field (name sail_invocation) (type string) (optional yes))
  (field (name spike_invocation) (type string) (optional yes))
  (field (name elf_sha256) (type string) (optional yes))
  (field (name verdict) (type string) (min-length 1))
  (field (name expectations) (type string) (optional yes))
  (field (name reproduced) (type string) (min-length 1))
  (field (name exercises) (type string) (optional yes))
  (field (name control) (type string) (min-length 1)))

(construct (name difference)
  (field (name id) (type string) (min-length 1))
  (field (name kind) (type string) (min-length 1))
  (field (name observed) (type string) (min-length 1))
  (field (name resolution) (type string) (min-length 1)))

(construct (name independence)
  (field (name subsystem) (type string) (min-length 1))
  (field (name pair) (type string) (repeat yes) (min 2))
  (field (name verdict) (type string) (min-length 1))
  (field (name evidence) (type string) (min-length 1))
  (field (name consequence) (type string) (min-length 1)))

(construct (name encoding_source)
  (field (name id) (type string) (min-length 1))
  (field (name origin) (type string) (min-length 1))
  (field (name license) (type string) (min-length 1))
  (field (name retrieved) (type string) (min-length 1))
  (field (name work_dir) (type string) (min-length 1))
  (field (name supplies) (type string) (min-length 1))
  (field (name note) (type string) (optional yes))
  (field (name file) (type form) (head file) (repeat yes) (min 1)))

(construct (name file)
  (field (name name) (type string) (min-length 1))
  (field (name sha256) (type string) (pattern "^[0-9a-f]{64}$"))
  (field (name bytes) (type integer)))
