#!/usr/bin/env bash
# scripts/check_m_vectors.sh — M-VECTORS (project doctrine; P4-SYSTEM.11 slice c1).
#
# `crates/semulith-verify/src/m_vectors/vectors.txt` — the M extension's instruction vectors,
# run through the ENGINE by `m_vectors/tests.rs` — is GENERATED by `scripts/gen_m_vectors.py`
# from its spec-side exact-integer reference (RVI-M §11.1, Table 1 tested by name). This check
# regenerates the table in memory and refuses the day it stops byte-matching the tracked file:
# an expected value edited by hand to make a test pass is a spec-side claim replaced by an
# engine-side one (EVD-05's failure), and DRIFT is how it shows.
#
# ⭐ IT ALSO JUDGES THE REFERENCE (the FP-VECTORS precedent: a generator whose oracle drifted
# would regenerate a wrong table perfectly). The reference's results are re-checked on seeded
# and edge operands against the CHAPTER'S OWN SENTENCES, not against a second formula:
# "dividend = divisor × quotient + remainder" except on overflow; the remainder smaller than the
# divisor in magnitude; "the sign of a nonzero result equals the sign of the dividend"; Table 1's
# zero-divisor and overflow rows; the high and low halves recomposing the exact 2·XLEN product;
# the word forms "sign-extend the 32-bit result".
#
# ⚠️ HONEST LIMIT: it proves the table is the reference's and the reference obeys the chapter's
# stated identities; the engine's agreement with the table is the test's (`cargo test`), and
# what the identities do not state, nothing here states.
#
# CONTRACT: exit code is the verdict; explains on stderr; deterministic; read-only; no network.
#   --self-test   run the RED/GREEN controls and exit.
set -uo pipefail
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
command -v python3 >/dev/null 2>&1 || {
  echo "M-VECTORS: REFUSED — python3 is not on PATH; this check cannot judge." >&2; exit 2; }

judge() { # judge <generator> <table> — prints findings, exits 1 on any, 0 when clean
python3 - "$1" "$2" <<'PY'
import importlib.util, random, sys
from pathlib import Path
gen_path, table = Path(sys.argv[1]), Path(sys.argv[2])
spec = importlib.util.spec_from_file_location("gen_m_vectors", gen_path)
G = importlib.util.module_from_spec(spec); spec.loader.exec_module(G)
findings = []
text = G.table()
drift = not table.is_file() or table.read_text() != text
if drift:
    findings.append(f"DRIFT {table}: not the generator's output — regenerate (python3 scripts/gen_m_vectors.py), never edit")
M64 = (1 << 64) - 1
def s(v, n): v &= (1 << n) - 1; return v - (1 << n) if v >> (n - 1) else v
rng = random.Random(0x4D56)                      # an operand set the table does not use
ops = list(G.EDGES) + [rng.getrandbits(64) for _ in range(120)] + [rng.randrange(1, 64) for _ in range(8)]
ops += [(-x) & M64 for x in ops[-8:]]
def R(mn, a, b): return G.reference(mn, a, b)
for a in ops:
    for b in ops[:48]:
        for L, sfx in ((64, ""), (32, "w")):
            ua, ub, sa, sb = a & ((1 << L) - 1), b & ((1 << L) - 1), s(a, L), s(b, L)
            q, r = s(R("div" + sfx, a, b), 64), s(R("rem" + sfx, a, b), 64)
            qu, ru = R("divu" + sfx, a, b), R("remu" + sfx, a, b)
            if L == 32:                          # the word forms sign-extend the 32-bit result
                for v, n in ((q, "div"), (r, "rem")):
                    if v != s(v, 32): findings.append(f"NOT SIGN-EXTENDED {n}w {a:#x} {b:#x}")
                qu, ru = s(qu, 64), s(ru, 64)
                if s(qu, 32) != qu or s(ru, 32) != ru: findings.append(f"NOT SIGN-EXTENDED divuw/remuw {a:#x} {b:#x}")
                qu, ru = qu & 0xFFFF_FFFF, ru & 0xFFFF_FFFF
            if sb == 0:
                if q != -1 or r != sa: findings.append(f"TABLE 1 (zero divisor, signed) {L} {a:#x}: q={q} r={r}")
                if qu != (1 << L) - 1 or ru != ua: findings.append(f"TABLE 1 (zero divisor, unsigned) {L} {a:#x}")
                continue
            if sa == -(1 << (L - 1)) and sb == -1:
                if q != sa or r != 0: findings.append(f"TABLE 1 (overflow) {L}: q={q} r={r}")
            else:
                if sb * q + r != sa: findings.append(f"IDENTITY div/rem {L} {a:#x} {b:#x}: {sb}*{q}+{r} != {sa}")
                if abs(r) >= abs(sb): findings.append(f"REMAINDER TOO LARGE {L} {a:#x} {b:#x}")
                if r and (r < 0) != (sa < 0): findings.append(f"REMAINDER SIGN {L} {a:#x} {b:#x}: r={r}, dividend {sa}")
            if ub * qu + ru != ua or ru >= ub: findings.append(f"IDENTITY divu/remu {L} {a:#x} {b:#x}")
        lo = R("mul", a, b)
        if (R("mulhu", a, b) << 64 | lo) != a * b: findings.append(f"PRODUCT mulhu:mul {a:#x} {b:#x}")
        if s(R("mulh", a, b), 64) * (1 << 64) + lo != s(a, 64) * s(b, 64): findings.append(f"PRODUCT mulh:mul {a:#x} {b:#x}")
        if s(R("mulhsu", a, b), 64) * (1 << 64) + lo != s(a, 64) * b: findings.append(f"PRODUCT mulhsu:mul {a:#x} {b:#x}")
        if s(R("mulw", a, b), 64) != s(s(a, 32) * s(b, 32), 32): findings.append(f"PRODUCT mulw {a:#x} {b:#x}")
for f in findings[:12]:
    print("  " + f)
print(f"M-VECTORS: {'FAIL' if findings else 'ok'} ({text.count(chr(10)) - 7} vectors "
      f"{'DRIFTED from' if drift else 'in sync with'} the generator; "
      f"the reference judged on {len(ops)}x48 operand pairs at both widths; {len(findings)} finding(s))")
sys.exit(1 if findings else 0)
PY
}

# ── self-test ────────────────────────────────────────────────────────────────────────────────
SELFTEST_TMP() { local d="$ROOT/target/doctrine-selftest"; mkdir -p "$d"; mktemp -d "$d/XXXXXX"; }
self_test() {
  local t pass=0 fail=0 out rc
  t="$(SELFTEST_TMP)"
  # ⛔ STRICT ARITY (docs/knowledge/self-test-arms-that-never-ran.md).
  argc() {
    [ "$2" -eq "$1" ] && return 0
    fail=$((fail+1))
    printf 'M-VECTORS self-test HARNESS: %s() got %s argument(s), expected %s — a missing `;` before `arm` swallows it\n' \
      "$3" "$2" "$1" >&2
    return 1
  }
  arm() { # arm <name> <rc> <expected-rc> <output> <reason substring>
    argc 5 "$#" arm || return
    if [ "$2" = "$3" ] && printf '%s' "$4" | grep -qF -- "$5"; then
      pass=$((pass+1))
    else
      fail=$((fail+1))
      printf 'M-VECTORS self-test MISS: %s — expected rc=%s (reason: %s), got rc=%s\n%s\n' \
        "$1" "$3" "$5" "$2" "$4" >&2
    fi
  }
  # Controls over COPIES (never the live files), each judged against a table the copy itself
  # generated — so a live tree out of sync cannot mask a control (the P4-SYSTEM.9 lesson).
  cp scripts/gen_m_vectors.py "$t/gen.py"
  python3 "$t/gen.py" --out "$t/table.txt" >/dev/null
  out="$(judge "$t/gen.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "GREEN the generator's own table, its reference obeying the chapter" "$rc" 0 "$out" "0 finding(s)"
  sed -i '0,/^div 8000000000000000 ffffffffffffffff 8000000000000000$/s//div 8000000000000000 ffffffffffffffff 0/' "$t/table.txt"
  out="$(judge "$t/gen.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "RED a hand-edited vector (the overflow quotient) is DRIFT" "$rc" 1 "$out" "DRIFT"
  python3 "$t/gen.py" --out "$t/table.txt" >/dev/null
  sed 's/    return q if (a < 0) == (b < 0) else -q/    return a \/\/ b/' scripts/gen_m_vectors.py > "$t/floor.py"
  out="$(judge "$t/floor.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "RED a reference that FLOORS (Python's //) breaks the remainder's sign rule" "$rc" 1 "$out" "REMAINDER SIGN"
  sed 's/        r = -1 if sb == 0 else/        r = 0 if sb == 0 else/' scripts/gen_m_vectors.py > "$t/zero.py"
  out="$(judge "$t/zero.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "RED a reference whose zero divisor yields 0 breaks Table 1" "$rc" 1 "$out" "TABLE 1 (zero divisor, signed)"
  sed 's/        r = (sa \* ub) >> 64/        r = (sa * sb) >> 64/' scripts/gen_m_vectors.py > "$t/hsu.py"
  out="$(judge "$t/hsu.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "RED a reference reading MULHSU's rs2 signed breaks the product split" "$rc" 1 "$out" "PRODUCT mulhsu:mul"
  sed 's/    if word:                                              # "sign-extend the 32-bit result"/    if False:/' scripts/gen_m_vectors.py > "$t/noext.py"
  out="$(judge "$t/noext.py" "$t/table.txt" 2>&1)"; rc=$?
  arm "RED a reference that does not sign-extend the word result" "$rc" 1 "$out" "NOT SIGN-EXTENDED"
  rm -rf "$t"
  printf 'M-VECTORS --self-test: %d pass / %d fail\n' "$pass" "$fail"
  [ "$fail" -eq 0 ]
}
if [ "${1:-}" = "--self-test" ]; then
  self_test
  exit $?
fi
# Judge FIRST: a finding is a verdict on its own; only a PASS needs the controls' proof.
out="$(judge scripts/gen_m_vectors.py crates/semulith-verify/src/m_vectors/vectors.txt 2>&1)"; rc=$?
if [ "$rc" -ne 0 ]; then
  printf '%s\n' "$out" >&2
  exit 1
fi
self_test >/dev/null 2>&1 || {
  echo "M-VECTORS: REFUSED — the check does not discriminate (self-test failed)." >&2
  exit 2; }
printf '%s\n' "$out"
