#!/usr/bin/env bash
# scripts/check_fp_vectors.sh — FP-VECTORS (project doctrine; P4-SYSTEM.7 slice c4).
#
# `crates/semulith-core/src/fp/tests/vectors.rs` — the floating-point model layer's unit
# vectors — is GENERATED by `scripts/gen_fp_vectors.py` from the spec-side exact-rational IEEE
# reference `scripts/specfp.py` (fractions/decimal: neither SoftFloat, the backend, nor MPFR).
# This check regenerates the table in memory and refuses the day it stops byte-matching the
# tracked file: an expected value edited by hand to make a test pass is a spec-side claim
# replaced by an engine-side one (EVD-05's failure), and DRIFT is how it shows.
#
# ⭐ IT ALSO JUDGES THE REFERENCE. A generator whose oracle drifted would regenerate a wrong table
# perfectly; so the reference's round-to-nearest-even add/mul/div/sqrt are re-checked on every
# run against the host's hardware IEEE (Python floats — an independent lineage), 400 seeded
# binary64 cases — and, since P4-SYSTEM.7 slice (d3), its format conversions (double -> single
# narrowing in RNE with directed ties, single -> double exact). Founding failure (slice c4): the slice-(a) MPFR oracle judged overflow on the
# EXACT magnitude and underflow on the DELIVERED result — both against IEEE 754-2008 §7.4/§7.5 —
# and agreed with the backend because it shared the backend's convention.
#
# ⚠️ HONEST LIMIT: the hardware cross-check covers RNE only (the host exposes no other mode
# from Python); the directed modes rest on the reference's rules as written and on the
# 63,480-case agreement with the model layer recorded in P4-SYSTEM.7 slice (c4).
#
# CONTRACT: exit code is the verdict; explains on stderr; deterministic; read-only; no network.
#   --self-test   run the RED/GREEN controls and exit.
set -uo pipefail
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"

command -v python3 >/dev/null 2>&1 || {
  echo "FP-VECTORS: REFUSED — python3 is not on PATH; this check cannot judge." >&2; exit 2; }

GEN="scripts/gen_fp_vectors.py"
OUT="crates/semulith-core/src/fp/tests/vectors.rs"

# The reference against the host's hardware IEEE, RNE (prints "agree N" or the first miss).
hardware_crosscheck() { # hardware_crosscheck <scripts-dir>
python3 - "$1" <<'PY'
import math, random, struct, sys
sys.path.insert(0, sys.argv[1])
import specfp as S
def f(b): return struct.unpack("<d", struct.pack("<Q", b))[0]
random.seed(20261006)
agree = 0
# directed EXACT TIES first — random operands almost never land on one, and a tie rule is
# exactly what a drifted reference gets wrong (measured: a half-up mutation survived 1,313
# random cases): 1 + 2^-53 and (1+2^-52) + 2^-53 (normal, to even both ways), and
# min-subnormal × 0.5 / 3·min-subnormal × 0.5 (subnormal ties, to even)
directed = [(0x3FF0000000000000, 0x3CA0000000000000), (0x3FF0000000000001, 0x3CA0000000000000),
            (0x0000000000000001, 0x3FE0000000000000), (0x0000000000000003, 0x3FE0000000000000)]
pairs = directed + [(random.getrandbits(64), random.getrandbits(64)) for _ in range(400)]
for a, b in pairs:
    x, y = f(a), f(b)
    if math.isnan(x) or math.isnan(y) or math.isinf(x) or math.isinf(y):
        continue
    for name, host in (("add", lambda: x + y), ("mul", lambda: x * y),
                       ("div", lambda: x / y if y != 0 else None)):
        h = host()
        if h is None or math.isinf(h) or math.isnan(h):
            continue
        got, _ = getattr(S, name)(64, S.RNE, a, b)
        if got != S.dbits(h):
            print(f"MISS {name} {a:#x} {b:#x}: reference {got:#x}, hardware {S.dbits(h):#x}")
            sys.exit(1)
        agree += 1
    if x > 0:
        got, _ = S.sqrt(64, S.RNE, a)
        if got != S.dbits(math.sqrt(x)):
            print(f"MISS sqrt {a:#x}: reference {got:#x}, hardware {S.dbits(math.sqrt(x)):#x}")
            sys.exit(1)
        agree += 1
# the format conversions (P4-SYSTEM.7 slice d3): double -> single in RNE is the host's own
# narrowing (struct "<f" packs a double through a C float conversion, ties to even), with
# directed ties (1 + 2^-24 to even below, 1 + 3*2^-24 to even above), the UF boundary and the
# minimum subnormal first, then doubles drawn inside and just outside single's range;
# single -> double is exact.
def f32(b): return struct.unpack("<f", struct.pack("<I", b))[0]
narrow = [0x3FF0000010000000, 0x3FF0000030000000, 0x380FFFFFE0000000, 0x0000000000000001]
for _ in range(400):
    e = random.randint(1023 - 152, 1023 + 127)
    narrow.append((random.getrandbits(1) << 63) | (e << 52) | random.getrandbits(52))
for a in narrow:
    try:
        h = struct.unpack("<I", struct.pack("<f", f(a)))[0]
    except OverflowError:
        continue
    got, _ = S.convert(32, 64, S.RNE, a)
    if got != h:
        print(f"MISS f2f d->s {a:#x}: reference {got:#x}, hardware {h:#x}")
        sys.exit(1)
    agree += 1
for _ in range(400):
    b = random.getrandbits(32)
    y = f32(b)
    if math.isnan(y):
        continue
    got, _ = S.convert(64, 32, S.RNE, b)
    if got != S.dbits(y):
        print(f"MISS f2f s->d {b:#x}: reference {got:#x}, hardware {S.dbits(y):#x}")
        sys.exit(1)
    agree += 1
print(f"agree {agree}")
PY
}

# ── self-test ────────────────────────────────────────────────────────────────────────────────
SELFTEST_TMP() { local d="$ROOT/target/doctrine-selftest"; mkdir -p "$d"; mktemp -d "$d/XXXXXX"; }

self_test() {
  local t pass=0 fail=0 out rc
  t="$(SELFTEST_TMP)"

  # ⛔ STRICT ARITY (docs/knowledge/self-test-arms-that-never-ran.md).
  argc() {
    [ "$2" -eq "$1" ] && return 0
    fail=$((fail+1))
    printf 'FP-VECTORS self-test HARNESS: %s() got %s argument(s), expected %s — a missing `;` before `arm` swallows it\n' \
      "$3" "$2" "$1" >&2
    return 1
  }
  arm() { # arm <name> <rc> <expected-rc> <output> <reason substring>
    argc 5 "$#" arm || return
    if [ "$2" = "$3" ] && printf '%s' "$4" | grep -qF -- "$5"; then
      pass=$((pass+1))
    else
      fail=$((fail+1))
      printf 'FP-VECTORS self-test MISS: %s — expected rc=%s (reason: %s), got rc=%s\n%s\n' \
        "$1" "$3" "$5" "$2" "$4" >&2
    fi
  }

  out="$(python3 "$GEN" --out "$t/vectors.rs" 2>&1)"; rc=$?
  arm "GREEN the generator emits the table" "$rc" 0 "$out" "wrote"
  out="$(python3 "$GEN" --check --out "$t/vectors.rs" 2>&1; echo "rc=$?")"; rc=0
  arm "GREEN a faithful regeneration is judged in sync" "$rc" 0 "$out" "rc=0"

  sed 's/bits: 0x3fb504f3, flags: 0x1/bits: 0x3fb504f4, flags: 0x1/' "$t/vectors.rs" > "$t/edited.rs"
  out="$(python3 "$GEN" --check --out "$t/edited.rs" 2>&1)"; rc=$?
  arm "RED an expected value edited by hand is refused as DRIFT" "$rc" 1 "$out" "DRIFT"

  printf '\n// one more row, by hand\n' >> "$t/vectors.rs"
  out="$(python3 "$GEN" --check --out "$t/vectors.rs" 2>&1)"; rc=$?
  arm "RED a hand-appended line is refused as DRIFT" "$rc" 1 "$out" "DRIFT"

  out="$(hardware_crosscheck scripts 2>&1)"; rc=$?
  arm "GREEN the reference agrees with the host's hardware IEEE (RNE)" "$rc" 0 "$out" "agree"

  # RED: the reference's round-half-even made round-half-UP (a mutated copy) — the hardware
  # cross-check must catch an oracle that drifted, not only a table that did.
  mkdir -p "$t/mut"
  sed 's/return fl + 1 if frac > half or (frac == half and fl % 2 == 1) else fl/return fl + 1 if frac >= half else fl/' \
    scripts/specfp.py > "$t/mut/specfp.py"
  if cmp -s scripts/specfp.py "$t/mut/specfp.py"; then
    fail=$((fail+1)); echo "FP-VECTORS self-test HARNESS: the mutation did not apply" >&2
  else
    out="$(hardware_crosscheck "$t/mut" 2>&1)"; rc=$?
    arm "RED a reference whose RNE ties round up is caught by the hardware" "$rc" 1 "$out" "MISS"
  fi

  rm -rf "$t"
  printf 'FP-VECTORS --self-test: %d pass / %d fail\n' "$pass" "$fail"
  [ "$fail" -eq 0 ]
}

if [ "${1:-}" = "--self-test" ]; then
  self_test
  exit $?
fi

self_test >/dev/null 2>&1 || {
  echo "FP-VECTORS: REFUSED — the check does not discriminate (self-test failed)." >&2
  exit 2; }

[ -f "$OUT" ] || { echo "FP-VECTORS: ok (no floating-point model layer yet)"; exit 0; }

out="$(python3 "$GEN" --check 2>&1)" || {
  printf '%s\n' "$out" >&2
  printf 'FP-VECTORS: FAIL — %s is not the spec-side reference'"'"'s output. Regenerate — never edit:\n  python3 scripts/gen_fp_vectors.py\n' "$OUT" >&2
  exit 1
}
xc="$(hardware_crosscheck scripts 2>&1)" || {
  printf '%s\n' "$xc" >&2
  echo "FP-VECTORS: FAIL — the spec-side reference disagrees with the host's hardware IEEE." >&2
  exit 1
}
rows="$(grep -c '^    Vector {' "$OUT")"
printf 'FP-VECTORS: ok (%s matches the spec-side reference, %s vectors; reference vs hardware RNE: %s)\n' \
  "$OUT" "$rows" "$xc"
exit 0
