#!/usr/bin/env python3
"""Author rv64gc expectations from spec-side rules (EVD-05), never engine outputs.

Promoted by P4-SYSTEM.12 d3a from the .11 producer, whose .4/.5/.7/.8/.9/.11 history
is recorded in the task-tree archives. The arithmetic, FP reference, CSR candidates,
reservation policy and data walks retain that producer's rules. This is a bounded
corpus author, not an ISA implementation or a conformance oracle: unknown shapes refuse.
C execution and translated parcel fetching support an explicit byte-addressed guest
route with a declared step budget. The tracked historical word-route corpus
contains the 42 records the promotion census regenerated byte-identically; other legacy
records retain their original authoring provenance and are not overwritten by this tool.

Usage: python3 scripts/derive_rv64gc_expectations.py [--check] guest.s ...
       python3 scripts/derive_rv64gc_expectations.py --check-owned
       python3 scripts/derive_rv64gc_expectations.py --parcels --steps N guest.s ...

Writes guest.expected.sexp unless --check/--check-owned requests a non-writing comparison.
A source directive overrides the stock derivation text and locator:
  addi x5, x0, 1  #: the marker begins at 1. | RVI-RV32I 1.1.4
Interpolation keys {old}/{new}/{addr}/{code} come from the spec-side computation.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sexp as _sexp  # noqa: E402
from riscv_asm import Assembler  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
import os  # noqa: E402
# A temporary composition may override the tracked unit for pre-bind authoring.
ENCODING = Path(os.environ.get("DERIVE_ENCODING",
                               REPO / "profiles/rv64gc-lab-v0/encoding.sexp"))
import spec_c as C  # noqa: E402 — independent spec-side C bit reconstruction
import specfp as SF  # noqa: E402  — the tracked spec-side IEEE reference (P4-SYSTEM.7 slice c4)
ENTRY = 0x8000_0000
REGION = 0x10000  # the tracked corpus's fixture: 64 KiB at the entry

M, S = 3, 1
CAUSE = {"misaligned_atomic": 7, "load_access": 5, "store_access": 7,
         "load_page": 13, "store_page": 15, "illegal": 2}


class Refusal(Exception):
    pass


def sx(v: int) -> str:
    return f"0x{v:016x}"


class Hart:
    """The spec-side hart: registers, memory, the CSRs the corpus touches, the
    reservation (the declared policy), and the Sv39 walk (the pinned 10 steps, Svade)."""

    def __init__(self):
        self.x = [0] * 32
        self.f = [0] * 32        # the f-file, FLEN = 64; the laboratory reset 0 (state.sexp)
        self.pc = ENTRY
        self.mode = M
        self.mem = {}
        self.csr = {"mtvec": 0, "mepc": 0, "mcause": 0, "mtval": 0, "mscratch": 0,
                    "mstatus": 0xA00000000, "medeleg": 0, "satp": 0, "sepc": 0, "scause": 0,
                    "stval": 0, "sscratch": 0, "mcounteren": 0, "scounteren": 0,
                    "mie": 0, "mip": 0, "mideleg": 0, "sie": 0, "sip": 0, "stimecmp": 0,
                    "fflags": 0, "frm": 0}   # fcsr is the composed VIEW, never storage
        self.time = 0            # the declared virtual-time domain (one tick per step)
        self.instret = 0         # the GENUINE retirement count (never for a trapped,
                                 # delivered or halted step — the engine's !frame.trapped)
        self.trapped = False     # set by any delivery this step (the instret discipline)
        self.waiting = False     # the hart wait state (decision 4), cold-ACTIVE at reset
        self.reservation = None   # (pa, width_bytes)
        self.log = []

    def read(self, addr, n):
        return sum(self.mem.get(addr + i, 0) << (8 * i) for i in range(n))

    def write(self, addr, n, v):
        for i in range(n):
            self.mem[addr + i] = (v >> (8 * i)) & 0xFF

    def in_region(self, addr, n):
        return ENTRY <= addr and addr + n <= ENTRY + REGION

    def refused(self, kind, addr, n):
        """A declared refusal region answers this request (P4-SYSTEM.8 slice c)."""
        return any(k == kind and addr < b + s and b < addr + n
                   for k, b, s in getattr(self, "refusals", ()))

    # ---- trap delivery (RVP-MACHINE §2.1.1.6.1, §2.1.1.8, §2.1.1.14-16) ----------------
    def deliver(self, cause, tval):
        self.trapped = True     # a trap-delivering step retires nothing (instret)
        from_mode = self.mode
        deleg = (self.csr["medeleg"] >> cause) & 1
        to_s = deleg and from_mode <= S
        if to_s:
            self.csr["sepc"] = self.pc & ~1
            self.csr["scause"] = cause
            self.csr["stval"] = tval
            mstatus = self.csr["mstatus"]
            mstatus = (mstatus & ~(1 << 5)) | (((mstatus >> 1) & 1) << 5)  # SPIE <- SIE
            mstatus &= ~(1 << 1)                                          # SIE <- 0
            mstatus = (mstatus & ~(1 << 8)) | ((1 if from_mode == S else 0) << 8)  # SPP
            self.csr["mstatus"] = mstatus
            self.pc = self.csr["mtvec"] & ~0  # stvec shares the programmed vector here
            self.pc = self.stvec()
        else:
            self.csr["mepc"] = self.pc & ~1
            self.csr["mcause"] = cause
            self.csr["mtval"] = tval
            mstatus = self.csr["mstatus"]
            mstatus = (mstatus & ~(1 << 7)) | (((mstatus >> 3) & 1) << 7)  # MPIE <- MIE
            mstatus &= ~(1 << 3)                                           # MIE <- 0
            mstatus = (mstatus & ~(0b11 << 11)) | (from_mode << 11)        # MPP
            self.csr["mstatus"] = mstatus
            self.pc = self.csr["mtvec"] & ~0b11
        self.mode = S if to_s else M

    def stvec(self):
        # the corpus programs ONE vector address through mtvec and reads it as stvec's
        # too (the laboratory guest convention — stvec is a distinct CSR the guests that
        # route to S program separately; see sv39-deleg's template)
        return self.csr.get("stvec", 0) & ~0b11

    def mip_value(self, which):
        """mip/sip with the live STIP overlay (time >= stimecmp — slice a's ticking
        domain; the SSIP/SEIP bits are storage)."""
        base = self.csr[which]
        stip = 1 if self.time >= self.csr["stimecmp"] else 0
        return (base & ~(1 << 5)) | (stip << 5)

    def wake_pending(self):
        """The WFI wake evaluation (decision 4, RVP-MACHINE §2.1.3.3): a locally-enabled
        pending interrupt at any privilege level, regardless of the global enables and
        of mideleg — exactly mip & mie != 0, mip with the live STIP overlay (the timer's
        arrival during the halt is the acceptance's wake source)."""
        return (self.mip_value("mip") & self.csr["mie"]) != 0

    def pending(self):
        """The (a)(b)(c) taken-rule at the step head (decision 3): the fixed priority
        walk MEI MSI MTI SEI SSI STI; the M-source bits read 0 in this platform."""
        for cause in (11, 3, 7, 9, 1, 5):
            bit = 1 << cause
            if not (self.mip_value("mip") & bit and self.csr["mie"] & bit):
                continue
            if self.csr["mideleg"] & bit:
                if self.mode == 3:
                    continue                     # the delegation mask: never in M
                if self.mode == 1 and ((self.csr["mstatus"] >> 1) & 1) == 0:
                    continue                     # S with SIE clear
                return (cause, True)
            else:
                if self.mode == 3 and ((self.csr["mstatus"] >> 3) & 1) == 0:
                    continue                     # M with MIE clear
                return (cause, False)
        return None

    def deliver_interrupt(self, cause, to_s):
        """Interrupt-caused delivery (decision 3): the Interrupt bit (63), xepc the
        un-fetched pc, the xPIE/xIE/xPP stack, the vector HONORING MODE."""
        self.trapped = True
        origin = self.mode
        code = cause | (1 << 63)
        if to_s:
            self.csr["sepc"] = self.pc & ~1
            self.csr["scause"] = code
            self.csr["stval"] = 0
            m = self.csr["mstatus"]
            sie = (m >> 1) & 1
            m = (m & ~(1 << 5)) | (sie << 5)
            m &= ~(1 << 1)
            m = (m & ~(1 << 8)) | ((1 if origin == 1 else 0) << 8)
            self.csr["mstatus"] = m
            self.mode = 1
            vec = self.csr.get("stvec", 0)
        else:
            self.csr["mepc"] = self.pc & ~1
            self.csr["mcause"] = code
            self.csr["mtval"] = 0
            m = self.csr["mstatus"]
            mie = (m >> 3) & 1
            m = (m & ~(1 << 7)) | (mie << 7)
            m &= ~(1 << 3)
            m = (m & ~(0b11 << 11)) | (origin << 11)
            self.csr["mstatus"] = m
            self.mode = 3
            vec = self.csr["mtvec"]
        base = vec & ~0b11
        self.pc = base + 4 * cause if vec & 0b11 == 1 else base

    # ---- the pinned 10-step Sv39 walk (RVP-SUPERVISOR §11.1.3.2, §11.1.4.1; Svade) ----
    def walk(self, va, kind):
        """kind in {'fetch','load','store','atomic'} -> ('pa', pa) or ('fault', cause)."""
        if kind not in ('fetch', 'load', 'store', 'atomic'):
            raise Refusal(f"walk kind {kind!r}: not in the declared access vocabulary")
        mode = self.mode
        if kind != 'fetch' and (self.csr['mstatus'] >> 17) & 1:
            mode = (self.csr['mstatus'] >> 11) & 3  # MPRV: data uses MPP, fetch never does
        satp_mode = self.csr['satp'] >> 60
        if mode == M or satp_mode == 0:
            return ("pa", va)
        if mode not in (0, S) or satp_mode != 8:
            raise Refusal(f"walk mode {mode}/satp.MODE {satp_mode}: outside the selected profile")
        cause = {"fetch": 12, "load": 13, "store": 15, "atomic": 15}[kind]
        expected_upper = (1 << 25) - 1 if (va >> 38) & 1 else 0
        if va >> 39 != expected_upper:
            return ("fault", cause)
        base = (self.csr["satp"] & ((1 << 44) - 1)) << 12
        vpn = [(va >> (12 + 9 * i)) & 0x1FF for i in range(3)]
        for level in (2, 1, 0):
            pte_addr = base + vpn[level] * 8
            self.log.append(('walk', pte_addr, 8))
            # an implicit walk read the environment refuses (outside the region, or a declared
            # walk refusal) is the ORIGINAL access's access fault (the engine's mapping;
            # P4-SYSTEM.8 slice c — the model read zeros there before, a page fault)
            if not self.in_region(pte_addr, 8) or self.refused("walk", pte_addr, 8):
                return ("fault", {"fetch": 1, "load": 5, "store": 7, "atomic": 7}[kind])
            pte = self.read(pte_addr, 8)
            v, r, w, x = pte & 1, (pte >> 1) & 1, (pte >> 2) & 1, (pte >> 3) & 1
            u, a, d = (pte >> 4) & 1, (pte >> 6) & 1, (pte >> 7) & 1
            # Svnapot/Svpbmt are absent; every PTE bit 63:54 must be zero.
            if not v or (not r and w) or pte >> 54:
                return ("fault", cause)
            if r or x:  # a leaf
                ppn2 = (pte >> 28) & ((1 << 26) - 1)
                ppn1 = (pte >> 19) & ((1 << 9) - 1)
                ppn0 = (pte >> 10) & ((1 << 9) - 1)
                if level == 2 and (ppn1 or ppn0):
                    return ("fault", cause)
                if level == 1 and ppn0:
                    return ("fault", cause)
                # RVP-SUPERVISOR 11.1.1.1.2 and translation step 6: SUM only
                # permits S data accesses to U pages; MXR also permits X-only loads.
                if mode == 0 and not u:
                    return ("fault", cause)
                if mode == S and u and (kind == "fetch" or not (self.csr["mstatus"] >> 18) & 1):
                    return ("fault", cause)
                if kind == "fetch" and not x:
                    return ("fault", cause)
                if kind == "load" and not (r or (x and (self.csr["mstatus"] >> 19) & 1)):
                    return ("fault", cause)
                if kind == "store" and not w:
                    return ("fault", cause)
                if kind == "atomic" and not (r and w):
                    return ("fault", cause)
                if not a or (kind in ("store", "atomic") and not d):
                    return ("fault", cause)  # Svade: page fault, never an update
                pa = (ppn2 << 30) | ((ppn1 if level <= 1 else (va >> 21) & 0x1FF) << 21) \
                    | ((ppn0 if level == 0 else (va >> 12) & 0x1FF) << 12) | (va & 0xFFF)
                return ("pa", pa)
            if pte & 0xd0:  # non-leaf U/A/D are reserved (RSW/G remain allowed)
                return ("fault", cause)
            if level == 0:
                return ("fault", cause)  # the pointer cannot descend below the final level
            base = ((pte >> 10) & ((1 << 44) - 1)) << 12
        raise AssertionError("three-level walk failed to produce a result")

    def fetch_instruction(self):
        """Fetch one instruction under C/ILEN=32; no retirement/time tick here.

        Returns ('insn', original_bits, length_bytes) or ('fault', cause, tval).
        A fault delivers with the instruction start as EPC and the failing parcel's
        VA as tval. Each necessary parcel walks before its exact two-byte request;
        log records actual boundary attempts, including refused requests. Memory in
        the declared region defaults to zero, even beyond the assembled payload.
        """
        def parcel(va):
            translated = self.walk(va, 'fetch')
            if translated[0] == 'fault':
                return ('fault', translated[1], va)
            pa = translated[1]
            self.log.append(('fetch', pa, 2))
            if pa & 1:
                return ('fault', 0, va)
            if not self.in_region(pa, 2) or self.refused('fetch', pa, 2):
                return ('fault', 1, va)
            return ('parcel', self.read(pa, 2))

        pc = self.pc
        low = parcel(pc)
        if low[0] == 'fault':
            self.deliver(low[1], low[2])
            return low
        if low[1] & 3 != 3:
            return ('insn', low[1], 2)
        high = parcel(u(pc + 2))
        if high[0] == 'fault':
            self.deliver(high[1], high[2])
            return high
        return ('insn', low[1] | (high[1] << 16), 4)


# ---- per-mnemonic stock rule text (locator-cited; a line directive overrides) ------------
RULES = {
    # P4-SYSTEM.11 (b): the M forms — RVI-M §11.1.1 (multiplication), §11.1.2 (division, Table 1)
    "mul": ("the low XLEN bits of rs1 × rs2.", "RVI-M §11.1.1"),
    "mulh": ("the high XLEN bits of the 128-bit product, signed × signed.", "RVI-M §11.1.1"),
    "mulhsu": ("the high XLEN bits of the 128-bit product, signed rs1 × unsigned rs2.", "RVI-M §11.1.1"),
    "mulhu": ("the high XLEN bits of the 128-bit product, unsigned × unsigned.", "RVI-M §11.1.1"),
    "mulw": ("the low 32 bits of the product of the low 32 bits, sign-extended.", "RVI-M §11.1.1"),
    "div": ("signed division rounding towards zero.", "RVI-M §11.1.2"),
    "divu": ("unsigned division.", "RVI-M §11.1.2"),
    "rem": ("the signed remainder, the sign of the dividend.", "RVI-M §11.1.2"),
    "remu": ("the unsigned remainder.", "RVI-M §11.1.2"),
    "divw": ("the low 32 bits divided as signed integers, the 32-bit quotient sign-extended.", "RVI-M §11.1.2"),
    "divuw": ("the low 32 bits divided as unsigned integers, the 32-bit quotient sign-extended.", "RVI-M §11.1.2"),
    "remw": ("the signed 32-bit remainder, sign-extended.", "RVI-M §11.1.2"),
    "remuw": ("the unsigned 32-bit remainder, sign-extended.", "RVI-M §11.1.2"),
    "addi": ("the 12-bit immediate adds into rd.", "RVI-RV32I §1.1.4"),
    "addiw": ("the low 32 bits add, sign-extended (D-WSUFFIX).", "RVI-RV64I §3.1.2.1"),
    "add": ("rd = rs1 + rs2, wrapping.", "RVI-RV32I §1.1.4"),
    "sub": ("rd = rs1 - rs2, wrapping.", "RVI-RV32I §1.1.4"),
    "lui": ("the upper 20 bits land sign-extended in rd.", "RVI-RV64I §3.1.2.1"),
    "auipc": ("auipc writes the instruction's own address plus the U-immediate.", "RVI-RV32I §1.1.4 (D-LUI-AUIPC)"),
    "slli": ("logical left shift.", "RVI-RV64I §3.1.2.1"),
    "srli": ("logical right shift.", "RVI-RV64I §3.1.2.1"),
    "srai": ("arithmetic right shift.", "RVI-RV64I §3.1.2.1"),
    "ori": ("bitwise OR with the sign-extended immediate.", "RVI-RV32I §1.1.4"),
    "andi": ("bitwise AND with the sign-extended immediate.", "RVI-RV32I §1.1.4"),
    "xor": ("bitwise XOR.", "RVI-RV32I §1.1.4"),
    "or": ("bitwise OR.", "RVI-RV32I §1.1.4"),
    "and": ("bitwise AND.", "RVI-RV32I §1.1.4"),
    "ld": ("a full XLEN load needs no extension.", "RVI-RV64I §3.1.3"),
    "lw": ("LW sign-extends its 32-bit result to 64 bits.", "RVI-RV64I §3.1.3 (D-LOAD-EXT)"),
    "lwu": ("the SAME word, zero-extended (RV64 only).", "RVI-RV64I §3.1.3 (D-LOAD-EXT)"),
    "sd": ("SD stores the low 64 bits of rs2 — no register observation.", "RVI-RV64I §3.1.3"),
    "sw": ("SW stores the low 32 bits of rs2 — no register observation.", "RVI-RV64I §3.1.3"),
    "beq": ("branch if equal — a taken branch writes no register.", "RVI-RV32I §1.1.5"),
    "bne": ("branch if not equal — a taken branch writes no register.", "RVI-RV32I §1.1.5"),
    "jal": ("JAL writes the return address.", "RVI-RV32I §1.1.5"),
    "jalr": ("JALR clears target bit zero and writes the following instruction address.", "RVI-RV32I §1.1.5"),
    "addw": ("the low 32 bits of the sum, sign-extended to 64 bits.", "RVI-RV64I §3.1.2.2"),
    "subw": ("the low 32 bits of the difference, sign-extended to 64 bits.", "RVI-RV64I §3.1.2.2"),
    "csrrw": ("atomic read/write CSR; rd=x0 discards the old value.", "RVI-ZICSR §5.1.1"),
    "csrrwi": ("atomic read/write CSR with the zero-extended uimm.", "RVI-ZICSR §5.1.1"),
    "csrrsi": ("read and set the uimm bits (uimm=0 writes nothing).", "RVI-ZICSR §5.1.1"),
    "csrrci": ("read and clear the uimm bits (uimm=0 writes nothing).", "RVI-ZICSR §5.1.1"),
    "csrrs": ("atomic read and set bits; rs1=x0 does not write the CSR.", "RVI-ZICSR §5.1.1"),
    "csrrc": ("atomic read and clear bits; rs1=x0 does not write the CSR.", "RVI-ZICSR §5.1.1"),
    "mret": ("the privilege stack pops per MPP and pc <- mepc.", "RVP-MACHINE §2.1.3.2"),
    "sret": ("the privilege stack pops per SPP and pc <- sepc.", "RVP-MACHINE §2.1.3.2"),
    "sfence.vma": ("the translation fence; the modelled TLB flushes per its four cases.", "RVP-SUPERVISOR §11.1.2.1"),
    ".word": ("a deliberately placed raw word (the reserved-encoding convention).", "D-RESERVED-DECODE"),
    "lr.w": ("LR.W loads the word, sign-extends it into rd, and registers the reservation.", "RVI-A §12.1.2"),
    "lr.d": ("LR.D loads the doubleword into rd and registers the reservation.", "RVI-A §12.1.2"),
    "sc.w": ("SC.W conditionally stores and writes the code to rd (0/1 — the declared deterministic policy).", "RVI-A §12.1.2; state.sexp's reservation candidate"),
    "sc.d": ("SC.D conditionally stores and writes the code to rd (0/1).", "RVI-A §12.1.2; state.sexp's reservation candidate"),
    "fence": ("a nop under this profile (D-FENCE).", "RVI-RV32I §1.1.6"),
}
AMO_TEXT = ("the atomic {op}: memory <- {new}, rd <- the OLD value {old}"
            " — one store/AMO-rules translation, the load-then-store pair.", "RVI-A §12.1.4")
AMO_OP = {0x00: "add", 0x01: "swap", 0x04: "xor", 0x0C: "and", 0x08: "or",
          0x10: "signed min", 0x14: "signed max", 0x18: "unsigned min", 0x1C: "unsigned max"}


# ---- CSR view/legalization mirrors (the engine's field tables, state_rv64gc.rs) ---------
MSTATUS_W = 0x7E79AA           # SIE,MIE,SPIE,MPIE,SPP,MPP,FS,MPRV,SUM,MXR,TVM,TW,TSR
SSTATUS_R = 0x80000003000DE722  # the view's named fields incl. VS/XS/UXL and the SD slot
SSTATUS_W = 0xC6122            # SIE,SPIE,SPP,FS,SUM,MXR


def mstatus_read(h):
    m = h.csr["mstatus"]
    sd = 1 if (m >> 13) & 0b11 == 3 else 0   # SD <- (FS == Dirty); XS is read-only 0
    return (m & ~(1 << 63)) | (sd << 63)


def csr_read_value(h, name):
    if name in ("mip", "sip"):
        v = h.mip_value(name)
        return v & 0x222 if name == "sip" else v
    if name == "sie":
        return h.csr["mie"] & 0x222
    if name == "mstatus":
        return mstatus_read(h)
    if name == "sstatus":
        return mstatus_read(h) & SSTATUS_R
    if name in ("cycle", "time", "mcycle"):
        return h.time                    # the one domain: mcycle's storage, the views
    if name in ("instret", "minstret"):
        return h.instret                 # the genuine retirement count
    if name == "fcsr":
        # the two-owner composition (RVI-F §20.1.2's figure): fflags[4:0], frm[2:0] above
        return (h.csr["fflags"] & 0x1F) | ((h.csr["frm"] & 0x7) << 5)
    return h.csr.get(name, 0)


def _dirty_fp(h):
    """Any FP-CSR write marks FS=Dirty (Sail 0.14's write_fcsr → dirty_fd_context_if_present,
    fdext_regs.sail:455); SD is computed from FS."""
    h.csr["mstatus"] |= 0b11 << 13


def csr_write_value(h, name, v):
    """Per-field legalization: WPRI/read-only/computed keep, OneOf judges, views write
    through to the owner under the view's own writable fields."""
    old = h.csr.get(name, 0)
    if name == "mstatus":
        new = (old & ~MSTATUS_W) | (v & MSTATUS_W)
        if (v >> 11) & 0b11 == 2:                       # MPP OneOf(0,1,3): keep the old field
            new = (new & ~(0b11 << 11)) | (old & (0b11 << 11))
        h.csr["mstatus"] = new
    elif name == "sstatus":
        m = h.csr["mstatus"]
        h.csr["mstatus"] = (m & ~SSTATUS_W) | (v & SSTATUS_W)
    elif name == "mip":
        h.csr["mip"] = (old & ~0x202) | (v & 0x202)     # SSIP/SEIP writable; STIP computed; the rest read-only 0
    elif name == "sip":
        m = h.csr["mip"]
        h.csr["mip"] = (m & ~0x2) | (v & 0x2)           # SSIP only — SEIP/STIP are read-only in the S view
    elif name == "mie":
        h.csr["mie"] = (old & ~0xAAA) | (v & 0xAAA)
    elif name == "sie":
        m = h.csr["mie"]
        h.csr["mie"] = (m & ~0x222) | (v & 0x222)
    elif name == "mideleg":
        h.csr["mideleg"] = (old & ~0x222) | (v & 0x222)
    elif name in ("mtvec", "stvec"):
        h.csr[name] = (v & ~0b11) | (v & 0b1)           # BASE Any; MODE OneOf(0,1)
    elif name in ("mepc", "sepc"):
        h.csr[name] = v & ~1                            # bit 0 read-only 0
    elif name == "fflags":
        h.csr["fflags"] = (old & ~0x1F) | (v & 0x1F)    # flags WARL-any; WPRI above keeps
        _dirty_fp(h)
    elif name == "frm":
        # any 3-bit value: "FSRM … writing a new value obtained from the three
        # least-significant bits of integer register rs1 into frm" (RVI-F §20.1.1)
        h.csr["frm"] = (old & ~0x7) | (v & 0x7)
        _dirty_fp(h)
    elif name == "fcsr":
        # the composition's inverse: both slices land (each owner stores its own field
        # bits — frm takes any 3-bit value, the FSRM sentence); bits 63:8 drop (the fcsr
        # paragraph: "implementations shall ignore writes to these bits")
        h.csr["fflags"] = (h.csr["fflags"] & ~0x1F) | (v & 0x1F)
        h.csr["frm"] = (h.csr["frm"] & ~0x7) | ((v >> 5) & 0x7)
        _dirty_fp(h)
    elif name in ("mcycle", "minstret"):
        raise Refusal(f"csr {name} write: the .5 tool's domain is a pure function of the "
                      f"step index — a write re-bases it; model the storage if a guest "
                      f"needs it (the wake corpus never does)")
    else:
        h.csr[name] = v


def sext(v, bits):
    return v - (1 << bits) if v & (1 << (bits - 1)) else v


def u(v, bits=64):
    return v & ((1 << bits) - 1)


class Step:
    def __init__(self, pc, insn):
        self.pc, self.insn = pc, insn
        self.writes = {}      # reg -> value
        self.deriv = ""
        self.source = ""
        self.fetch = 1        # actual requests: legacy word route 0/1; parcel route 0/1/2


def strip_labels(code: str) -> str:
    """The assembler's own convention: `label: instruction` — the word carries the
    instruction, the directive keys must match it."""
    while code and (code.endswith(":") or ":" in code.split()[0] if code.split() else False):
        _, _, code = code.partition(":")
        code = code.strip()
    return code


def run_guest(path: Path, asm: Assembler) -> tuple[str, int]:
    """Assemble, execute spec-side BY PC (branches and delivered traps reroute it),
    emit the .expected.sexp text. Returns (text, executed-steps)."""
    lines = path.read_text().splitlines()
    words = asm.assemble(lines)
    prog = {ENTRY + 4 * i: (w, t) for i, (w, t) in enumerate(words)}
    directives, never, end_at = {}, [], None
    refuse = []
    idx = 0
    for raw in lines:
        if raw.strip().startswith("#|never:"):
            never = [r.strip() for r in raw.split(":", 1)[1].split(",") if r.strip()]
            continue
        if raw.strip().startswith("#|refuse:"):
            # P4-SYSTEM.8 slice (c): typed fault injection — `#|refuse: KIND BASE SIZE`
            k, b, s = raw.split(":", 1)[1].split()
            if k not in ("load", "store", "walk"):
                raise Refusal(f"refuse kind {k!r}: this model derives load/store/walk refusals; "
                              f"it has no fetch translation model (fetch refusals are not derivable here)")
            refuse.append((k, int(b, 16), int(s, 16)))
            continue
        code = strip_labels(raw.split("#", 1)[0].strip())
        if not code:
            continue
        if "#:" in raw:
            if '"' in raw.split("#:", 1)[1]:
                # the emitter writes directives into S-expression strings unescaped — a
                # double quote would end the string early (measured at slice c1)
                raise Refusal(f"directive {raw.strip()!r}: a double quote cannot ride an "
                              f"S-expression string here — quote spec phrases with '…'")
            directives[idx] = raw.split("#:", 1)[1]   # keyed by INSTRUCTION INDEX (pc):
                                                      # the same instruction text at two pcs
                                                      # carries two derivations
        if "#|end" in raw:
            end_at = code   # the corpus's declared last step (the runner's count convention:
                            # the handler code after it is never a continuation)
        idx += 1
    h = Hart()
    h.refusals = refuse
    steps: list[Step] = []
    for _ in range(10000):
        got = prog.get(h.pc)
        if got is None:
            if not steps:
                raise Refusal(f"{path.name}: pc {h.pc:#x} leaves the program at the FIRST step")
            break                                    # the natural run-off: the guest ends
        if h.waiting:
            if not h.wake_pending():
                st = Step(h.pc, "<halted>")
                st.fetch = False
                st.deriv = ("the halt: the hart is WAITING — nothing retires and no "
                            "fetch issues this step; the domain ticks one, and the "
                            "wake re-evaluates at the next head (a locally-enabled "
                            "pending interrupt at any privilege level, regardless of "
                            "the global enables and of mideleg).")
                st.source = "RVP-MACHINE §2.1.3.3; the .5 brief's decisions 4 and 6"
                steps.append(st)
                h.time += 1
                continue
            h.waiting = False
            # the wake step is ordinary (decision 6): fall through to the head
            # evaluation — a taken trap's xepc is this pc (the WFI's pc + 4 by the
            # generic between-instructions rule); an untrapped resume continues here
        pend = h.pending()
        if pend is not None:
            cause, to_s = pend
            word, code_text = got
            st = Step(h.pc, code_text)
            st.fetch = False
            st.writes = {}
            name = {1: "SSI", 5: "STI", 9: "SEI", 3: "MSI", 7: "MTI", 11: "MEI"}[cause]
            level = "S" if to_s else "M"
            st.deriv = (f"the pending evaluation takes the {name} interrupt in {level}: "
                        f"xcause carries the Interrupt bit with cause {cause}, xepc is the "
                        f"un-fetched pc (interrupts are taken BETWEEN instructions), and "
                        f"pc moves to the vector as declared (no register observation — the "
                        f"handler's csrr reads below are the evidence).")
            st.source = "RVP-MACHINE §2.1.1.9; RVP-SUPERVISOR §11.1.1.3; the .5 brief's decision 3"
            steps.append(st)
            h.deliver_interrupt(cause, to_s)
            h.time += 1                              # a step boundary, nothing retired
            continue
        word, code_text = got
        st = Step(h.pc, code_text)
        h.trapped = False
        h.pc, info = execute(h, word)
        stored = info.pop("stored", None)
        if stored is not None:
            addr, width = stored
            # D-CODE-VISIBILITY, spec-side: a store into the program region is visible
            # to the NEXT fetch — the engine re-reads memory per fetch, so the
            # derivation re-reads too (the selfmod guests; the `.2` probe-measured
            # precedent, now tooled). The insn text keeps the assembled spelling and
            # names the patch, the `.2` comment convention.
            for a in range(addr, addr + width):
                if a in prog:
                    original_text = prog[a][1]
                    new_word = h.read(a, 4)
                    prog[a] = (new_word, original_text
                               + f" (patched: the word now reads {new_word:#010x})")
        st.writes = info.pop("writes", {})
        # the READS-AND-WRITES contract, by construction: execute() read the
        # PRE-instruction register file throughout; the instruction's writes land only
        # now, after the whole effect — exactly "register reads see pre-state"
        h.time += 1                                  # the domain ticks at every boundary
        if not h.trapped:
            h.instret += 1                           # minstret counts GENUINELY (never
                                                     # for a trapped/delivered/halted step)
        for reg, val in list(st.writes.items()):
            if h.x[reg] == val:
                # the corpus runner's comparison rule (the base profile's own): a
                # register written ITS OWN VALUE is no observation — the writes table
                # records changes, not writes (the .3 slice-e "x8-already-zero" rule)
                del st.writes[reg]
            else:
                h.x[reg] = val
        deriv, source = info.pop("deriv", ""), info.pop("source", "")
        directive = directives.get((st.pc - ENTRY) // 4)
        if directive is not None:
            d, _, s = directive.partition("|")
            deriv, source = d.strip(), s.strip() or source
            if not deriv:
                # the schema's min-length 1 (DOSSIER-SCHEMA refused f-sgnj at P4-SYSTEM.7
                # slice c6: a leading '|' — absolute-value bars — is the separator)
                raise Refusal(f"directive {directive.strip()!r} at pc {st.pc:#x}: the "
                              f"derivation before the first '|' is empty")
        for k, v in info.items():
            deriv = deriv.replace("{" + k + "}", str(v))
            source = source.replace("{" + k + "}", str(v))
        st.deriv, st.source = deriv, source
        steps.append(st)
        if code_text == end_at:
            break
    else:
        raise Refusal(f"{path.name}: 10000 steps without running off — a loop without an exit")
    out = emit(path, steps, len(steps), never, refuse)
    return out, len(steps)


class ParcelRun:
    """Independent guest observations and final hart, retained for offline controls."""

    def __init__(self, hart, steps, never, refusals):
        self.hart, self.steps = hart, steps
        self.never, self.refusals = never, refusals


def derive_parcel_guest(path: Path, asm: Assembler, budget: int) -> ParcelRun:
    """Execute exactly a declared number of boundaries from an exact byte image.

    Source PCs supply annotations only: instruction bytes always come from memory.
    Running off the source or reaching #|end does not shorten the explicit budget.
    Unknown valid instruction vocabulary refuses rather than fabricating a trap.
    """
    if type(budget) is not int or not 1 <= budget <= 10000:
        raise Refusal('parcel guest budget must be an integer in 1..10000')
    lines = path.read_text().splitlines()
    units = asm.assemble_units(lines, ENTRY)
    image = b''.join(unit.value.to_bytes(unit.length, 'little') for unit in units)
    if len(image) > REGION:
        raise Refusal(f'{path.name}: byte image exceeds the declared {REGION}-byte region')
    program = {unit.pc: unit for unit in units}
    directives, never, refusals = {}, [], []
    source_units = iter(units)
    for raw in lines:
        if raw.strip().startswith('#|never:'):
            never = [reg.strip() for reg in raw.split(':', 1)[1].split(',') if reg.strip()]
            continue
        if raw.strip().startswith('#|refuse:'):
            fields = raw.split(':', 1)[1].split()
            if len(fields) != 3 or fields[0] not in ('fetch', 'load', 'store', 'walk'):
                raise Refusal('parcel refusal needs KIND BASE SIZE (fetch/load/store/walk)')
            kind, base, size = fields
            try:
                base, size = int(base, 16), int(size, 16)
            except ValueError as exc:
                raise Refusal('parcel refusal base/size must be hexadecimal integers') from exc
            if not 0 <= base < 1 << 64 or not 0 < size <= (1 << 64) - base:
                raise Refusal('parcel refusal must be a nonempty nonwrapping XLEN region')
            refusals.append((kind, base, size))
            continue
        code = strip_labels(raw.split('#', 1)[0].strip())
        if not code:
            continue
        unit = next(source_units)
        assert unit.text == code, 'source annotations must follow the assembled units'
        if '#:' in raw:
            directive = raw.split('#:', 1)[1].split('#|end', 1)[0]
            if '"' in directive or '\\' in directive:
                raise Refusal('parcel directive cannot contain a double quote or backslash')
            derivation, _, source = directive.partition('|')
            if not derivation.strip():
                raise Refusal(f'parcel directive at pc {unit.pc:#x}: derivation is empty')
            directives[unit.pc] = (derivation.strip(), source.strip())

    hart = Hart()
    hart.refusals = refusals
    for offset, byte in enumerate(image):
        hart.mem[ENTRY + offset] = byte
    steps = []
    for _ in range(budget):
        pc = hart.pc
        unit = program.get(pc)
        step = Step(pc, unit.text if unit else '<memory instruction>')
        step.fetch = 0
        hart.trapped = False
        if hart.waiting and not hart.wake_pending():
            step.insn = '<halted>'
            step.deriv = 'WAITING: no fetch or retirement; the declared time domain ticks once.'
            step.source = 'RVP-MACHINE §2.1.3.3; the laboratory wait policy'
            hart.time += 1
            steps.append(step)
            continue
        hart.waiting = False
        pending = hart.pending()
        if pending is not None:
            cause, to_s = pending
            step.deriv = (f'pending interrupt {cause} delivers in {"S" if to_s else "M"} '
                          'before instruction fetch; EPC is this boundary PC, no retirement.')
            step.source = 'RVP-MACHINE §2.1.1.9; RVP-SUPERVISOR §11.1.1.3'
            hart.deliver_interrupt(cause, to_s)
            hart.time += 1
            steps.append(step)
            continue
        log_start = len(hart.log)
        fetched = hart.fetch_instruction()
        step.fetch = sum(record[0] == 'fetch' for record in hart.log[log_start:])
        if fetched[0] == 'fault':
            cause, va = fetched[1:]
            step.insn = '<fetch page fault>' if cause == 12 else '<fetch fault>'
            info = {'deriv': f'fetch cause {cause}: EPC is the instruction start, tval is failing parcel VA {sx(va)}; no retirement.',
                    'source': 'RVP-SUPERVISOR §11.1.3.2; RVP-MACHINE §2.1.1.14/§2.1.1.16'}
        else:
            _, bits, length = fetched
            if unit is None or (unit.value, unit.length) != (bits, length):
                step.insn = f'.{"half" if length == 2 else "word"} {bits:#0{length * 2 + 2}x}'
            if length == 2:
                hart.pc, info = execute_c(hart, bits)
            elif bits & 0x1f == 0x1f:
                # The selected profile has ILEN=32; no wider instruction is implemented.
                hart.deliver(2, bits)
                info = {'deriv': f'unsupported wider prefix: illegal instruction, tval retains all ILEN=32 bits {bits:#010x}.',
                        'source': 'RVI-INTRO instruction-length encoding; RVP-MACHINE §2.1.1.16; ILEN=32 laboratory profile'}
            else:
                hart.pc, info = execute(hart, bits)
        info.pop('stored', None)  # every later fetch reads the updated memory directly
        step.writes = info.pop('writes', {})
        hart.time += 1
        if not hart.trapped:
            hart.instret += 1
        for reg, value in list(step.writes.items()):
            if hart.x[reg] == value:
                del step.writes[reg]
            else:
                hart.x[reg] = value
        derivation, source = info.pop('deriv', ''), info.pop('source', '')
        if pc in directives and fetched[0] != 'fault':
            derivation, override = directives[pc]
            source = override or source
        for key, value in info.items():
            derivation = derivation.replace('{' + key + '}', str(value))
            source = source.replace('{' + key + '}', str(value))
        step.deriv, step.source = derivation, source
        steps.append(step)
    return ParcelRun(hart, steps, never, refusals)


def run_parcel_guest(path: Path, asm: Assembler, budget: int) -> tuple[str, int]:
    run = derive_parcel_guest(path, asm, budget)
    return emit(path, run.steps, len(run.steps), run.never, run.refusals), len(run.steps)


def execute_c(h: Hart, parcel: int) -> tuple[int, dict]:
    """Judge a complete compressed parcel; fetching remains the caller's duty.

    Reserved encodings take the laboratory illegal-instruction policy. Expansion
    computation is independent of the engine's declarations, and its traps retain
    the original parcel. The caller commits returned GPR writes after all reads.
    """
    try:
        expansion = C.decode(parcel)
    except C.Reserved as exc:
        h.deliver(2, parcel)
        return h.pc, {"deriv": f"reserved compressed parcel {parcel:#06x}: {exc}; cause 2, xtval the original 16 bits.",
                      "source": "RVI-C §27.1.5/§27.1.8; the laboratory illegal-instruction policy"}
    except ValueError as exc:
        raise Refusal(str(exc)) from exc
    next_pc, info = execute(h, expansion.word, length=2, raw=parcel)
    info["deriv"] = f"{expansion.name.upper()} uses its declared base operation at length 2: " + info["deriv"]
    info["source"] = expansion.source + "; " + info["source"]
    return next_pc, info


def execute(h: Hart, word: int, *, length=4, raw=None) -> tuple[int, dict]:
    """One instruction, spec-side. Returns (next_pc, info) — info carries writes +
    derivation/source/interpolation values. REFUSES an unknown encoding by name."""
    if length not in (2, 4):
        raise Refusal(f"instruction length {length}: only 2/4 are supported")
    raw = word if raw is None else raw
    pc = h.pc
    next_pc = u(pc + length)
    op = word & 0x7F
    rd, f3, rs1, rs2 = (word >> 7) & 0x1F, (word >> 12) & 7, (word >> 15) & 0x1F, (word >> 20) & 0x1F
    imm_i = sext(word >> 20, 12)
    imm_s = sext(((word >> 25) << 5) | rd, 12)
    imm_b = sext(((word >> 31) << 12) | (((word >> 7) & 1) << 11)
                 | (((word >> 25) & 0x3F) << 5) | (((word >> 8) & 0xF) << 1), 13)
    imm_u = sext(word & 0xFFFFF000, 32)
    imm_j = sext(((word >> 31) << 20) | (((word >> 12) & 0xFF) << 12)
                 | (((word >> 20) & 1) << 11) | (((word >> 21) & 0x3FF) << 1), 21)
    if word & 0x0000707F == 0x0000100F:  # fence.i — funct3=1 in MISC-MEM; the fields
                                         # decode-and-IGNORE (the shall-ignore rule)
        return next_pc, {"deriv": "fence.i retires: the declared nop — the synchronization is already provided (this machine re-reads memory on every fetch, so the chapter's coherent/uncached-RAM latitude leaves nothing to flush); funct12/rs1/rd decoded-and-ignored, never rejected.",
                        "source": "RVI-ZIFENCEI §4.1; the .6 brief's decision 2; D-CODE-VISIBILITY"}
    x = h.x

    def w(reg, val):
        return {reg: u(val)} if reg else {}

    def stock(mn, **fmt):
        if mn not in RULES:
            raise Refusal(f"mnemonic {mn!r} has no stock spec-side rule in this corpus")
        d, s = RULES[mn]
        for k, v in fmt.items():
            d = d.replace("{" + k + "}", str(v))
        return {"deriv": d, "source": s, **fmt}

    def data_access(kind, va, width_bits):
        """The shared access path: misaligned (atomics: cause 7) or plain (4/6) before
        translation, then the walk, then the region. Returns ('pa', pa) or ('fault', c, tval)."""
        mis_cause = 7 if kind == "atomic" else (4 if kind == "load" else 6)
        if va % (width_bits // 8):
            return ("fault", mis_cause, va)
        walk_kind = {"load": "load", "store": "store", "atomic": "atomic"}[kind]
        r = h.walk(va, walk_kind)
        if r[0] == "fault":
            return ("fault", r[1], va)
        pa = r[1]
        if not h.in_region(pa, width_bits // 8):
            return ("fault", {"load": 5, "store": 7, "atomic": 7}[kind], va)
        # P4-SYSTEM.8 slice (c): a declared refusal answers the boundary request with an
        # access fault — an AMO issues a load then a store, and either refused is cause 7;
        # a plain or reserved load's is 5, a store's or SC's 7 (the engine's own mapping)
        halves = {"load": ("load",), "store": ("store",), "atomic": ("load", "store")}[kind]
        for half in halves:
            if h.refused(half, pa, width_bits // 8):
                return ("fault", 5 if kind == "load" else 7, va)
        return ("pa", pa)

    if op == 0b0010011:  # OP-IMM
        shamt = (word >> 20) & 0x3F
        if ((f3 == 1 and word >> 26 != 0)
                or (f3 == 5 and word >> 26 not in (0, 0x10))):
            raise Refusal(f"OP-IMM word {word:#010x}: reserved shift upper bits")
        if f3 == 0:
            val, mn = u(x[rs1] + imm_i), "addi"
        elif f3 == 1:
            val, mn = u(x[rs1] << shamt), "slli"
        elif f3 == 5 and (word >> 26) == 0:
            val, mn = u(x[rs1] >> shamt), "srli"
        elif f3 == 5:
            val, mn = u(sext(x[rs1], 64) >> shamt), "srai"
        elif f3 == 6:
            val, mn = u(x[rs1] | imm_i), "ori"
        elif f3 == 7:   # P4-SYSTEM.7 slice d4: "ANDI … perform bitwise AND … on register rs1 and
            #             the sign-extended 12-bit immediate" (RVI-RV32I §1.1.4) — the D corpus
            #             aligns its doubleword data address with it
            val, mn = u(x[rs1] & imm_i), "andi"
        elif f3 == 4:
            raise Refusal("xori is outside the corpus's vocabulary — refuse, never guess")
        else:
            raise Refusal(f"OP-IMM funct3 {f3} outside the corpus's vocabulary")
        return next_pc, {"writes": w(rd, val), **stock(mn)}
    if op in (0b0110011, 0b0111011) and (word >> 25) == 1:
        # P4-SYSTEM.11 (b): M — decoded BEFORE the OP branch, whose `elif f3 == 0` would read a
        # funct7=1 word (mul) as sub. Exact integers; Table 1's two rows tested BY NAME.
        def tdiv(a, b):              # "rounding towards zero" — Python's // floors
            q = abs(a) // abs(b)
            return q if (a < 0) == (b < 0) else -q
        L = 64 if op == 0b0110011 else 32
        ua, ub = u(x[rs1], L), u(x[rs2], L)
        sa, sb = sext(ua, L), sext(ub, L)
        most_negative = -(1 << (L - 1))
        if L == 64 and f3 in (0, 1, 2, 3):
            val, mn = {0: (sa * sb, "mul"), 1: ((sa * sb) >> 64, "mulh"),
                       2: ((sa * ub) >> 64, "mulhsu"), 3: ((ua * ub) >> 64, "mulhu")}[f3]
        elif L == 32 and f3 == 0:
            val, mn = sext(u(sa * sb, 32), 32), "mulw"
        elif f3 == 4:   # DIV[W] — Table 1: by zero −1; overflow (signed only) the dividend
            q = -1 if sb == 0 else sa if (sa == most_negative and sb == -1) else tdiv(sa, sb)
            val, mn = q, "div" if L == 64 else "divw"
        elif f3 == 5:   # DIVU[W] — Table 1: by zero 2^L − 1
            q = (1 << L) - 1 if ub == 0 else ua // ub
            val, mn = q if L == 64 else sext(u(q, 32), 32), "divu" if L == 64 else "divuw"
        elif f3 == 6:   # REM[W] — Table 1: by zero the dividend; overflow 0
            r = sa if sb == 0 else 0 if (sa == most_negative and sb == -1) else sa - sb * tdiv(sa, sb)
            val, mn = r, "rem" if L == 64 else "remw"
        elif f3 == 7:   # REMU[W] — Table 1: by zero the dividend
            r = ua if ub == 0 else ua % ub
            val, mn = r if L == 64 else sext(u(r, 32), 32), "remu" if L == 64 else "remuw"
        else:
            raise Refusal(f"M funct3 {f3} at width {L} names no M instruction — refuse, never guess")
        return next_pc, {"writes": w(rd, u(val)), **stock(mn), "new": sx(u(val))}
    if op == 0x1b:  # ADDIW; other OP-IMM-32 forms remain outside this corpus
        if f3 != 0:
            raise Refusal(f"OP-IMM-32 word {word:#010x}: unsupported funct3")
        val = u(sext(u(x[rs1] + imm_i, 32), 32))
        return next_pc, {"writes": w(rd, val), **stock("addiw")}
    if op == 0x3b:  # ADDW/SUBW, after the exact M-word family above
        funct7 = word >> 25
        if f3 != 0 or funct7 not in (0, 0x20):
            raise Refusal(f"OP-32 word {word:#010x}: reserved or unsupported funct3/funct7")
        val = x[rs1] + x[rs2] if funct7 == 0 else x[rs1] - x[rs2]
        return next_pc, {"writes": w(rd, u(sext(u(val, 32), 32))),
                         **stock("addw" if funct7 == 0 else "subw")}
    if op == 0b0110011:  # OP
        funct7 = word >> 25
        if not ((f3 == 0 and funct7 in (0, 0x20))
                or (f3 in (4, 6, 7) and funct7 == 0)):
            raise Refusal(f"OP word {word:#010x}: reserved or unsupported funct3/funct7")
        if f3 == 0 and (word >> 25) == 0:
            val, mn = u(x[rs1] + x[rs2]), "add"
        elif f3 == 0:
            val, mn = u(x[rs1] - x[rs2]), "sub"
        elif f3 == 4:
            val, mn = u(x[rs1] ^ x[rs2]), "xor"
        elif f3 == 6:
            val, mn = u(x[rs1] | x[rs2]), "or"
        elif f3 == 7:
            val, mn = u(x[rs1] & x[rs2]), "and"
        else:
            raise Refusal(f"OP funct3 {f3}/funct7 {word >> 25} outside the corpus")
        return next_pc, {"writes": w(rd, val), **stock(mn)}
    if op == 0b0110111:
        return next_pc, {"writes": w(rd, imm_u), **stock("lui")}
    if op == 0b0010111:
        return next_pc, {"writes": w(rd, u(pc + imm_u)), **stock("auipc")}
    if op == 0b0000011:  # LOAD
        va = u(x[rs1] + imm_i)
        widths = {0: (1, "lb"), 1: (2, "lh"), 2: (4, "lw"), 3: (8, "ld"),
                  4: (1, "lbu"), 5: (2, "lhu"), 6: (4, "lwu")}
        if f3 not in widths:
            raise Refusal(f"LOAD funct3 {f3} outside the corpus")
        n, mn = widths[f3]
        r = data_access("load", va, n * 8)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"{mn} at {sx(va)}: misaligned/access/page fault — cause {r[1]} delivered (xtval the address, xepc this instruction).",
                          "source": "RVP-MACHINE's exception table; RVI-A §12.1.2/§12.1.4 for the atomic kinds"}
        v = h.read(r[1], n)
        v = u(sext(v, n * 8)) if mn in ("lb", "lh", "lw") else v
        return next_pc, {"writes": w(rd, v), **stock(mn)}
    if op == 0b0100011:  # STORE
        va = u(x[rs1] + imm_s)
        widths = {0: (1, "sb"), 1: (2, "sh"), 2: (4, "sw"), 3: (8, "sd")}
        if f3 not in widths:
            raise Refusal(f"STORE funct3 {f3} outside the corpus")
        n, mn = widths[f3]
        r = data_access("store", va, n * 8)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"{mn} at {sx(va)}: fault — cause {r[1]} delivered.",
                          "source": "RVP-MACHINE's exception table"}
        h.write(r[1], n, x[rs2])
        info = stock(mn)
        info["stored"] = (r[1], n)     # run_guest's memory-backed fetch watches stores
        return next_pc, info
    if op == 0b1100011:  # BRANCH
        taken = {0: x[rs1] == x[rs2], 1: x[rs1] != x[rs2]}.get(f3)
        if taken is None:
            raise Refusal(f"BRANCH funct3 {f3} outside the corpus")
        mn = "beq" if f3 == 0 else "bne"
        return (u(pc + imm_b) if taken else next_pc), stock(mn)
    if op == 0b1101111:
        return u(pc + imm_j), {"writes": w(rd, u(next_pc)), **stock("jal")}
    if op == 0x67:
        if f3 != 0:
            raise Refusal(f"JALR word {word:#010x}: reserved funct3")
        # PRE-state rs1 determines the target even when rs1 and rd alias (C.JALR x1).
        return u(x[rs1] + imm_i) & ~1, {"writes": w(rd, next_pc), **stock("jalr")}
    if op in F_OPCODES:
        return execute_f(h, word, op, rd, f3, rs1, rs2, imm_i, imm_s, data_access, w,
                         next_pc=next_pc, raw=raw)
    if op == 0b1110011:  # SYSTEM
        csr = (word >> 20) & 0xFFF
        name = {0x300: "mstatus", 0x301: "misa", 0x305: "mtvec",
                0x340: "mscratch", 0x341: "mepc", 0x342: "mcause", 0x343: "mtval",
                0x302: "medeleg", 0x180: "satp", 0x100: "sstatus", 0x105: "stvec",
                0x140: "sscratch", 0x141: "sepc", 0x142: "scause", 0x143: "stval",
                0x304: "mie", 0x303: "mideleg", 0x344: "mip",
                0x104: "sie", 0x144: "sip", 0x14D: "stimecmp",
                0xC00: "cycle", 0xC01: "time", 0xC02: "instret",
                0xB00: "mcycle", 0xB02: "minstret",
                0x001: "fflags", 0x002: "frm", 0x003: "fcsr", 0xF14: "mhartid"}.get(csr)
        if f3 in (1, 2, 3, 5, 6, 7):  # csrrw / csrrs / csrrc and the immediate forms (P4-SYSTEM.8 a)
            if name is None:
                raise Refusal(f"csr {csr:#x} outside the corpus's vocabulary")
            if (csr >> 8) & 0b11 > h.mode:
                raise Refusal(f"csr {name} (address {csr:#x}) accessed from mode {h.mode} — "
                              f"the engine raises illegal-instruction here; route through "
                              f"the S view or fix the guest")
            if name in ("fflags", "frm", "fcsr") and (h.csr["mstatus"] >> 13) & 0b11 == 0:
                # the FS gate (slice b): at FS=Off the FP CSRs are inaccessible — an
                # illegal-instruction trap (cause 2, xtval the word), every mode
                h.deliver(2, raw)
                return h.pc, {"deriv": "mstatus.FS is Off: the FP CSRs are inaccessible (the Off-state sentence) — cause 2 delivered, xtval the instruction word.",
                              "source": "RVP-MACHINE §2.1.1.6.7; RVI-F §20.1.1; the .7 brief's decision 5"}
            counter_bit = {"cycle": 0, "time": 1, "instret": 2}.get(name)
            if counter_bit is not None:
                # the counter-ACCESS gates (§2.1.1.11): M open; S needs mcounteren;
                # U needs mcounteren AND scounteren — gated off is an illegal-instruction
                # trap (cause 2, xtval the word), the engine's own delivery
                bit = counter_bit
                open_s = h.mode == 1 and (h.csr["mcounteren"] >> bit) & 1
                open_u = (h.mode == 0 and (h.csr["mcounteren"] >> bit) & 1
                          and (h.csr["scounteren"] >> bit) & 1)
                if h.mode != 3 and not open_s and not open_u:
                    h.deliver(2, raw)
                    return h.pc, {"deriv": f"rd{name} gated off below M (mcounteren/scounteren): cause 2 delivered, xtval the instruction word.",
                                  "source": "RVP-MACHINE §2.1.1.11"}
            # P4-SYSTEM.8 slice (a): a write to a READ-ONLY address (csr[11:10] = 11, RVP-CSR
            # §1.1.1) is illegal — "Attempts to write a read-only register raise an
            # illegal-instruction exception" (RVI-ZICSR §5.1.1) — and the instruction completes
            # or faults as a unit (the laboratory's declared discipline): rd is NOT written.
            # csrrw/csrrwi always write; the set/clear forms write iff rs1 (or uimm) is nonzero.
            writes = f3 in (1, 5) or rs1 != 0
            if writes and (csr >> 10) & 0b11 == 0b11:
                h.deliver(2, raw)
                return h.pc, {"deriv": f"a write to the read-only {name} (address {csr:#x}): illegal-instruction, cause 2 (xtval the word) — and the instruction faults as a unit: rd is not written.",
                              "source": "RVI-ZICSR §5.1.1; RVP-CSR §1.1.1; the .8 brief's unit discipline"}
            # sip/sie/sstatus are VIEWS: reads see the owner's state through the view
            # mask, writes route to the owner under the view's own fields (the engine's
            # view rule — the guests touch only the S-subset bits)
            old = csr_read_value(h, name)
            src = rs1 if f3 >= 5 else x[rs1]     # the immediate forms: the zero-extended uimm
            mn = {1: "csrrw", 2: "csrrs", 3: "csrrc", 5: "csrrwi", 6: "csrrsi", 7: "csrrci"}[f3]
            if f3 in (1, 5):
                new = src
            elif f3 in (2, 6):
                new = (old | src) if rs1 != 0 else None
            else:
                new = (old & ~src) if rs1 != 0 else None
            if new is not None:
                csr_write_value(h, name, new)
            return next_pc, {"writes": w(rd, old), **stock(mn)}
        if word == 0x10500073:  # wfi — the .2 legality resolutions STAND; a LEGAL wfi ENTERS the wait (decision 4)
            if h.mode == 0 or (h.mode < 3 and (h.csr["mstatus"] >> 21) & 1):
                h.deliver(2, raw)
                return h.pc, {"deriv": "wfi illegal here (U with S present, or below M with TW=1 — the .2 TW resolutions, standing): cause 2 delivered, xtval the instruction word.",
                              "source": "RVP-MACHINE §2.1.3.3, §2.1.1.6.6"}
            h.waiting = True
            return next_pc, {"deriv": "a LEGAL wfi: the hart ENTERS the wait (the nop latitude recorded-not-taken — decision 4); it retires the instruction and stalls, the wake evaluating at the next head.",
                            "source": "RVP-MACHINE §2.1.3.3; the .5 brief's decision 4"}
        if word == 0x00000073:  # ecall — the cause names the ORIGINATING mode (U=8, S=9, M=11), xtval 0
            cause = {0: 8, 1: 9, 3: 11}[h.mode]
            h.deliver(cause, 0)
            return h.pc, {"deriv": f"ecall from {'M' if h.mode == 3 else ('S' if h.mode == 1 else 'U')}: cause {cause} delivered (xtval 0, xepc this instruction).",
                          "source": "RVP-MACHINE §2.1.3.1"}
        if word == 0x00100073:  # ebreak — cause 3, xtval the pc (the .2 convention)
            h.deliver(3, pc)
            return h.pc, {"deriv": "ebreak: cause 3, xtval the instruction's own address.",
                          "source": "RVP-MACHINE §2.1.3.1"}
        if word == 0x30200073:  # mret
            mstatus = h.csr["mstatus"]
            mpp = (mstatus >> 11) & 0b11
            h.mode = mpp
            mstatus = (mstatus & ~(1 << 3)) | (((mstatus >> 7) & 1) << 3)
            mstatus |= 1 << 7
            mstatus = (mstatus & ~(0b11 << 11)) | (0 << 11)  # MPP <- U (least)
            if h.mode != M:
                mstatus &= ~(1 << 17)  # MPRV <- 0
            h.csr["mstatus"] = mstatus
            return h.csr["mepc"], stock("mret")
        if word == 0x10200073:  # sret
            mstatus = h.csr["mstatus"]
            spp = (mstatus >> 8) & 1
            h.mode = spp
            mstatus = (mstatus & ~(1 << 1)) | (((mstatus >> 5) & 1) << 1)
            mstatus |= 1 << 5
            mstatus &= ~(1 << 8)
            if h.mode != M:
                mstatus &= ~(1 << 17)
            h.csr["mstatus"] = mstatus
            return h.csr["sepc"], stock("sret")
        if (word & 0xFE007FFF) == 0x12000073:  # sfence.vma
            return next_pc, stock("sfence.vma")
        raise Refusal(f"SYSTEM word {word:#x} outside the corpus")
    if op == 0b0001111:
        if f3 != 0:
            raise Refusal(f"MISC-MEM word {word:#010x}: reserved or unsupported funct3")
        return next_pc, stock("fence")
    if op == 0b0101111:  # the A forms
        funct5 = word >> 27
        aq, rl = (word >> 26) & 1, (word >> 25) & 1
        n = 4 if f3 == 2 else (8 if f3 == 3 else None)
        legal = n is not None and (funct5 in AMO_OP or funct5 == 0b00011
                                   or (funct5 == 0b00010 and rs2 == 0))
        if not legal:
            # D-RESERVED-DECODE: no A row matches (a funct3 outside .W/.D, an LR with
            # rs2≠0, a reserved funct5) — the corpus runner's diagnostic policy converts
            # the decode miss to the delivered illegal-instruction cause, xtval the word
            h.deliver(2, raw)
            return h.pc, {"deriv": f"a deliberately reserved encoding ({sx(word)}): no A row matches — the diagnostic policy converts the decode miss to the delivered illegal-instruction cause 2, xtval the word itself.",
                          "source": "D-RESERVED-DECODE; RVI-A §12.1.2/§12.1.4's encoding rules"}
        va = x[rs1]
        if funct5 == 0b00010:  # LR
            r = data_access("load", va, n * 8) if va % n == 0 else ("fault", 5, va)
            if r[0] == "fault":
                h.deliver(r[1], r[2])
                return h.pc, {"deriv": f"lr at {sx(va)}: misaligned — the declared policy takes the LOAD access-fault cause 5 (the exception table maps load-reserved to load exceptions), judged BEFORE translation; the trap clears nothing.",
                              "source": "RVI-A §12.1.2; RVP-MACHINE's exception table; the laboratory's declared policy (state.sexp, decision 6)"}
            v = h.read(r[1], n)
            h.reservation = (r[1], n)
            mn = "lr.w" if n == 4 else "lr.d"
            v = u(sext(v, 32)) if n == 4 else v
            return next_pc, {"writes": w(rd, v), **stock(mn)}
        if funct5 == 0b00011:  # SC
            r = data_access("store", va, n * 8) if va % n == 0 else ("fault", 7, va)
            if r[0] == "fault":
                h.deliver(r[1], r[2])
                return h.pc, {"deriv": f"sc at {sx(va)}: the trap path — neither success nor failure, so the reservation SURVIVES (cause {r[1]} delivered).",
                              "source": "RVI-A §12.1.2; the laboratory's declared policy (state.sexp)"}
            mn = "sc.w" if n == 4 else "sc.d"
            if h.reservation == (r[1], n):
                h.write(r[1], n, x[rs2])
                h.reservation = None
                code = 0
                note = "the reservation matches (valid ∧ PA equal ∧ width equal): the store lands, rd <- 0, the reservation clears"
            else:
                h.reservation = None
                code = 1
                note = "no matching reservation: code 1, NOTHING is stored, the reservation clears anyway — the declared deterministic policy, never spurious"
            return next_pc, {"writes": w(rd, code),
                            "deriv": f"{mn}: {note} (the deterministic policy: succeeds iff valid ∧ physical address equal ∧ width equal).",
                            "source": "RVI-A §12.1.2; state.sexp's reservation candidate (decision 3)"}
        if funct5 in AMO_OP:  # the nine AMOs
            r = data_access("atomic", va, n * 8) if va % n == 0 else ("fault", 7, va)
            if r[0] == "fault":
                h.deliver(r[1], r[2])
                return h.pc, {"deriv": f"amo at {sx(va)}: cause {r[1]} delivered — misaligned or the store/AMO translation rule, NEVER a load page fault.",
                              "source": "RVI-A §12.1.4; RVP-SUPERVISOR (AMOs never raise load page-fault exceptions); state.sexp's policy"}
            old = h.read(r[1], n)
            v = x[rs2] & ((1 << (n * 8)) - 1)
            op_name = AMO_OP[funct5]
            if funct5 == 0x00:
                new = old + v
            elif funct5 == 0x01:
                new = v
            elif funct5 == 0x04:
                new = old ^ v
            elif funct5 == 0x0C:
                new = old & v
            elif funct5 == 0x08:
                new = old | v
            elif funct5 == 0x10:
                new = min(sext(old, n * 8), sext(v, n * 8))
            elif funct5 == 0x14:
                new = max(sext(old, n * 8), sext(v, n * 8))
            elif funct5 == 0x18:
                new = min(old, v)
            else:
                new = max(old, v)
            new &= (1 << (n * 8)) - 1
            h.write(r[1], n, new)
            mn = f"amo{op_name.replace('signed ', 's').replace('unsigned ', 'u')}.{'w' if n == 4 else 'd'}"
            rdv = u(sext(old, 32)) if n == 4 else old
            d, s = AMO_TEXT
            d = d.replace("{op}", op_name).replace("{new}", sx(new)).replace("{old}", sx(old))
            return next_pc, {"writes": w(rd, rdv), "deriv": d, "source": s}
        raise Refusal(f"AMO funct5 {funct5:#x} outside the closed Zaamo nine")
    raise Refusal(f"word {word:#010x}: no spec-side rule — a .word reserved row is "
                  f"authored with its own directive, not executed")


# ---- the F extension, spec-side (P4-SYSTEM.7 slice c5) ------------------------------------------
# Decoded from the opcode map (LOAD-FP 0000111, STORE-FP 0100111, the fused MADD/MSUB/NMSUB/
# NMADD 1000011/1000111/1001011/1001111, OP-FP 1010011) and executed from the pinned chapter's
# sentences; the arithmetic is scripts/specfp.py's exact rationals — never fp.rs, never the
# backend, never an engine run (EVD-05).
F_OPCODES = (0b0000111, 0b0100111, 0b1000011, 0b1000111, 0b1001011, 0b1001111, 0b1010011)
SIGN32 = 0x80000000
FLAG_NAMES = ((SF.NV, "NV"), (SF.DZ, "DZ"), (SF.OF, "OF"), (SF.UF, "UF"), (SF.NX, "NX"))
RM_NAMES = ("RNE", "RTZ", "RDN", "RUP", "RMM")


def fnames(fl):
    return "|".join(n for b, n in FLAG_NAMES if fl & b) or "none"


def execute_f(h, word, op, rd, f3, rs1, rs2, imm_i, imm_s, data_access, w, *, next_pc, raw):
    # THE OFF GATE (RVP-MACHINE §2.1.1.6.7): every F instruction reads or writes the FP
    # state, so at FS=Off it is illegal-instruction — before any effect (an FLW never reaches
    # its load)
    if (h.csr["mstatus"] >> 13) & 0b11 == 0:
        h.deliver(2, raw)
        return h.pc, {"deriv": "FS=Off: the instruction would read or write the floating-point state — illegal-instruction, cause 2 (xtval the word), before any effect of its own.",
                      "source": "RVP-MACHINE §2.1.1.6.7"}

    def unbox(v):   # RVI-D §21.1.2: properly boxed → the low 32 bits; else the canonical NaN
        return v & 0xFFFFFFFF if v >> 32 == 0xFFFFFFFF else 0x7FC00000

    def box(v):
        return (v & 0xFFFFFFFF) | 0xFFFFFFFF00000000

    def dirty():
        h.csr["mstatus"] |= 0b11 << 13

    def fwrite(r, v):   # an f-register write marks FS Dirty (the FP-state contract)
        h.f[r] = v
        dirty()

    def accrue(fl):     # sticky; FS Dirty iff fflags CHANGES (the declared Precise rule)
        old = h.csr["fflags"]
        if old | fl != old:
            h.csr["fflags"] = old | fl
            dirty()

    def mode():         # (rounding rm): DYN → frm; reserved static 101/110 or dyn 101..111 → None
        m = f3 if f3 != 7 else h.csr["frm"] & 7
        return m if m <= 4 else None

    def reserved():
        h.deliver(2, raw)
        how = (f"rm = {f3:03b} is a reserved static mode" if f3 != 7
               else f"rm = DYN with frm = {h.csr['frm'] & 7:03b}, a reserved dynamic mode")
        return h.pc, {"deriv": f"{how} — reserved behavior, taken as illegal-instruction (cause 2, xtval the word); no flag accrues.",
                      "source": "RVI-F §20.1.2 (Table 2); the laboratory's illegal-instruction choice"}

    if op == 0b0000111 and f3 == 2:      # FLW
        va = u(h.x[rs1] + imm_i)
        r = data_access("load", va, 32)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"flw at {sx(va)}: fault — cause {r[1]} delivered.", "source": "RVP-MACHINE's exception table"}
        v = h.read(r[1], 4)
        fwrite(rd, box(v))
        return next_pc, {"deriv": f"flw: f{rd} <- the word {v:#010x} NaN-boxed (bits unmodified).",
                        "source": "RVI-F §20.1.5; RVI-D §21.1.2"}
    if op == 0b0100111 and f3 == 2:      # FSW
        va = u(h.x[rs1] + imm_s)
        r = data_access("store", va, 32)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"fsw at {sx(va)}: fault — cause {r[1]} delivered.", "source": "RVP-MACHINE's exception table"}
        h.write(r[1], 4, h.f[rs2] & 0xFFFFFFFF)
        return next_pc, {"deriv": f"fsw: the low 32 bits of f{rs2} to {sx(va)} (the upper FLEN-32 ignored).",
                        "source": "RVI-F §20.1.5; RVI-D §21.1.2"}
    if op == 0b0000111 and f3 == 3:      # FLD — RVI-D §21.1.3: the 64 bits, unmodified
        va = u(h.x[rs1] + imm_i)
        r = data_access("load", va, 64)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"fld at {sx(va)}: fault — cause {r[1]} delivered.", "source": "RVP-MACHINE's exception table"}
        v = h.read(r[1], 8)
        fwrite(rd, v)
        return next_pc, {"deriv": f"fld: f{rd} <- the doubleword {v:#018x} (bits unmodified).",
                        "source": "RVI-D §21.1.3"}
    if op == 0b0100111 and f3 == 3:      # FSD
        va = u(h.x[rs1] + imm_s)
        r = data_access("store", va, 64)
        if r[0] == "fault":
            h.deliver(r[1], r[2])
            return h.pc, {"deriv": f"fsd at {sx(va)}: fault — cause {r[1]} delivered.", "source": "RVP-MACHINE's exception table"}
        h.write(r[1], 8, h.f[rs2])
        return next_pc, {"deriv": f"fsd: f{rs2}'s 64 bits to {sx(va)} (unmodified).", "source": "RVI-D §21.1.3"}
    # P4-SYSTEM.7 slice (d4): the format is DATA — fmt 0 (S: operands unboxed, results boxed)
    # or 1 (D: the register is the double); every rule below is its F sentence at width n.
    fmt = (word >> 25) & 3
    if fmt > 1:
        raise Refusal(f"F word {word:#010x}: fmt {fmt} is neither S nor D")
    n = 32 if fmt == 0 else 64
    sfx = ".s" if fmt == 0 else ".d"
    SIGN = SIGN32 if n == 32 else 0x8000000000000000
    MASK = 0xFFFFFFFF if n == 32 else 0xFFFFFFFFFFFFFFFF
    HEX = 10 if n == 32 else 18
    src = "RVI-F" if n == 32 else "RVI-D (its F counterpart at 64)"

    def opnd(r):        # an n-bit operand: unboxed single, or the register's double
        return unbox(h.f[r]) if n == 32 else h.f[r]

    def result(v):      # an n-bit result: boxed single, or the double itself
        return box(v) if n == 32 else v & MASK
    if op in (0b1000011, 0b1000111, 0b1001011, 0b1001111):   # the fused four
        m = mode()
        if m is None:
            return reserved()
        rs3 = word >> 27
        a, b, c = opnd(rs1), opnd(rs2), opnd(rs3)
        np_, na = {0b1000011: (False, False), 0b1000111: (False, True),
                   0b1001011: (True, False), 0b1001111: (True, True)}[op]
        bits, fl = SF.fma(n, m, a, b, c, negate_product=np_, negate_addend=na)
        fwrite(rd, result(bits))
        accrue(fl)
        name = {0b1000011: "fmadd", 0b1000111: "fmsub", 0b1001011: "fnmsub", 0b1001111: "fnmadd"}[op] + sfx
        return next_pc, {"deriv": f"{name} ({RM_NAMES[m]}): {('-' if np_ else '')}(f{rs1}×f{rs2}){'-' if na else '+'}f{rs3} rounded once = {bits:#0{HEX}x}; flags {fnames(fl)}.",
                        "source": f"{src} §20.1.6" if n == 32 else "RVI-D §21.1.4 (FMADD.S's rule at 64)"}
    if op != 0b1010011:
        raise Refusal(f"F word {word:#010x} outside the corpus")
    funct5 = word >> 27
    a, b = opnd(rs1), opnd(rs2)
    arith = {0x00: ("fadd", SF.add), 0x01: ("fsub", SF.sub), 0x02: ("fmul", SF.mul), 0x03: ("fdiv", SF.div)}
    s_src = "RVI-F §20.1.6" if n == 32 else "RVI-D §21.1.4"
    if funct5 in arith:
        m = mode()
        if m is None:
            return reserved()
        name, fn = arith[funct5]
        bits, fl = fn(n, m, a, b)
        fwrite(rd, result(bits))
        accrue(fl)
        return next_pc, {"deriv": f"{name}{sfx} ({RM_NAMES[m]}): {bits:#0{HEX}x}; flags {fnames(fl)}.", "source": s_src}
    if funct5 == 0x0B and rs2 == 0:      # FSQRT
        m = mode()
        if m is None:
            return reserved()
        bits, fl = SF.sqrt(n, m, a)
        fwrite(rd, result(bits))
        accrue(fl)
        return next_pc, {"deriv": f"fsqrt{sfx} ({RM_NAMES[m]}): {bits:#0{HEX}x}; flags {fnames(fl)}.", "source": s_src}
    if funct5 == 0x04 and f3 in (0, 1, 2):   # sign injection: bits, no flags, no canonicalization
        sign = {0: b & SIGN, 1: (b ^ SIGN) & SIGN, 2: (a ^ b) & SIGN}[f3]
        bits = (a & ~SIGN & MASK) | sign
        fwrite(rd, result(bits))
        name = ("fsgnj", "fsgnjn", "fsgnjx")[f3] + sfx
        return next_pc, {"deriv": f"{name}: rs1's magnitude with the injected sign = {bits:#0{HEX}x}; no flag, no canonicalization.",
                        "source": "RVI-F §20.1.7" if n == 32 else "RVI-D §21.1.5"}
    if funct5 == 0x05 and f3 in (0, 1):
        bits, fl = SF.min_max(n, a, b, f3 == 1)
        fwrite(rd, result(bits))
        accrue(fl)
        return next_pc, {"deriv": f"{('fmin', 'fmax')[f3]}{sfx}: {bits:#0{HEX}x}; flags {fnames(fl)}.", "source": s_src}
    if funct5 == 0x08 and fmt == 0 and rs2 == 1:   # FCVT.S.D — narrowing, rounded
        m = mode()
        if m is None:
            return reserved()
        bits, fl = SF.convert(32, 64, m, h.f[rs1])
        fwrite(rd, box(bits))
        accrue(fl)
        return next_pc, {"deriv": f"fcvt.s.d ({RM_NAMES[m]}): f{rs1}'s double rounded to the single {bits:#010x}, NaN-boxed; flags {fnames(fl)}.",
                        "source": "RVI-D §21.1.5"}
    if funct5 == 0x08 and fmt == 1 and rs2 == 0:   # FCVT.D.S — widening, exact
        m = mode()
        if m is None:
            return reserved()
        bits, fl = SF.convert(64, 32, m, unbox(h.f[rs1]))
        fwrite(rd, bits)
        accrue(fl)
        return next_pc, {"deriv": f"fcvt.d.s: f{rs1}'s single (unboxed) widened exactly to {bits:#018x}; flags {fnames(fl)}.",
                        "source": "RVI-D §21.1.5"}
    if funct5 == 0x18 and rs2 <= 3:      # FCVT.{W,WU,L,LU}.{S,D}
        m = mode()
        if m is None:
            return reserved()
        iw, signed = ((32, True), (32, False), (64, True), (64, False))[rs2]
        v, fl = SF.to_int(n, iw, signed, m, a)
        if iw == 32:
            v = u(sext(v, 32))   # "FCVT.W[U].S sign-extends the 32-bit result" (and .D's, RVI-D §21.1.5)
        accrue(fl)
        name = ("fcvt.w", "fcvt.wu", "fcvt.l", "fcvt.lu")[rs2] + sfx
        return next_pc, {"writes": w(rd, v), "deriv": f"{name} ({RM_NAMES[m]}): x{rd} = {sx(v)}; flags {fnames(fl)}.",
                        "source": "RVI-F §20.1.7 (Table 5)" if n == 32 else "RVI-D §21.1.5 (FCVT.int.S's Table 5)"}
    if funct5 == 0x1A and rs2 <= 3:      # FCVT.{S,D}.{W,WU,L,LU}
        m = mode()
        if m is None:
            return reserved()
        iw, signed = ((32, True), (32, False), (64, True), (64, False))[rs2]
        bits, fl = SF.from_int(n, iw, signed, m, h.x[rs1])
        fwrite(rd, result(bits))
        accrue(fl)
        name = "fcvt" + sfx + ("." + ("w", "wu", "l", "lu")[rs2])
        return next_pc, {"deriv": f"{name} ({RM_NAMES[m]}): {bits:#0{HEX}x}; flags {fnames(fl)}.",
                        "source": "RVI-F §20.1.7" if n == 32 else "RVI-D §21.1.5"}
    if funct5 == 0x1C and rs2 == 0 and f3 == 0:   # FMV.X.W / FMV.X.D — transfers, never unboxed
        if n == 32:
            v = u(sext(h.f[rs1] & 0xFFFFFFFF, 32))
            return next_pc, {"writes": w(rd, v), "deriv": f"fmv.x.w: the low 32 bits of f{rs1}, sign-extended: x{rd} = {sx(v)}.",
                            "source": "RVI-F §20.1.7"}
        v = h.f[rs1]
        return next_pc, {"writes": w(rd, v), "deriv": f"fmv.x.d: f{rs1}'s 64 bits, unmodified: x{rd} = {sx(v)}.",
                        "source": "RVI-D §21.1.5"}
    if funct5 == 0x1C and rs2 == 0 and f3 == 1:   # FCLASS
        v = SF.classify(n, a)
        return next_pc, {"writes": w(rd, v), "deriv": f"fclass{sfx}: the class mask {v:#x}; no flag.",
                        "source": "RVI-F §20.1.9 (Table 6)" if n == 32 else "RVI-D §21.1.7 (FCLASS.S's Table 6)"}
    if funct5 == 0x1E and rs2 == 0 and f3 == 0:   # FMV.W.X / FMV.D.X
        if n == 32:
            fwrite(rd, box(h.x[rs1]))
            return next_pc, {"deriv": f"fmv.w.x: f{rd} <- x{rs1}'s low 32 bits, NaN-boxed.", "source": "RVI-F §20.1.7; RVI-D §21.1.2"}
        fwrite(rd, h.x[rs1])
        return next_pc, {"deriv": f"fmv.d.x: f{rd} <- x{rs1}'s 64 bits, unmodified.", "source": "RVI-D §21.1.5"}
    if funct5 == 0x14 and f3 in (0, 1, 2):        # FLE / FLT / FEQ
        kind = {2: "eq", 1: "lt", 0: "le"}[f3]
        v, fl = SF.compare(n, kind, a, b)
        accrue(fl)
        return next_pc, {"writes": w(rd, v), "deriv": f"f{kind}{sfx}: x{rd} = {v}; flags {fnames(fl)}.",
                        "source": "RVI-F §20.1.8" if n == 32 else "RVI-D §21.1.6"}
    raise Refusal(f"OP-FP word {word:#010x} outside the corpus")


def emit(path: Path, steps: list[Step], count: int, never: list[str], refuse=()) -> str:
    fetches = sum(st.fetch for st in steps)
    # the header names the guest's OWN family (P4-SYSTEM.8 slice a: the .7 header was stamped
    # on every re-derived file); the atomics family keeps its .4 tool's exact words
    if path.stem.startswith("a-"):
        head = [f';; {path.stem}.expected.sexp — the expected observations for `{path.name}` (P4-SYSTEM.4',
                ';; slice d, the atomics corpus). EVD-05: every value below was derived from the pinned',
                ';; chapters and the declared deterministic SC policy (state.sexp) by the spec-side',
                ';; authoring model BEFORE any engine run; the corpus runner falsifies against it.']
    elif path.stem.startswith("env-"):
        head = [f';; {path.stem}.expected.sexp — the expected observations for `{path.name}` (P4-SYSTEM.9,',
                ';; the environment-contract fixtures). EVD-05: every value below was derived from the',
                ';; pinned chapters and the contract v1 assumptions by the spec-side authoring model',
                ';; BEFORE any engine run; the corpus runner falsifies against it.']
    elif path.stem.startswith("m-"):
        head = [f';; {path.stem}.expected.sexp — the expected observations for `{path.name}` (P4-SYSTEM.11,',
                ';; the M corpus). EVD-05: every value below was derived from the pinned chapter (RVI-M',
                ';; §11.1, Table 1\'s rows by name) with exact integers by the spec-side authoring model',
                ';; BEFORE any engine run; the corpus runner falsifies against it.']
    elif path.stem.startswith(("mm-csr-ro", "prio-", "inj-")):
        head = [f';; {path.stem}.expected.sexp — the expected observations for `{path.name}` (P4-SYSTEM.8,',
                ';; the faults corpus). EVD-05: every value below was derived from the pinned chapters',
                ';; and the .8 brief\'s declared unit discipline by the spec-side authoring model',
                ';; BEFORE any engine run; the corpus runner falsifies against it.']
    else:
        head = [f';; {path.stem}.expected.sexp — the expected observations for `{path.name}` (P4-SYSTEM.7,',
                ';; the floating-point corpus). EVD-05: every value below was derived from the pinned',
                ';; chapters and the .7 brief\'s declared FP-state rules by the spec-side authoring model',
                ';; BEFORE any engine run; the corpus runner falsifies against it.']
    L = head + [
         ';; Validate with',
         f';;   python3 scripts/check_sexp_schema.py {path.stem}.expected.sexp schema/expectations.sexp',
         '',
         f'(expectations (program "{path.name}") (entry "{sx(ENTRY)}") (instructions {count})'
         + (f' (fetches {fetches})' if fetches != count else '')]
    for r in never:
        L.append(f'  (never_written "{r}")')
    for k, b, s in refuse:
        L.append(f'  (refuse (kind {k}) (base "{b:#x}") (size "{s:#x}"))')
    for i, st in enumerate(steps):
        writes = " ".join(f'(write (reg "x{r}") (value "{sx(v)}"))'
                          for r, v in sorted(st.writes.items()))
        L.append(f'  (step (n {i}) (insn "{st.insn}") (writes{" " if writes else ""}{writes})')
        L.append(f'    (derivation "{st.deriv}") (source "{st.source}"))')
    L.append(')')
    return "\n".join(L) + "\n"


OWNED_GUESTS = (
    'a-lrsc-fault',
    'a-lrsc-illegal',
    'a-lrsc-loop',
    'a-lrsc-pair',
    'd-arith',
    'd-class',
    'd-compare',
    'd-convert',
    'd-f2f',
    'd-fs-off',
    'd-fused',
    'd-minmax',
    'd-move',
    'd-rounding',
    'd-sgnj',
    'env-irq-sources',
    'f-arith',
    'f-class',
    'f-compare',
    'f-convert',
    'f-dirty',
    'f-fs-off',
    'f-fused',
    'f-minmax',
    'f-move-box',
    'f-rounding',
    'f-sgnj',
    'fp-fcsr-view',
    'fp-fs-off',
    'inj-atomics',
    'inj-carrier',
    'inj-fp',
    'inj-walk-l0',
    'inj-walk-l1',
    'inj-walk-l2',
    'm-alias',
    'm-div',
    'm-mul',
    'm-word',
    'mm-csr-ro-counters',
    'mm-csr-ro-write',
    'prio-sv39',
)


def main(argv):
    import argparse
    from riscv_asm import AsmError
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='compare without writing')
    parser.add_argument('--check-owned', action='store_true', help='check the explicit historical author corpus')
    parser.add_argument('--parcels', action='store_true', help='execute exact byte images under C/ILEN=32')
    parser.add_argument('--steps', type=int, help='explicit boundary budget for --parcels (1..10000)')
    parser.add_argument('--encoding', type=Path, default=ENCODING)
    parser.add_argument('guests', nargs='*', type=Path)
    args = parser.parse_args(argv[1:])
    if args.check_owned and args.guests:
        parser.error('--check-owned selects its corpus; do not also pass guests')
    if args.parcels and (args.steps is None or args.check_owned):
        parser.error('--parcels requires --steps and cannot select the historical --check-owned corpus')
    if not args.parcels and args.steps is not None:
        parser.error('--steps requires --parcels')
    paths = ([REPO / 'profiles/rv64gc-lab-v0/guests' / (n + '.s') for n in OWNED_GUESTS]
             if args.check_owned else args.guests)
    if not paths:
        parser.error('pass guest sources or --check-owned')
    try:
        asm = Assembler(args.encoding)
        results = [(p, *(run_parcel_guest(p, asm, args.steps) if args.parcels else run_guest(p, asm)))
                   for p in paths]
    except (Refusal, AsmError, OSError) as exc:
        print(f'derive_rv64gc_expectations: REFUSED — {exc}', file=sys.stderr)
        return 2
    drift = []
    for path, text, steps in results:
        out = path.with_suffix('.expected.sexp')
        if args.check or args.check_owned:
            if not out.is_file() or out.read_text() != text:
                drift.append(path.stem)
        else:
            out.write_text(text)
            print(f'derive_rv64gc_expectations: wrote {out.name} ({steps} steps)')
    if drift:
        print('derive_rv64gc_expectations: DRIFT — ' + ', '.join(drift), file=sys.stderr)
        return 1
    if args.check or args.check_owned:
        print(f'derive_rv64gc_expectations: {len(paths)} guest(s) byte-identical; no records written')
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
