#!/usr/bin/env python3
"""Generate a milestone gate report from PINNED inputs.

`ROADMAP.md` §P1 asks for the gate report to be *generated from pinned inputs*, and `EVD-08`
requires it to name its inputs, its commands, its actual results and its limitations. A gate
report written by hand is a summary of what its author remembers; this one is a function of the
repository, so it cannot flatter the work.

⛔ IT IS DERIVED ENTIRELY FROM TRACKED FILES — the profile, the requirements catalogue, the
contract obligations, the reference dossier (whose `[[experiment]]` records carry the observed
results) and the guest expectations. Nothing here reads `target/`, so the report regenerates
byte-identically in a fresh clone with no reference binaries present. That is what lets a gate
check it for staleness.

⛔ AND IT CANNOT SAY `passed` WHILE A REQUIRED CHECK IS MISSING. `EVD-08` names that outcome
explicitly, and it is the one verdict this generator refuses to produce: the criterion below
counts declared checks against implemented ones, and 66 against 0 cannot round up.

Usage:  scripts/gate_report.py <profile>          write the report
        scripts/gate_report.py <profile> --stdout print it instead
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True, check=True).stdout.strip())

sys.path.insert(0, str(ROOT / "scripts"))
import records_sexp as R                                # noqa: E402
import dossier_sexp as D                                # noqa: E402


def build(profile: str) -> str:
    d = ROOT / "profiles" / profile
    prof = D.load_profile(d / "profile.sexp")            # SOT-FORMAT.4: one format, read via
    refs = D.load_references(d / "references.sexp")      # the mapping — the same dicts the
    reqs = R.load(d / "requirements.sexp")               # TOML/JSON produced, so this report
    obs = R.load(d / "contract-obligations.sexp")        # is byte-stable across the move
    guests = sorted((d / "guests").glob("*.expected.sexp"))

    by_class: dict[str, int] = {}
    for r in reqs:
        c = r["source_semantics"]["category"]
        by_class[c] = by_class.get(c, 0) + 1
    declared_checks = sum(len(o["required_checks"]) for o in obs)
    # An IMPLEMENTED check is one an executable actually names — by its CONCRETE id, not by its
    # shape.
    # ⛔ This took two wrong cuts, and both were wrong in the direction that inflates the verdict.
    # Grepping the whole tree for the id PATTERN counted `EVIDENCE_POLICY.md`, which merely
    # describes the naming convention in prose. Narrowing to `scripts/` still counted
    # `check_requirements.sh`, which tests for the `-POS`/`-NEG` suffix as part of enforcing that
    # the ids exist — a gate about checks is not a check. The measure is therefore exact: take the
    # concrete ids the contract declares and ask which of them any tracked executable names.
    declared_ids = sorted({c for o in obs for c in o["required_checks"]})
    hits = subprocess.run(
        ["git", "grep", "-h", "-o", "-F", "-f", "-", "--", "scripts", "crates"],
        input="\n".join(declared_ids), capture_output=True, text=True, cwd=ROOT).stdout.split()
    implementing = sorted(set(hits))

    exps = refs.get("experiment", [])
    inds = refs.get("independence", [])
    diffs = refs.get("difference", [])
    cands = refs.get("candidate", [])
    obtained = [c for c in cands if c["status"] == "obtained"]
    exercised = sorted({m for e in exps for m in e["models"]})

    steps = 0
    negatives = 0
    for g in guests:
        spec = D.load_expectations(g)
        steps += len(spec["step"])
        negatives += len(spec.get("never_written") or [])

    unresolved = [r["id"] for r in reqs if r["research_status"] != "resolved"]

    L: list[str] = []
    A = L.append
    A(f"# Gate `{prof['profile'].get('gate', 'G0')}` report — `{profile}`")
    A("")
    A("<!-- DERIVED — DO NOT EDIT. Regenerated by `scripts/gate_report.py`; the `GATE-REPORT`")
    A("     doctrine fails the commit if this file and its inputs disagree. Edit the INPUTS:")
    A("     profile.sexp, requirements.sexp, contract-obligations.sexp, references.sexp,")
    A("     guests/*.expected.sexp. -->")
    A("")
    # ⛔ There is exactly one way to reach `passed`, and it requires every declared check to be
    # implemented. `EVD-08` names "passed with a missing required check" as the outcome a report
    # must never produce, so it is unreachable here rather than merely discouraged.
    verdict = "passed" if declared_checks and len(implementing) >= declared_checks else "incomplete"
    A(f"**Verdict: `{verdict}`.**")
    A("")
    A("## Why this verdict")
    A("")
    A("`EVD-08` forbids a report that reads `passed` while a required check is missing. This")
    A(f"profile declares **{declared_checks} required checks** across {len(obs)} obligations, of")
    A(f"which **{len(implementing)} {'is' if len(implementing) == 1 else 'are'} implemented** —")
    A("measured by taking each concrete check id the contract declares and asking whether any")
    A("tracked executable under `scripts/` or `crates/` names it. Not asserted, and not inferred")
    A("from an id-shaped pattern appearing in prose. The verdict cannot be `passed`, and this")
    A("generator has no code path that would produce it while that is true.")
    A("")
    A("## Inputs (all tracked; this report reads nothing untracked)")
    A("")
    A("| Input | Contents |")
    A("| --- | --- |")
    A(f"| `profile.sexp` | {len(prof['decision'])} decisions, {prof['scope']['count_total']} mnemonics, XLEN {prof['profile']['xlen']}, extensions `{prof['profile']['extensions']}` |")
    A(f"| `requirements.sexp` | {len(reqs)} requirements |")
    A(f"| `contract-obligations.sexp` | {len(obs)} obligations, {declared_checks} declared checks |")
    A(f"| `references.sexp` | {len(cands)} candidates, {len(exps)} experiments, {len(inds)} independence records, {len(diffs)} recorded differences |")
    A(f"| `guests/*.expected.sexp` | {len(guests)} programs, {steps} expected steps, {negatives} negative observations |")
    A("")
    A("## Criterion 1 — foundational semantics are resolved")
    A("")
    A("Every requirement carries a source locator, and its research status is recorded.")
    A("")
    A("| Semantic class | Requirements |")
    A("| --- | --- |")
    for c in sorted(by_class):
        A(f"| `{c}` | {by_class[c]} |")
    A("")
    if unresolved:
        A(f"**Not fully resolved: {len(unresolved)}** — " + ", ".join(f"`{u}`" for u in unresolved) +
          ". Each names its open question inside the record. `RECORD-SCHEMA` refuses a record that")
        A("claims `resolved` while carrying an open note, so this count cannot be flattered.")
    else:
        A("All requirements are `resolved`.")
    A("")
    A("**Status: met, with the open questions named above.**")
    A("")
    A("## Criterion 2 — an actual evidence path works")
    A("")
    A("| Experiment | Models | Verdict | Reproduced |")
    A("| --- | --- | --- | --- |")
    for e in exps:
        A(f"| `{e['id']}` | {', '.join(e['models'])} | {e['verdict']} | {e['reproduced'].split('—')[0].strip()} |")
    A("")
    A(f"Reference candidates obtained: **{len(obtained)}** of {len(cands)}; exercised in an")
    A(f"experiment: **{len(exercised)}** ({', '.join(exercised)}). Every experiment records the")
    A("control that was observed FAILING — `RECORD-SCHEMA` refuses one that does not.")
    A("")
    A("**Status: met.** A matched-profile experiment has been run and reproduced, covering a")
    A("trap as well as arithmetic.")
    A("")
    A("## Criterion 3 — profile and reference differences are enumerated")
    A("")
    A("| Difference | Kind |")
    A("| --- | --- |")
    for df in diffs:
        A(f"| `{df['id']}` | {df['kind']} |")
    A("")
    A("| Independence: subsystem | Pair | Verdict |")
    A("| --- | --- | --- |")
    for i in inds:
        A(f"| {i['subsystem']} | {' ↔ '.join(i['pair'])} | **{i['verdict']}** |")
    A("")
    A("**Status: met.** Differences are recorded rather than assumed absent, and independence is")
    A("stated per pair and subsystem — including the pairs nobody has examined, because an omitted")
    A("pair reads exactly like an independent one.")
    A("")
    A("## Limitations (`EVD-08`)")
    A("")
    A(f"1. **{declared_checks} checks are declared and {len(implementing)} implemented.** They name")
    A("   fixtures a later milestone builds. This is the reason for the verdict.")
    A("2. **No CPU model exists.** `crates/` holds the scaffold's placeholder; every requirement is")
    A("   `implementation_status: planned`. Nothing here is evidence about an implementation.")
    A("3. **Finite differential testing is not proof.** The experiments are evidence for those")
    A("   inputs on those models. Two models sharing semantic code can agree while both are wrong.")
    A("4. **The effective reference configuration is our merge, not the model's report.** The Sail")
    A("   model will not emit its merged configuration; the one self-description it does emit is")
    A("   its ISA string, which is pinned and re-derived.")
    A("5. **Encodings come from a different provenance than the semantics.** The pinned")
    A("   specification contains no instruction encodings; that source is upstream of one")
    A("   comparator and not the other.")
    A("")
    A("## Commands that re-derive this report's inputs")
    A("")
    A("```")
    A("scripts/fetch_references.sh --verify-only   # every pinned digest, and 52 == 52")
    A("scripts/run_smoke.py                        # the experiments, on both models")
    A("scripts/check_requirements.sh               # records validate and agree with the profile")
    A("scripts/check_doctrines.sh                  # the whole gate registry")
    A("```")
    A("")
    return "\n".join(L) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: gate_report.py <profile> [--stdout]", file=sys.stderr)
        return 2
    text = build(argv[1])
    if "--stdout" in argv:
        sys.stdout.write(text)
        return 0
    out = ROOT / "profiles" / argv[1] / "G0-REPORT.md"
    out.write_text(text)
    print(f"wrote {out.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
