#!/usr/bin/env python3
"""gen_m_vectors.py — the M extension's instruction vectors, from a spec-side reference
(P4-SYSTEM.11 slice c1). Every expected result is derived HERE with exact Python integers from
the pinned chapter (RVI-M §11.1.1–§11.1.2): the products from the exact 2·XLEN-bit product,
the quotients by truncation written out by hand (Python's // floors), and Table 1's two rows —
a zero divisor, signed overflow — tested BY NAME, never by wrapping. Nothing here is the
engine's arithmetic (crates/semulith-core/src/muldiv.rs wraps on overflow and leaves a zero
divisor undefined; the definition's guards supply Table 1).

The table is checked through the ENGINE — decode, the m.sem.sexp rule with its guard, the
operators at their width — by crates/semulith-verify/src/m_vectors/tests.rs, and it is TRACKED
and gated (M-VECTORS): an expected value edited by hand to make a test pass is DRIFT.

usage: gen_m_vectors.py            write the table
       gen_m_vectors.py --check    exit 0 iff the tracked table is this generator's output
       gen_m_vectors.py --out P    write (or with --check, compare) the table at P
"""
import random
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates/semulith-verify/src/m_vectors/vectors.txt"
SEED = 20261006
M64 = (1 << 64) - 1

# (mnemonic, funct3, is_word) — the pinned rv_m/rv64_m rows (definitions/riscv/m.sexp)
INSNS = [("mul", 0, False), ("mulh", 1, False), ("mulhsu", 2, False), ("mulhu", 3, False),
         ("div", 4, False), ("divu", 5, False), ("rem", 6, False), ("remu", 7, False),
         ("mulw", 0, True), ("divw", 4, True), ("divuw", 5, True), ("remw", 6, True),
         ("remuw", 7, True)]

# the values Table 1 and the word forms distinguish: zero, ±1, the 64- and 32-bit extremes,
# a divisor zero only as a word (2^32), and a word operand under high-bit garbage
EDGES = [0, 1, 2, 3, M64, M64 - 1, 1 << 63, (1 << 63) + 1, (1 << 63) - 1, 0x8000_0000,
         0x7FFF_FFFF, 0xFFFF_FFFF, 1 << 32, 0xFFFF_FFFF_8000_0000, 0x1234_5678_FFFF_FFF9]
DIVISORS = (0, 1, M64, 1 << 63, 0xFFFF_FFFF)


def signed(v, bits):
    v &= (1 << bits) - 1
    return v - (1 << bits) if v >> (bits - 1) else v


def trunc_div(a, b):
    """'rounding towards zero' (RVI-M §11.1.2) — written out, because // floors."""
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q


def reference(mn, a, b):
    """The instruction's rd, from the chapter's text and Table 1."""
    word = mn.endswith("w") and mn not in ("mulhsu",)
    L = 32 if word else 64
    ua, ub = a & ((1 << L) - 1), b & ((1 << L) - 1)
    sa, sb = signed(a, L), signed(b, L)
    most_negative = -(1 << (L - 1))
    base = mn[:-1] if word else mn
    if base == "mul":
        r = sa * sb                                       # the low L bits are sign-agnostic
    elif base == "mulh":
        r = (sa * sb) >> 64
    elif base == "mulhsu":
        r = (sa * ub) >> 64
    elif base == "mulhu":
        r = (ua * ub) >> 64
    elif base == "div":
        r = -1 if sb == 0 else sa if (sa == most_negative and sb == -1) else trunc_div(sa, sb)
    elif base == "divu":
        r = (1 << L) - 1 if ub == 0 else ua // ub
    elif base == "rem":
        r = sa if sb == 0 else 0 if (sa == most_negative and sb == -1) else sa - sb * trunc_div(sa, sb)
    elif base == "remu":
        r = ua if ub == 0 else ua % ub
    else:
        raise SystemExit(f"gen_m_vectors: no reference for {mn}")
    if word:                                              # "sign-extend the 32-bit result"
        r = signed(r, 32)
    return r & M64


def operands():
    rng = random.Random(SEED)
    seeded = [rng.getrandbits(64) for _ in range(14)]
    # small magnitudes and their negations, so quotients and remainders are not all 0 / a
    seeded += [rng.randrange(1, 1 << 12) for _ in range(3)]
    seeded += [(-rng.randrange(1, 1 << 12)) & M64 for _ in range(3)]
    return EDGES + seeded


def table() -> str:
    ops = operands()
    lines = ["# GENERATED by scripts/gen_m_vectors.py (P4-SYSTEM.11 slice c1) from its spec-side",
             "# exact-integer reference (RVI-M §11.1, Table 1 by name) — not the engine's arithmetic.",
             "# Do not edit; regenerate. Gated by M-VECTORS; run through the engine by",
             "# crates/semulith-verify/src/m_vectors/tests.rs.",
             f"# seed {SEED}; {len(ops)} operands; every edge pair, every seeded pair against the",
             "# edges and the zero divisor; mnemonic rs1 rs2 rd (hex)"]
    rows = 0
    for mn, _, _ in INSNS:
        pairs = [(a, b) for a in EDGES for b in EDGES]
        pairs += [(a, b) for a in ops[len(EDGES):] for b in DIVISORS]
        pairs += [(a, b) for a, b in zip(ops[len(EDGES):], reversed(ops[len(EDGES):]))]
        for a, b in pairs:
            lines.append(f"{mn} {a:x} {b:x} {reference(mn, a, b):x}")
            rows += 1
    lines.insert(6, f"# {rows} vectors over {len(INSNS)} instructions")
    return "\n".join(lines) + "\n"


def main(argv):
    out, check = OUT, False
    i = 1
    while i < len(argv):
        if argv[i] == "--check":
            check = True
        elif argv[i] == "--out" and i + 1 < len(argv):
            out = Path(argv[i + 1])
            i += 1
        else:
            print(__doc__, file=sys.stderr)
            return 2
        i += 1
    text = table()
    if check:
        if not out.is_file() or out.read_text() != text:
            print(f"gen_m_vectors: DRIFT — {out} is not this generator's output; regenerate, never edit",
                  file=sys.stderr)
            return 1
        print(f"gen_m_vectors: ok ({out.name} is the generator's output)")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"gen_m_vectors: wrote {out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
