#!/usr/bin/env python3
"""gen_book_index.py — generate the project book's index (BOOK-APPARATUS.1).

The index is a FACT about the book: which governed terms are discussed in which chapters.
A hand-maintained index is a running total — a memory of a measurement, not a measurement
(DERIVED-COUNTS' founding failure) — so this generator derives it:

  term set      docs/GLOSSARY.md (the canonical glossary table) + the acronym table in
                docs/book/src/glossary.md ("The acronyms this book uses")
  chapter set   docs/book/src/SUMMARY.md, in reading order (the book's own declaration)
  occurrences   a case-insensitive, word-boundary scan of each chapter's text

Output: docs/book/src/index.md — one row per term: where it is defined, and the chapters
(in reading order) that discuss it. The glossary chapter and the index itself are excluded
from the occurrence scan (a term's definition is not a discussion of it).

Contract: deterministic; offline; read-only except --out. A shape this generator cannot
emit is REFUSED by name (exit 2), never guessed. `--check` compares the regenerated bytes
against --out and reports DRIFT (exit 1) instead of writing.

Usage:
  python3 scripts/gen_book_index.py [--check] [--book DIR] [--glossary FILE] [--out FILE]
"""
import argparse
import re
import sys
from pathlib import Path

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/gen_book_index.py from the book's own text (SUMMARY.md, the\n"
    "     canonical glossary, the acronym table) — regenerate, never edit:\n"
    "       python3 scripts/gen_book_index.py\n"
    "     The BOOK-INDEX gate (scripts/check_book_index.sh) refuses drift. -->"
)

SUMMARY_ENTRY = re.compile(r"^\s*(?:-\s*)?\[([^\]]+)\]\(([^)]+)\)\s*$")
GLOSSARY_ROW = re.compile(r"^\|(.+)\|(.+)\|$")
ACRONYM_ROW = re.compile(r"^\|(.+)\|(.+)\|(.+)\|$")
ACRONYMS_HEADING = "## The acronyms this book uses"

# Terms the scan must not match inside, and the file the scan must not treat as input:
# the glossary defines terms (not a discussion), and the index restates them.
SCAN_EXCLUDED = {"glossary.md", "index.md", "SUMMARY.md"}


class Refusal(Exception):
    """A shape the generator cannot emit — named, never guessed (exit 2)."""


def read_chapters(book: Path) -> list[tuple[str, str, str]]:
    """(title, relative link path, text) per SUMMARY.md entry, in reading order."""
    summary = book / "src" / "SUMMARY.md"
    if not summary.is_file():
        raise Refusal(f"no SUMMARY.md under {book / 'src'} — the chapter set is undeclared")
    chapters = []
    for line in summary.read_text(encoding="utf-8").splitlines():
        m = SUMMARY_ENTRY.match(line)
        if not m:
            continue
        title, rel = m.group(1).strip(), m.group(2).strip()
        path = book / "src" / rel
        if not path.is_file():
            raise Refusal(f"SUMMARY.md names '{rel}' but no such chapter exists")
        chapters.append((title, rel, path.read_text(encoding="utf-8")))
    if not chapters:
        raise Refusal("SUMMARY.md declares no chapters — nothing to index")
    return chapters


def read_terms(book: Path, glossary: Path) -> list[tuple[str, str, list[str]]]:
    """(display term, definition link, aliases) — glossary terms, then acronyms."""
    if not glossary.is_file():
        raise Refusal(f"the canonical glossary {glossary} is missing")
    terms: list[tuple[str, str, list[str]]] = []
    for line in glossary.read_text(encoding="utf-8").splitlines():
        m = GLOSSARY_ROW.match(line.strip())
        if not m:
            continue
        term = m.group(1).strip()
        if term in ("Term", "---", ":---") or set(term) <= {"-", ":"}:
            continue
        aliases = [a.strip() for a in term.split("/") if a.strip()]
        terms.append((term, "glossary.md", aliases))

    book_glossary = book / "src" / "glossary.md"
    if not book_glossary.is_file():
        raise Refusal("the book has no glossary.md — the acronym table is undeclared")
    in_acronyms = False
    for line in book_glossary.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("## "):
            in_acronyms = line.strip() == ACRONYMS_HEADING
            continue
        if not in_acronyms:
            continue
        m = ACRONYM_ROW.match(line.strip())
        if not m:
            continue
        acronym = m.group(1).strip()
        if acronym in ("Acronym", "---", ":---") or set(acronym) <= {"-", ":"}:
            continue
        terms.append((acronym, "glossary.md#the-acronyms-this-book-uses", [acronym]))
    if not any(t[1].endswith("#the-acronyms-this-book-uses") for t in terms):
        raise Refusal(
            f"the acronym table ('{ACRONYMS_HEADING}') is missing or empty in glossary.md"
        )
    return terms


def discusses(text: str, aliases: list[str]) -> bool:
    for alias in aliases:
        pat = re.compile(
            r"(?<![A-Za-z0-9_])" + re.escape(alias) + r"(?![A-Za-z0-9_])", re.IGNORECASE
        )
        if pat.search(text):
            return True
    return False


def render(book: Path, glossary: Path) -> str:
    chapters = read_chapters(book)
    terms = read_terms(book, glossary)
    scannable = [c for c in chapters if c[1] not in SCAN_EXCLUDED]

    lines = [
        "# Index",
        "",
        GENERATED_HEADER,
        "",
        "Every governed term — the canonical glossary's contract terms and the book's acronym"
        " table — with the",
        "chapters that discuss it, in reading order. A term with no discussion chapter is a"
        " defined term the",
        "chapters have not needed yet; it is indexed, not dropped.",
        "",
        "| Term | Defined in | Discussed in |",
        "| --- | --- | --- |",
    ]
    for display, defined, aliases in sorted(terms, key=lambda t: t[0].casefold()):
        hits = [f"[{title}]({rel})" for title, rel, text in scannable
                if discusses(text, aliases)]
        discussed = ", ".join(hits) if hits else "—"
        lines.append(f"| {display} | [Glossary]({defined}) | {discussed} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="compare the regenerated bytes against --out; write nothing")
    ap.add_argument("--book", default="docs/book", help="the mdBook directory")
    ap.add_argument("--glossary", default="docs/GLOSSARY.md",
                    help="the canonical glossary")
    ap.add_argument("--out", default="docs/book/src/index.md", help="the generated index")
    args = ap.parse_args()

    book, glossary, out = Path(args.book), Path(args.glossary), Path(args.out)
    try:
        content = render(book, glossary)
    except Refusal as exc:
        print(f"gen_book_index: REFUSED — {exc}", file=sys.stderr)
        return 2

    if args.check:
        if not out.is_file():
            print(f"gen_book_index: DRIFT — {out} does not exist; generate it:\n"
                  f"  python3 scripts/gen_book_index.py", file=sys.stderr)
            return 1
        if out.read_text(encoding="utf-8") != content:
            print(f"gen_book_index: DRIFT — {out} is not what the book's text derives.\n"
                  f"  Regenerate — never edit: python3 scripts/gen_book_index.py",
                  file=sys.stderr)
            return 1
        return 0

    out.write_text(content, encoding="utf-8")
    n_terms = content.count("\n| ") - 2  # minus the header and separator rows
    print(f"gen_book_index: wrote {out} ({len(content)} bytes, {n_terms} indexed terms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
