#!/usr/bin/env python3
"""Generate the reusable definition FRAGMENTS the repository owns.

A fragment is a complete, independently checkable description of one thing — an ISA base, an
extension — and lives under `definitions/` because it is shared by every unit that composes it.
A unit's `encoding.sexp` names fragments; it never carries a copy of an instruction.

⛔ THE GAP THIS CLOSES, measured. Before this file existed the assembler read its encodings from
`target/refs/riscv-opcodes` — untracked and network-acquired — so `git ls-files | grep -c
riscv-opcodes` returned `0` and a fresh clone could not build a model at all. The project's own
rule is that a constant which is a function of an external document is derived or gated, never
assumed present; its own tooling was breaking that rule.

The generated file is TRACKED, so the repository owns its encodings, and `fetch_references.sh`
re-derives it against the pinned upstream whenever that upstream is present. Ownership without a
re-derivation would just be a copy.

Usage:  scripts/gen_fragments.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

ROOT = Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True, check=True).stdout.strip())
UPSTREAM = ROOT / "target/refs/riscv-opcodes"
SOURCE_FILES = ("rv_i", "rv64_i", "arg_lut.csv", "constants.py")
# Only the operand fields this profile's instructions actually use are emitted: an encoding file
# listing fields nothing references would invite a reader to believe they are supported. `fm`,
# `pred` and `succ` are FENCE's (`P2-SCALAR.1`: a guest assembles `fence`, and the fields come
# from the pinned `arg_lut.csv` like every other — derived, never typed).
USED_FIELDS = ("rd", "rs1", "rs2", "imm12", "imm20", "shamtd", "shamtw",
               "imm12hi", "imm12lo", "jimm20", "bimm12hi", "bimm12lo",
               "fm", "pred", "succ")

def sha256(path: Path) -> str:
    return subprocess.run(["shasum", "-a", "256", str(path)],
                          capture_output=True, text=True, check=True).stdout.split()[0]


FRAGMENTS = (
    ("definitions/riscv/rv64i.sexp", "riscv/rv64i", "isa-base", ("rv_i", "rv64_i"), "", True,
     "The RV64I base: the 52 instructions every RV64 profile starts from. Carries the operand "
     "field table and the scattered-immediate layouts, because a base defines the formats its "
     "extensions reuse."),
    ("definitions/riscv/m.sexp", "riscv/m", "isa-extension", ("rv_m", "rv64_m"), '"riscv/rv64i"',
     False,
     "The M extension: integer multiply and divide. REQUIRES a base, because it reuses the base's "
     "R-type operand fields and defines none of its own — a fragment with a hidden dependency is a "
     "fragment that composes by luck."),
)


def regenerate() -> int:
    from riscv_asm import load_arg_lut, load_encodings, load_immediate_layout
    arg_lut = load_arg_lut(UPSTREAM / "arg_lut.csv")
    layout = load_immediate_layout(UPSTREAM / "constants.py", arg_lut)
    for rel, fid, kind, tables, requires, with_fields, note in FRAGMENTS:
        insns = load_encodings([UPSTREAM / t for t in tables])
        L = [f";; {Path(rel).name} — a reusable definition FRAGMENT ({kind}).", ";;",
             ";; A fragment is a complete, independently checkable description of ONE thing. It",
             ";; lives here rather than inside a profile because a base ISA is shared by every",
             ";; profile that composes it — copying it per profile would be the duplication the",
             ";; composition model exists to avoid. A unit COMPOSES fragments;",
             ";; `scripts/check_encoding_disjoint.py` decides whether a composition is legal.", ";;",
             f";; {note}", ";;",
             ";; Generated by `scripts/gen_fragments.py`. Do not edit by hand.", "",
             "(fragment", f'  (id "{fid}")', f"  (kind {kind})",
             f"  (requires {requires})" if requires else "  (requires)", "  (source"]
        for t in tables:
            L.append(f'    (file (name "{t}") (sha256 "{sha256(UPSTREAM / t)}"))')
        L += ['    (origin "https://github.com/riscv/riscv-opcodes")',
              '    (license "BSD-3-Clause"))', ""]
        if with_fields:
            L.append("  ;; ---- operand field positions, inclusive bit ranges ------------------")
            for n in USED_FIELDS:
                hi, lo = arg_lut[n]
                L.append(f"  (field (name {n}) (hi {hi}) (lo {lo}))")
            L += ["", "  ;; ---- immediates SCATTERED across their field, MSB piece first -------"]
            for n in sorted(layout):
                hi, lo = arg_lut[n]
                pieces = " ".join(f"({h} {l})" for h, l in layout[n])
                L.append(f"  (scatter (name {n}) (hi {hi}) (lo {lo}) (pieces {pieces}))")
            L.append("")
        L.append(f"  ;; ---- {len(insns)} instruction(s) ----")
        for name in sorted(insns):
            i = insns[name]
            fixed = " ".join(f"({h} {lo} {v:#x})" for h, lo, v in i.fixed)
            ops = " ".join(str(o) for o in i.operands)
            L.append(f'  (insn (name {name}) (fixed {fixed}) (operands {ops}) (from "{i.source}"))')
        L.append(")")
        (ROOT / rel).write_text("\n".join(L) + "\n")
    return len(FRAGMENTS)


def main(argv: list[str]) -> int:
    if not UPSTREAM.is_dir():
        print(f"gen_fragments: {UPSTREAM} is absent — run scripts/fetch_references.sh first",
              file=sys.stderr)
        return 2
    n = regenerate()
    print(f"regenerated {n} fragment(s) under definitions/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
