;; category-needs.sexp — the category-needs catalogue (MODEL-METHOD.2, census revised by
;; MODEL-METHOD.3). One (category-need …) per docs/INFORMATION_CATALOG.md category per unit;
;; validate with
;;   python3 scripts/check_sexp_schema.py category-needs.sexp schema/category-needs.sexp
;; Dispositions are honest about ABSENT vs NEVER-NEEDED vs OWNED-ELSEWHERE: `missing` (a reason
;; is owed, naming what would close it) means the unit requires the category and the facts are
;; not part of this unit's model — the profile EXCLUDES the subsystem; `out-of-scope` means the
;; unit never owed it; `deferred-to-board` means P5-BOARD owns it and the CPU records an
;; assumption in its place. The census evidence (2026-09-27): every `covered` row's subject
;; matter was found in the pinned snapshot's pages, and the excluded subsystems' chapters
;; (f/d/q/v/a-st-ext, rvwmo, counters, zicsr) are present in that same snapshot — `missing`
;; rows close with a profile revision, not (mostly) with new material.

(category-need (category "C01") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C02") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C03") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C04") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C05") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C06") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C07") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition missing) (reason "F and D are excluded from this profile, so floating-point numerics are not part of this unit's model. Closing: an F/D-admitting profile revision; the pinned snapshot's f-st-ext, d-st-ext and q-st-ext chapters already carry the facts.") (material "RVI-PINNED-V20260120"))
(category-need (category "C08") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition missing) (reason "V is excluded from this profile, so vector semantics are not part of this unit's model. Closing: a vector unit; v-st-ext.html is already in the pinned snapshot.") (material "RVI-PINNED-V20260120"))
(category-need (category "C09") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition partial) (reason "In-order, single-hart, one-operation-at-a-time is declared (no interlock, forwarding or issue-group questions arise); the sequencing facts the category asks for are absent by construction, not by gap.") (material "RVI-PINNED-V20260120"))
(category-need (category "C10") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C11") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C12") (layer system) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition missing) (reason "Translation is excluded (no MMU, no S/U modes). Closing: the RISC-V Privileged Architecture manual — a separate volume, absent from this unprivileged snapshot — pinned at the first translated unit."))
(category-need (category "C13") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition partial) (reason "Code visibility is decided as a laboratory policy (re-fetch every instruction); the Zifencei maintenance questions are absent from this profile by exclusion (zifencei.html is in the snapshot, unused).") (material "RVI-PINNED-V20260120"))
(category-need (category "C14") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition partial) (reason "Only requested traps (ECALL/EBREAK) exist; interrupt sources, nesting, and delivery are excluded with the privilege modes. Closing: the Privileged Architecture manual at the first privileged unit.") (material "RVI-PINNED-V20260120"))
(category-need (category "C15") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition missing) (reason "Privilege modes beyond M are not modelled. Closing: the RISC-V Privileged Architecture manual (a separate volume) pinned at the first privileged unit."))
(category-need (category "C16") (layer system) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition missing) (reason "One hart and no atomics: the memory-consistency questions are excluded from this unit's model. Closing: MC-MULTICORE's unit — rvwmo.html and a-st-ext.html are already in the pinned snapshot; what is missing is the multicore profile and its tests, not the material.") (material "RVI-PINNED-V20260120"))
(category-need (category "C17") (layer board) (kind "datasheet") (unit "rv64i-lab-v0") (disposition out-of-scope) (reason "Reset and time are the harness's concern in this laboratory — the CPU/environment contract owns them as assumptions (OB-ENV-RESET, OB-ENV-VIRTUAL-TIME), so the processor unit does not owe this category; the board that replaces the harness will."))
(category-need (category "C18") (layer system) (kind "debug-spec") (unit "rv64i-lab-v0") (disposition missing) (reason "No debug entry, trace, or counters exist in this profile (Zicntr/Zihpm excluded). Closing: the RISC-V Debug specification, a separate document, at the first debuggable unit; counters.html and zicsr.html in the snapshot supply the counter questions once CSRs are in."))
(category-need (category "C19") (layer board) (kind "datasheet") (unit "rv64i-lab-v0") (disposition deferred-to-board) (reason "Device and interconnect categories are P5-BOARD's to own, not the CPU's: the laboratory declares exactly one main-memory region and no devices, and the CPU records an environment assumption (OB-ENV-*) in this category's place."))
(category-need (category "C20") (layer board) (kind "abi-spec") (unit "rv64i-lab-v0") (disposition deferred-to-board) (reason "The program environment is the board's, but the run-real-code set is now acquired and digest-pinned (MODEL-METHOD.4): the psABI canonical render, the System V ELF specification, the generic syscall header (the hosted exit convention), and the compiler-rt builtins inventory — cached under .materials/run-real-code/, anchored in the owning leaf."))
(category-need (category "C21") (layer board) (kind "datasheet") (unit "rv64i-lab-v0") (disposition deferred-to-board) (reason "External input and co-simulation scheduling are the harness/board boundary; the processor unit records its replay contract (OB-ENV-ORDERING) and defers the input categories to the board that drives it."))
(category-need (category "C22") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C23") (layer processor) (kind "isa-manual") (unit "rv64i-lab-v0") (disposition covered) (material "RVI-PINNED-V20260120"))
(category-need (category "C24") (layer processor) (kind "model-contract") (unit "rv64i-lab-v0") (disposition partial) (reason "The observation contract declares determinism, replay-relevant state and stop reasons; snapshot and versioning policy are declared for P1, not yet built — closing is P1-LAB's evidence, not new material."))
(category-need (category "C01") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C02") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C03") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C04") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C05") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C06") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C07") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition out-of-scope) (reason "No floating point exists in the DSP56300 architecture — the unit never owed this category, and no profile revision can close it."))
(category-need (category "C08") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition out-of-scope) (reason "No SIMD/vector lanes exist in the architecture; the parallel-move dual feed is an issue-group question (C09), not lanes."))
(category-need (category "C09") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition partial) (reason "Scalar issue is declared (REP is a single-instruction repeat; the F5 pending-writes window was measured ABSENT). The parallel-move dual feed is EXCLUDED from subset v0 as the named first extension candidate — its old/new-operand visibility questions arrive with that extension, not before.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C10") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition partial) (reason "The X/Y/P spaces and the seven linear (Rn) modes are covered; modulo and reverse-carry addressing are excluded from subset v0 by name. Closing: a corpus extension — the FM's AGU chapters carry the facts.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C11") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition partial) (reason "Moves within the three spaces are covered; the fault and side-effect axes are excluded with the peripherals — this laboratory declares no I/O region, so no access has a side effect.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C12") (layer system) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition out-of-scope) (reason "No MMU or translation exists in the DSP56300 architecture — addresses are physical in every space."))
(category-need (category "C13") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition partial) (reason "Fetch re-reads P space per instruction (the laboratory's declaration); the reference treats cache-control operations as NOPs (its LIMITATIONS), and the subset decodes none. The visibility questions are absent by exclusion, stated rather than assumed.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C14") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition missing) (reason "Interrupts and traps are excluded from subset v0 by name (the subset decision). Closing: an interrupt-admitting corpus revision — the FM's exception/interrupt chapters carry the facts, and the reference's unverified-peripheral-interrupt gap bounds what they would buy.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C15") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition missing) (reason "Operating modes (SA/SC/DM) are excluded; the reference stores the mode bits but treats them as inert (LIMITATIONS). Closing: a mode-admitting profile revision.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C16") (layer system) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition out-of-scope) (reason "One core, no atomics: the DSP56300 architecture has no multicore memory-consistency model to owe."))
(category-need (category "C17") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition partial) (reason "Reset is the unit's own decision (D-RESET-STATE, FM Table 5-1, cross-checked against the reference's observed reset dump). Idle (STOP/WAIT) and ALL timing are excluded by name — cyc is informational and never compared.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C18") (layer system) (kind "debug-spec") (unit "dsp56300-lab-v0") (disposition missing) (reason "The OnCE debug port is excluded from subset v0. Closing: a debug-admitting revision — the FM carries the OnCE chapters.") (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C19") (layer board) (kind "datasheet") (unit "dsp56300-lab-v0") (disposition deferred-to-board) (reason "Peripherals and devices are P5-BOARD's to own: the laboratory declares three memory spaces and no devices, and the unit records environment assumptions (OB-ENV-*) in this category's place."))
(category-need (category "C20") (layer board) (kind "abi-spec") (unit "dsp56300-lab-v0") (disposition deferred-to-board) (reason "The program environment — the .lod image, the load base, the case meta — is the harness's contract; the board that boots real firmware owns the category."))
(category-need (category "C21") (layer board) (kind "datasheet") (unit "dsp56300-lab-v0") (disposition deferred-to-board) (reason "Subset v0 has no external inputs: the runner is deterministic from the case file, and the board boundary owns injection and co-simulation scheduling."))
(category-need (category "C22") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C23") (layer processor) (kind "isa-manual") (unit "dsp56300-lab-v0") (disposition covered) (material "NXP-DSP56300-FAMILY-MANUAL"))
(category-need (category "C24") (layer processor) (kind "model-contract") (unit "dsp56300-lab-v0") (disposition partial) (reason "The observation contract declares typed ModelStops and the canonical-dump comparison surface; snapshot/replay and versioning policy are not built for this unit — the census's consequence (the dump IS the complete architectural state) is what makes them honest when built."))
